plugins/reddit/PLUGININFO, plugins/reddit/__init__.py, pynicotine/gtkgui/about.py, pynicotine/gtkgui/chatrooms.py, pynicotine/pluginsystem.py, pynicotine/pynicotine.py
Exposes additional network messages to plugin system.
Implements command '/toggle' to toggle plugin on/off.
Adds one new plugin.
gtkgui/chatrooms.py -
- Add /toggle to toggle plugin on / off.  Removed never implemented and unneeded /reload code.
gtkgui/about.py -
- Add info about /toggle
pynicotine.py -
- Add notification-type calls to plugin system for SearchRequest, DistribSearch, PublicRoomMessage network messages.
pluginsystem.py -
- some code clean up
- toggle_plugin added to toggle plugin on/off
- load_plugin set to reload plugin by default
- Added SearchRequestNotification, DistribSearchNotification, PublicRoomMessageNotification.
- Added ResponseThrottle class - optional functionality to deal with plugins that reply in chatrooms.
pluginsystem/reddit -
- New plugin intended as …
=> Implement plugin system enhancements

README.md
straightforward enough, i think
=> fix typo and grammatical corrections

pynicotine/metadata_mutagen.py
Just removing those _<<EEK, what should I do with <class 'mutagen.oggopus.OggOpusInfo'> ({somesongdirhere}.opus)?>>_ messages spamming the console
=> Added ogg/Opus metadata check

pynicotine/config.py, pynicotine/gtkgui/about.py, pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/transferlist.py, pynicotine/gtkgui/uploads.py, pynicotine/gtkgui/userlist.py
Save and load column widths for various tabs so that the layout is persistent.
=> Save column widths for userlist, downloads, uploads, searches tabs

nicotine, pynicotine/config.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/userbrowse.py, pynicotine/pluginsystem.py, pynicotine/pynicotine.py, pynicotine/shares.py, pynicotine/utils.py
This pull request implements support for the XDG Base Directory specification, as discussed in #94.
I've tested the changes manually in my arch linux box, and everything seems to work.
Let me know if there's anything to be improved or fixed here.
=> XDG Base Directory Support (#94)

pynicotine/config.py, pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/uploads.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userinfo.py
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/79
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/8
A few ranges were incorrect, causing the visibility status to not be set for the last column.
=> Column fixes

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/privatechat.py
Gtk.TextBuffer.get_text() requires an extra parameter now: https://lazka.github.io/pgi-docs/Gtk-3.0/classes/TextBuffer.html#Gtk.TextBuffer.get_text
=> Fix text copying and some leftovers

pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/nowplaying.py, pynicotine/gtkgui/ui/nowplaying.ui, pynicotine/gtkgui/userinfo.py
(Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/53)
- Make add to player functionality work in python3
- Remove Banshee from NowPlaying, since it's dead
- Fix python3 errors in mpd and audacious code
- Don't create new threads for GetNP, since accessing the TextBuffer in a different thread is unsafe (crashes). Performance-wise this shouldn't be noticeable when using the program, in my case it was even faster.
- Use GStreamer 1.0 instead of 0.10
=> Player-related corrections

pynicotine/gtkgui/about.py, pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/ui/fastconfigure.ui, pynicotine/gtkgui/ui/nowplaying.ui, pynicotine/gtkgui/ui/settingswindow_AutoReplaceFrame.ui, pynicotine/gtkgui/ui/settingswindow_CensorFrame.ui, pynicotine/gtkgui/ui/settingswindow_PluginFrame.ui, pynicotine/gtkgui/ui/settingswindow_SharesFrame.ui, pynicotine/gtkgui/ui/settingswindow_TreeView.ui, pynicotine/gtkgui/ui/settingswindow_UrlCatchFrame.ui, pynicotine/gtkgui/ui/settingswindow_UserinfoFrame.ui, pynicotine/gtkgui/ui/userinfo.ui, pynicotine/gtkgui/userinfo.py, pynicotine/gtkgui/utils.py
- Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/146
- Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/145
- Fixes the character issue in https://github.com/Nicotine-Plus/nicotine-plus/issues/144
- UI spacing fixes in a few locations
- Adds a button to reset/remove your user pic
- Removed plugin install/update UI, since there was functionality coded for them
=> Multiple fixes

pynicotine/gtkgui/frame.py, pynicotine/gtkgui/ui/buddylist.ui, pynicotine/gtkgui/ui/chatrooms.ui, pynicotine/gtkgui/ui/mainwindow.ui, pynicotine/gtkgui/ui/privatechat.ui, pynicotine/gtkgui/ui/roomlist.ui, pynicotine/gtkgui/ui/search.ui, pynicotine/gtkgui/ui/userbrowse.ui, pynicotine/gtkgui/ui/userinfo.ui, pynicotine/gtkgui/utils.py
Fixed a lot of UI spacing and border inconsistencies.
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/151
=> Improved UI spacing

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/utils.py
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/147
=> Fix clicking on username in log view

pynicotine/gtkgui/frame.py
So... many... hidden... features.
=> Fix interest menu on user info page

setup.py
Closes https://github.com/Nicotine-Plus/nicotine-plus/pull/158
I forgot you can't move files at this stage.
=> Fix incorrect plugin move

pynicotine/gtkgui/ui/userinfo.ui, pynicotine/gtkgui/userinfo.py, pynicotine/slskmessages.py
Allow sending raw bytes to prevent messing up image data.
User with image for testing: orangeman
=> Fix picture loading in user info view

setup.py
Fixes some installation issues found while updating the Nix package; see the commit messages for details.
*Edit:* Fixes #158; resolves #159.
=> setup.py: installation fixes

pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/ui/settingswindow_UserinfoFrame.ui
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/149
=> Add image chooser preview

pynicotine/slskproto.py
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/100
=> Workaround for struct.pack integer limit

pynicotine/gtkgui/search.py
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/91
=> Include full file path in filter

doc/TODO.md, pynicotine/upnp.py
Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/63
=> Make UPnP work again 

pynicotine/gtkgui/frame.py, pynicotine/gtkgui/ui/userinfo.ui, pynicotine/gtkgui/userinfo.py
Fixes (again) https://github.com/Nicotine-Plus/nicotine-plus/issues/144
Oversight in https://github.com/Nicotine-Plus/nicotine-plus/pull/171
Also simplified picture handling a bit.
=> Remove quotation marks from own description

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/uploads.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userinfo.py, pynicotine/gtkgui/userlist.py, pynicotine/gtkgui/utils.py
Attaching them to parent widgets causes style issues (as seen in https://github.com/Nicotine-Plus/nicotine-plus/issues/181).
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/181
=> Attach menus to window

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/uploads.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userlist.py, pynicotine/gtkgui/utils.py
I broke submenu functionality in https://github.com/Nicotine-Plus/nicotine-plus/pull/184, since they rely on the frame to access data. Here's an alternative approach.
=> Make submenus functional again

doc/SLSKPROTOCOL.md
Converted from https://www.nicotine-plus.org/wiki/SoulseekProtocol
=> Add Soulseek protocol doc from old wiki

pynicotine/gtkgui/privatechat.py
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/194
=> Fix typo and incorrect menu attachment

pynicotine/gtkgui/userinfo.py
Was supposed to return the tag there. Sorry about that.
=> Add missing return statement

pynicotine/gtkgui/transferlist.py, pynicotine/slskmessages.py
These were supposed to be parsed as long, not int.
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/192
=> Don't use incorrect type when getting objects

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/transferlist.py, pynicotine/gtkgui/uploads.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userlist.py
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/202
=> Handle column update gracefully

files/nicotine.desktop
Just a minor thing that has irked me for a while.
=> Change application name in desktop file

pynicotine/gtkgui/about.py, pynicotine/gtkgui/frame.py
Less custom stuff to maintain.
=> Use GtkAboutDialog

pynicotine/transfers.py, pynicotine/utils.py
The functionality existed, but wasn't applied correctly.
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/101
=> Fix downloading of invalid char files on Windows

.github/workflows/tests.yml, nicotine, plugins/multipaste/__init__.py, pynicotine/config.py, pynicotine/gtkgui/about.py, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/nowplaying.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userinfo.py, pynicotine/gtkgui/utils.py, pynicotine/metadata_mutagen.py, pynicotine/pynicotine.py, pynicotine/slskmessages.py, pynicotine/slskproto.py, pynicotine/transfers.py, pynicotine/utils.py
Let's start enforcing these style checks.
=> Lint cleanup

pynicotine/gtkgui/fastconfigure.py, pynicotine/gtkgui/ui/fastconfigure.ui
Fixes some previous issues with excessive window width.
=> Refresh fast configure design

setup.cfg
Depends on https://github.com/Nicotine-Plus/nicotine-plus/pull/213 for gsound
=> Update rpm dependencies

pynicotine/gtkgui/search.py
There is no point in creating a new thread every time we add a new search result, and it messes up the result count and numbering pretty badly. Also reduce the number of new rows that are created (remove encoded_row), and bail out earlier in the chain if result limit is reached.
=> Don't create new thread for every search result

pynicotine/gtkgui/tray.py
https://github.com/Nicotine-Plus/nicotine-plus/commit/f47ebaae89b3d8b07cbcad6fe7ff8106f5b0da87#commitcomment-39584334
=> Accept tray icon formats other than png

pynicotine/gtkgui/frame.py, pynicotine/gtkgui/ui/mainwindow.ui
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/42
=> Add option to hide buddy list

pynicotine/gtkgui/search.py
Forgot to change these in https://github.com/Nicotine-Plus/nicotine-plus/pull/224
=> Use correct element index for file name and size

pynicotine/config.py, test/integration/nicotine.robot, test/integration/nicotine_library.py
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/228
=> Add checks for settings window when updating config

_config.yml, pynicotine/utils.py
Look for nicotine.mo, not messages.mo.
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/155
=> gettext: set text domain

pynicotine/gtkgui/frame.py, pynicotine/gtkgui/ui/mainwindow.ui, pynicotine/pynicotine.py
Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/186
I don't really want to mess around with the logic of status and non-status messages, so I've changed the no-privileges message to be more descriptive and make more sense in the context of the status bar. A new item for getting privileges has been added into the menu. Also added a tooltip for the status bar, since a lot of messages get truncated.
=> Tweaks to privilege-related functionality

plugins/memory_debugger/__init__.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/settingswindow.py, pynicotine/pluginsystem.py
Unchecking the "Enable plugins" checkbox would not disable plugins completely, causing a nasty exception spam. Also removed some dead code.
=> Properly disable plugins

pynicotine/gtkgui/search.py, pynicotine/gtkgui/userlist.py
Fixes everything in https://github.com/Nicotine-Plus/nicotine-plus/issues/246 except for the GTK warnings.
=> Minor fixes

pynicotine/gtkgui/frame.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/tray.py
For OSes that don't support AppIndicator (Windows, maybe MacOS?).
=> Add GtkStatusIcon fallback

.github/ISSUE_TEMPLATE/1-bug-report.md, .github/ISSUE_TEMPLATE/2-feature-request.md, .github/ISSUE_TEMPLATE/3-other.md, .github/ISSUE_TEMPLATE/config.yml
Add some basic issue templates to ease development and label assignment.
=> Add issue templates

pynicotine/pluginsystem.py
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/271
=> Use correct syntax for importlib

pynicotine/gtkgui/chatrooms.py
Instead of sorting the ticker list every time a new ticker is added, we set a flag to indicate that the ticker list should be sorted on the next scroll.
Also stop sorting the list when removing tickers, since it's pointless, and use one list for messages instead of a separate sortedmessages list.
Reduces the number of function calls after sorting from ~20000 to 200 in the nicotine chat room. Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/245
=> Smarter ticker sorting

pynicotine/gtkgui/chatrooms.py
Small oversight in https://github.com/Nicotine-Plus/nicotine-plus/pull/274
=> Fix get_tickers function

pynicotine/config.py, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/entrydialog.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/userbrowse.py, pynicotine/slskmessages.py
While this didn't solve https://github.com/Nicotine-Plus/nicotine-plus/issues/267, using the newest protocol available can still bring benefits. See https://docs.python.org/3/library/pickle.html#pickle-protocols
=> Use the highest pickle protocol available

NEWS, pynicotine/gtkgui/search.py
Add all the required information into the initial row, instead of creating a new, temporary one later. Also closes https://github.com/Nicotine-Plus/nicotine-plus/issues/278
=> Use one less temporary row when appending search result

pynicotine/config.py
PR for handling any uncaught exceptions when out of storage.
=> Handle more cases when out of storage

pynicotine/gtkgui/frame.py, pynicotine/gtkgui/settingswindow.py, pynicotine/pynicotine.py, pynicotine/utils.py
Replaced eval, due to its unsafe nature.
=> Unescape outgoing user descriptions

NEWS, pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/transferlist.py, pynicotine/gtkgui/uploads.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/utils.py
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/297
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/300
=> Properly select treeview rows on right-click

NEWS, pynicotine/gtkgui/search.py
Turns out our little slash buddy here was causing issues. :P
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/301
=> Make "Download containing folders to"-feature work again

pynicotine/gtkgui/frame.py, pynicotine/gtkgui/tray.py, pynicotine/pluginsystem.py, pynicotine/utils.py
Uses /app for Flatpak instead of /usr.
=> Detect install prefix when running

NEWS, pynicotine/transfers.py
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/305
=> Don't add duplicate downloads

NEWS, pynicotine/gtkgui/transferlist.py, pynicotine/transfers.py
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/302
=> Don't count filtered files into total percentage

doc/SLSKPROTOCOL.md, pynicotine/gtkgui/userinfo.py, pynicotine/pynicotine.py, pynicotine/slskmessages.py
There's no need to explicitly send a GetUserStats message to the server, since the server already sends changes automatically.
=> Add better documentation for AddUser and GetUserStats

NEWS, pynicotine/slskproto.py, pynicotine/transfers.py
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/201
=> Add support for >2GB downloads

NEWS, pynicotine/gtkgui/ui/mainwindow.ui, pynicotine/transfers.py
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/336
=> Re-add auto-retry downloads

doc/TRANSLATORS.md, pynicotine/gtkgui/about.py
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/348
=> Update translation credits

pynicotine/gtkgui/uploads.py
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/354
=> Show uploads expand button when supposed to

pynicotine/gtkgui/frame.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/utils.py
Eliminates most of the GUI freezes when searching for terms with many results.
=> Additional search result optimizations

pynicotine/gtkgui/frame.py, pynicotine/pynicotine.py, pynicotine/slskmessages.py, pynicotine/slskproto.py, pynicotine/transfers.py
Fixes the original issue in https://github.com/Nicotine-Plus/nicotine-plus/issues/346
=> Tweaks to open files limit

NEWS, pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/transferlist.py, pynicotine/gtkgui/uploads.py, pynicotine/gtkgui/utils.py, pynicotine/transfers.py
- Drop remaining references to removed "transfers" attribute. Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/360 (happened when an upload was paused). Fixes the feature to select a user's transfers.
- Reduced code duplication
=> Remove some leftovers in transfers view

pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/transferlist.py, pynicotine/gtkgui/uploads.py, pynicotine/gtkgui/utils.py, pynicotine/metadata_mutagen.py, pynicotine/transfers.py, pynicotine/utils.py
- Remove some old, unnecessary sorting code
- General simplification of code
- Don't show transfer status (time elapsed, time left, speed) when not necessary (e.g. timer and speed was frozen when aborting a download, now they're not shown)
=> Simplify column sorting

plugins/leech_detector/PLUGININFO, plugins/leech_detector/__init__.py, pynicotine/gtkgui/settingswindow.py
https://github.com/Nicotine-Plus/nicotine-plus/pull/359#issuecomment-654091371
=> Multiline support for leech messages

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/entrydialog.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/ui/nowplaying.ui, pynicotine/gtkgui/utils.py
- The loop should finish, not end abruptly.
- Cosmetics
=> Fix error in tab visibility loop code

pynicotine/config.py
https://github.com/moreati/pickle-fuzz#pickle
=> Add restricted unpickler

NEWS, pynicotine/config.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/ui/settingswindow_SearchFrame.ui, pynicotine/gtkgui/utils.py
- Add option to remove special characters from search terms, enabled by default. Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/343
- Add functional search result word filtering (put "-" in front of a word), like the official client has
- Filter out inexact or incorrect search results client-side, like the official client does
Don't merge yet.
=> Search result improvements

NEWS, pynicotine/gtkgui/ui/mainwindow.ui, pynicotine/transfers.py
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/374
=> Autoclear filtered downloads

pynicotine/transfers.py
Chances are it won't succeed. Give it a slight cooldown, and let the 1 min timer do the job.
=> Don't re-attempt to download file immediately

NEWS, pynicotine/gtkgui/frame.py
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/384
=> Case-insensitive text search

pynicotine/gtkgui/ui/settingswindow_TreeView.ui
Prevents some elements from being cut off in Windows.
=> Increase width of settings window

NEWS, pynicotine/upnp.py
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/385
=> UPnP: use local IP detected by miniupnp

README.md
Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/102
=> Add link to Flathub

.github/workflows/autopkgtest.yml, .github/workflows/tests.yml, debian/changelog, files/windows/nicotine.nsi, pynicotine/gtkgui/checklatest.py, pynicotine/utils.py
The update checker would display the whole json response instead of the version number.
=> Fix issue in update checker

README.md, doc/DEPENDENCIES.md, doc/PACKAGING.md, doc/RUNFROMGIT.md
- Since dependencies are important to both people who want to run from git and packagers I created DEPENDENCIES.md and I move various dependencies mentions in other files to this one, replacing them with links to the new file
- Move licence next to legal stuff
- Improve the descriptions a bit
- Improve wording a bit
- Improve the layout a bit
=> Improve documentation a bit.

README.md
They now ship Nicotine+ 2.0.1.
=> Add Void Linux install instructions

debian/changelog, files/windows/nicotine.nsi, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/checklatest.py, pynicotine/utils.py
The ticker message itself is not sent with the ticker removal message, so we can only depend on the username to remove tickers.
=> Fix bug in ticker removal code

pynicotine/gtkgui/frame.py
Cache a few hot spots instead of constantly accessing the translation files.
=> Reduce translation string file calls

MANIFEST.in, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/ui/buddylist.ui, pynicotine/gtkgui/ui/chatrooms.ui, pynicotine/gtkgui/ui/fastconfigure.ui, pynicotine/gtkgui/ui/nowplaying.ui, pynicotine/gtkgui/ui/privatechat.ui, pynicotine/gtkgui/ui/roomlist.ui, pynicotine/gtkgui/ui/search.ui
Removes all deprecated properties from the UI files.
=> Convert ui files to GTK3, part 1

pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/ui/mainnotebook.ui, pynicotine/gtkgui/ui/mainwindow.ui, pynicotine/gtkgui/ui/userbrowse.ui, pynicotine/gtkgui/ui/userinfo.ui, pynicotine/gtkgui/uploads.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/utils.py
Removes all deprecated properties from the UI files.
=> Convert ui files to GTK3, part 2

pynicotine/gtkgui/frame.py, pynicotine/gtkgui/ui/mainwindow.ui
See https://github.com/Nicotine-Plus/nicotine-plus/issues/430#issuecomment-663632509
Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/430
=> Remove menu item to rebuild share

.github/workflows/autopkgtest.yml, .github/workflows/tests.yml, test/unit/mock_socket.py
The next step is to generate exe installers with GitHub Actions, so we don't have to depend on my Windows VM to generate them.
=> Run unit tests in Windows

pynicotine/gtkgui/search.py, pynicotine/gtkgui/userbrowse.py, pynicotine/transfers.py
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/313
=> Handle duplicate download folders

pynicotine/gtkgui/transferlist.py
Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/308
=> Allow selecting all child transfers in grouped mode

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/transferlist.py, pynicotine/gtkgui/userlist.py, pynicotine/transfers.py
- Reduce the number of lists used to store data
- Improve code consistency and readability
- Disable a few popup items for offline users
=> Simplify buddy list code

.github/workflows/autopkgtest.yml, .github/workflows/packaging.yml, .github/workflows/tests.yml, README.md, files/macos/dependencies.sh, files/macos/nicotine.spec, pynicotine/slskproto.py
I can't confirm that these packages actually work, since I have no means of testing them at the moment, but they are available if any MacOS users want to help us out.
=> Untested MacOS support

debian/changelog, files/windows/nicotine.nsi, pynicotine/gtkgui/roomlist.py, pynicotine/gtkgui/ui/roomlist.ui, pynicotine/utils.py
We sent a message to the server before we were logged in, which delayed the login process.
=> Fix login delay issue

pynicotine/gtkgui/utils.py
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/457
=> Properly detect URLs

pynicotine/gtkgui/search.py
We can't call OnFilterChanged before the results model is created.
=> Initialize search filters later

pynicotine/gtkgui/chatrooms.py
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/464
=> Always show auto-join checkbox

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/userlist.py
It's broken, and nobody has opened an issue. I don't think anyone uses it.
=> Remove user drag-and-drop feature

pynicotine/shares.py
The pywin32 dependency most likely won't work in msys2 for a long time, and Python 3.5 introduced a better way of checking the hidden attribute of a file. https://bugs.python.org/issue21719
=> Use better way of checking hidden files on Windows

pynicotine/gtkgui/ui/mainwindow.ui
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/474
=> Set window width limit to the width of the main notebook

pynicotine/gtkgui/chatrooms.py
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/466
=> Allow right-clicking on usernames in chatrooms

pynicotine/config.py, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/transferlist.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userlist.py, pynicotine/gtkgui/utils.py
- Ensure the width of the last column in a treeview is always dynamic, to make resizing of columns easier.
- Align the contents of a few columns to the right
=> Improvements to columns

pynicotine/config.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/transferlist.py, pynicotine/gtkgui/utils.py
Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/438
=> Improve treeview readability and show reverse folder names

pynicotine/gtkgui/search.py, pynicotine/gtkgui/ui/search.ui
=> Add button for filter help on search page

pynicotine/gtkgui/transferlist.py
Only necessary when searching. Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/438#issuecomment-669846682
=> Prevent accidental removal of character in path

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/dialogs.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/roomwall.py, pynicotine/gtkgui/ui/chatrooms.ui, pynicotine/gtkgui/ui/mainwindow.ui, pynicotine/gtkgui/ui/roomwall.ui, pynicotine/pynicotine.py
From what I've personally experienced and noticed, the ticker feature always seems to cause confusion among new users. I've repurposed tickers as a room wall feature, like SoulseekQt did some years ago.
=> Add room wall feature

pynicotine/gtkgui/frame.py, pynicotine/gtkgui/ui/nowplaying.ui
Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/485
=> Remove close button from about dialog

pynicotine/shares.py
Prevent creating lists for every incoming search request, even if there are no matches. Reduces memory and CPU usage.
=> Minor optimizations to search request processing

pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/transferlist.py, pynicotine/gtkgui/uploads.py
Necessary changes after selected_transfers was turned into a set.
=> Make open directory feature functional again

pynicotine/gtkgui/frame.py, pynicotine/gtkgui/settingswindow.py
These are the final ones for 2.1.0. There are still a few in the metadata and search dialogs, but these dialogs will be replaced in future versions anyway.
=> Replace a few deprecated elements

pynicotine/gtkgui/ui/mainwindow.ui, pynicotine/gtkgui/ui/userinfo.ui
We don't live in 2007 anymore.
=> Remove unnecessary borders from some boxes

pynicotine/shares.py, pynicotine/slskmessages.py, pynicotine/utils.py
Causes issues with existing shares.
Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/527
Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/529
=> Revert "Remove variable bitrate information"

pynicotine/gtkgui/search.py
When ignoring a search tab/query, we can't remove it from the searches dictionary, since the dictionary is necessary for functionality such as saving column widths and showing a close item when right-clicking a tab. Instead, we add a flag to dict items that determines if a search query should be ignored or not, and remove searches from the dictionary only when closing tabs.
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/481
=> Proper handling of ignored search tabs

pynicotine/gtkgui/utils.py
Fixes the stacktrace in https://github.com/Nicotine-Plus/nicotine-plus/issues/536
=> Don't add log items while shutting down

pynicotine/shares.py
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/535
@zniavre You may have to remove your shares db and rescan.
=> Make necessary conversion from bool to int

pynicotine/config.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/ui/settings/colours.ui, pynicotine/pynicotine.py, pynicotine/slskproto.py
Addresses a few performance concerns I noticed when profiling with py-spy. Removes the functionality that turns search results of offline users red, since it's quite complex for little gain.
Should also reduce memory usage a tad, since we're copying less lists.
=> Several performance improvements 

pynicotine/slskproto.py
Avoid callbacks to the UI too often.
=> Add cooldown to connection count updater

pynicotine/slskproto.py
Not sure if there are any consequences associated with this change yet, but it seems to reduce the number of stale connections staying around for too long, especially when searching for popular terms.
=> Close stale connections more frequently

pynicotine/slskmessages.py
Fixes regression in https://github.com/Nicotine-Plus/nicotine-plus/pull/539
Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/545
=> Use unsigned integers when necessary

NEWS.md, pynicotine/transfers.py
Otherwise your speed is reported as 0 B/s.
=> Send upload speed to server before resetting it

pynicotine/transfers.py
Update the speed we send with search results regularly.
=> Update locally saved upload speed more often

pynicotine/utils.py
https://forum.manjaro.org/t/getting-soulseek-to-work/690/5
=> Don't crash if locale is invalid

pynicotine/gtkgui/ui/mainwindow.ui
Show text for progress bars
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/559
=> Reduce status bar height

pynicotine/gtkgui/frame.py
Otherwise it will be placed behind the main window.
=> Show fast configure dialog at a later stage

pynicotine/gtkgui/frame.py, pynicotine/pynicotine.py, pynicotine/transfers.py
Doesn't seem like it's used for anything.
=> Avoid creating unnecessary list when downloading folder

pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/uploads.py
Also some minor changes to to make compatibility with transfer grouping better.
=> Bring transfer popup item ids up to date

pynicotine/gtkgui/roomwall.py
=> Show newest room wall messages at the top

pynicotine/pynicotine.py
There shouldn't be any need for this.
=> Remove one second delay before connecting to server

pynicotine/slskproto.py
A few empty lines never hurt anyone...
=> slskproto.py: improve readability

pynicotine/transfers.py
Fix for regression in https://github.com/Nicotine-Plus/nicotine-plus/pull/554
=> Don't download aborted transfers

pynicotine/gtkgui/frame.py, pynicotine/gtkgui/nowplaying.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/ui/mainwindow.ui, pynicotine/gtkgui/utils.py
Reorganization of the frame.py code to something that isn't completely out of order, and a general cleanup of unneeded code.
=> frame.py: general cleanup

pynicotine/gtkgui/search.py
If grouping was enabled for search results, and you selected a file row in the results, a folder download request would send out an empty string as the folder name, since the folder name cell is empty for file rows.
Instead, we add a fullpath to both folder and file rows, and extract the folder path from the fullpath when necessary.
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/574
=>  Fix issue with empty folder name when requesting files from user

pynicotine/gtkgui/transferlist.py, pynicotine/slskproto.py, pynicotine/transfers.py
Continuation of https://github.com/Nicotine-Plus/nicotine-plus/pull/596 with optimizations at the networking thread level to avoid looping through the downloads list in transfers.py too often.
=> Add UI callback cooldown for file downloads

pynicotine/gtkgui/frame.py
In rare cases I've noticed that all tabs were hidden when starting Nicotine+. It seems like OnPageRemoved is called at shutdown, which sets the tab visibility to false. This is rarely written to the actual config file though, since the write process is started before the visibility is changed, but it can happen.
=> Don't set tab visibility on shutdown

pynicotine/gtkgui/transferlist.py, pynicotine/slskproto.py, pynicotine/transfers.py
#600, but for file uploads this time.
=> Add UI callback cooldown for file uploads

pynicotine/slskproto.py
https://github.com/Nicotine-Plus/nicotine-plus/pull/543 revisited. As long as we don't modify CONNECTION_MAX_IDLE, there are no upload issues as seen in https://github.com/Nicotine-Plus/nicotine-plus/pull/568.
=> Reduce connection timeout value for conns in progress

NEWS.md, pynicotine/gtkgui/transferlist.py
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/609
=> Also increment iter if a transfer is filtered

files/windows/dependencies.sh
Seems like an old issue: https://stackoverflow.com/questions/53239095/install-pyinstaller-on-msys2-mingw
No idea why it has resurfaced again...
=> Fix Windows build (again)

doc/SLSKPROTOCOL.md, pynicotine/slskmessages.py, pynicotine/slskproto.py, test/unit/test_login.py
Alternative solution to the previous ping system, which never worked as intended for me at least.
=> Use TCP keepalive to monitor server connection

pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/uploads.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/utils.py
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/437
=> Unselect treeview items when clicking on empty space

NEWS.md, TRANSLATORS.md, pynicotine/config.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/ui/settings/search.ui, pynicotine/shares.py
The limit in SoulseekQt seems to be 3 characters, so we'll use that as the default value too.
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/551
=> Add configurable min character limit for incoming searches

pynicotine/gtkgui/frame.py
Regression in https://github.com/Nicotine-Plus/nicotine-plus/pull/598
=> Restore user info and user browse tab hilite

pynicotine/config.py, pynicotine/shares.py, pynicotine/slskmessages.py
- Rewrite of the search result processing code to reduce resource usage and make the code clearer
- Remove a few unnecessary hidden folder checks when scanning files
=> Revise processing of search requests

pynicotine/shares.py
Since we don't need the resulting list, use an iterator instead.
=> Use islice to limit number of sent search results

pynicotine/slskmessages.py, pynicotine/slskproto.py, pynicotine/transfers.py, test/unit/mock_socket.py
- Add cooldown to networking thread loop to reduce cpu usage
- Fix incorrect download speed limit
- Remove break statements to allow every transfer to be updated if a user disappears
- Various minor optimizations/style changes
=> Reduce networking thread CPU usage and other optimizations

pynicotine/plugins/multipaste/__init__.py, pynicotine/pluginsystem.py
- Remove usage of eval
- Remove leftovers
- Remove GUI queue, since plugins run in the main thread
- Import traceback module only when necessary
=> Plugin system cleanup

pynicotine/gtkgui/fastconfigure.py
I'm slightly surprised this wasn't done before.
=> Scan shares after completing fast configure

pynicotine/slskproto.py
Due to a minor error in the input processing code, we would hit a "ValueError: Invalid file descriptor: -1" over and over, ending the loop prematurely and causing large CPU usage due to a lack of cooldowns in the exception handling code.
=> Fix issue regarding 100% CPU usage in networking code

pynicotine/config.py, pynicotine/gtkgui/userbrowse.py, pynicotine/slskmessages.py
https://github.com/Nicotine-Plus/nicotine-plus/blob/2.0.1/pynicotine/slskmessages.py#L1847
=> Handle a few more exceptions

NEWS.md, README.md, debian/changelog, files/windows/nicotine.nsi, pynicotine/utils.py
Opening this PR in preparation for 2.1.0, which is right around the corner now.
Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/504
=> Version 2.1.0

pynicotine/gtkgui/checklatest.py, pynicotine/utils.py, test/unit/test_version.py
Partial fix for https://github.com/Nicotine-Plus/nicotine-plus/issues/659
=> Handle dev versions in version checker

pynicotine/config.py, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/ui/settings/colours.ui
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/661
=> Add dark mode setting

pynicotine/gtkgui/ui/search.ui
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/669
=> Reduce filter entry min width

pynicotine/gtkgui/chatrooms.py
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/672
For clarification, public room in this case means https://github.com/Nicotine-Plus/nicotine-plus/blob/master/doc/SLSKPROTOCOL.md#server-code-150.
=> Allow auto-joining public room

pynicotine/slskproto.py
The transfer speed limit calculations contained a bunch of errors that have been corrected.
- The download speed limiter was supposed to reduce the speeds of individual downloads to stay under the total limit, if two or more downloads existed. This didn't work, because we checked_isDownload on the keys in the conns dictionary instead of the values.
- The upload speed limiter was incorrect, and started cutting the upload speed limit in half even when we only uploaded a single file.
=> Make transfer speed limits more accurate

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/ui/chatrooms.ui, pynicotine/gtkgui/ui/mainwindow.ui, pynicotine/gtkgui/ui/privatechat.ui, pynicotine/gtkgui/utils.py
Replaces the old text search dialog with a GtkSearchBar. https://developer.gnome.org/gtk3/stable/GtkSearchBar.html
=> Replace search dialog feature with search bar

nicotine, pynicotine/config.py, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/ui/settings/log.ui, pynicotine/gtkgui/utils.py, pynicotine/logfacility.py, pynicotine/pynicotine.py, pynicotine/utils.py
Adds an option to log the debug window contents to file. Also contains a bunch of consistency improvements for logging.
Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/387
I won't implement the search/filter part of the issue due to constraints. Third party tools can be used to properly inspect the log files instead.
=> Add option to log debug messages to file

pynicotine/gtkgui/frame.py, pynicotine/gtkgui/utils.py
We want to use our own link handler.
=> Override link handler in about dialog

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/ui/chatrooms.ui, pynicotine/gtkgui/ui/mainwindow.ui, pynicotine/gtkgui/ui/roomwall.ui, pynicotine/gtkgui/utils.py
Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/659
can_focus needs to be true for keyboard shortcuts to work.
=> Fix Ctrl-C in text views and simplify search bar code

NEWS.md, README.md, debian/changelog, files/appdata/org.nicotine_plus.Nicotine.appdata.xml, files/windows/nicotine.nsi, pynicotine/utils.py
2.1.1 needs some final testing, but is essentially ready.
=> Version 2.1.1

pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/notifications.py, pynicotine/gtkgui/transferlist.py, pynicotine/gtkgui/tray.py, pynicotine/transfers.py
AppIndicators don't support tooltips, move the status text to separate menu items instead.
=> Tray: add download/upload status and shortcuts

pynicotine/config.py, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/notifications.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/transferlist.py, pynicotine/gtkgui/uploads.py, pynicotine/gtkgui/userlist.py, pynicotine/gtkgui/utils.py, pynicotine/pluginsystem.py, pynicotine/pynicotine.py, pynicotine/transfers.py, pynicotine/upnp.py
Some work to untie the core from the GUI slightly more.
=> Reduce UI-related code in backend

nicotine, pynicotine/config.py, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/notifications.py, pynicotine/gtkgui/nowplaying.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/tray.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userinfo.py, pynicotine/gtkgui/userlist.py, pynicotine/gtkgui/utils.py, pynicotine/gtkgui/wishlist.py, pynicotine/logfacility.py, pynicotine/pluginsystem.py, pynicotine/pynicotine.py, pynicotine/shares.py, pynicotine/slskmessages.py, pynicotine/slskproto.py, pynicotine/transfers.py, pynicotine/upnp.py, test/unit/shares/test_shares.py
Logging across the whole program is now more consistent.
=> Improvements to logging system

pynicotine/config.py, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/nowplaying.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/utils.py, pynicotine/plugins/anti_shout/PLUGININFO, pynicotine/plugins/leech_detector/PLUGININFO, pynicotine/plugins/memory_debugger/PLUGININFO, pynicotine/plugins/multipaste/PLUGININFO, pynicotine/plugins/plugindebugger/PLUGININFO, pynicotine/plugins/reddit/PLUGININFO, pynicotine/plugins/spamfilter/PLUGININFO, pynicotine/plugins/testreplier/PLUGININFO, pynicotine/pluginsystem.py, pynicotine/pynicotine.py, pynicotine/shares.py, pynicotine/slskmessages.py, pynicotine/slskproto.py, pynicotine/transfers.py, test/unit/test_version.py
A few corrections by the Autopep8 tool, and a minor fix for a regression from the previous PR.
=> Autopep8 corrections

pynicotine/gtkgui/userbrowse.py
Should've been removed in https://github.com/Nicotine-Plus/nicotine-plus/pull/703
=> userbrowse.py: remove reference to old function

pynicotine/plugins/reddit/PLUGININFO, pynicotine/plugins/reddit/__init__.py
Requiring an external dependency to use a simple plugin like this is overkill.
=> Reddit plugin: drop feedparser dependency

pynicotine/shares.py
Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/730
=> Only scan metadata of files larger than 128 bytes

NEWS.md, README.md, debian/changelog, files/appdata/org.nicotine_plus.Nicotine.appdata.xml, files/windows/nicotine.nsi, po/da.po, po/de.po, po/es.po, po/eu.po, po/fi.po, po/fr.po, po/hu.po, po/it.po, po/lt.po, po/nicotine.pot, po/nl.po, po/pl.po, po/pt_BR.po, po/sk.po, po/sv.po, pynicotine/utils.py, test/unit/shares/test_shares.py
I think we're ready for a new release.
=> Version 2.1.2

test/unit/test_slskmessages.py
We should cover more messages when we have time, but it's enough to get a general idea if our data types work or not.
Taken from https://github.com/lene/nicotine-plus/pull/42
Co-authored-by: droserasprout <droserasprout@tuta.io>
=> Initial tests for slskmessages

debian/control, pynicotine/config.py, pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/uploads.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/utils.py
Cleaner solution than executing the xdg-open command.
=> Launch file manager and audio player without external deps

pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/ui/settings/search.ui
Perhaps I should remove it from the GUI too...
=> Remove option to stop responding to searches for a certain time (part 2)

po/it.po
As in title. There are some general improvements above all the translated strings and every single line is localized
=> Improvements on italian localization

po/it.po
=> Some refinements on Italian localization

TRANSLATORS.md, pynicotine/gtkgui/ui/about/about.ui
Thank you for your kidness and your fast prompt reactions. Glad to see this project still alive and modernized.
=> Add some credits for Italian localization

po/it.po
Some typo fixes and more coherent vocabulary
=> Improve overall Italian localization

doc/SLSKPROTOCOL.md, pynicotine/gtkgui/search.py, pynicotine/pynicotine.py, pynicotine/slskmessages.py, pynicotine/slskproto.py
Adding this code in case the feature starts working again in the future, and we decide to implement it in the UI.
=> Add protocol code for related searches

doc/SLSKPROTOCOL.md, pynicotine/slskmessages.py, pynicotine/slskproto.py
Some minor corrections to the protocol documentation and documentation of a few deprecated server codes.
=> Minor documentation corrections

pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/ui/buddylist.ui, pynicotine/gtkgui/ui/chatrooms.ui, pynicotine/gtkgui/ui/interests.ui, pynicotine/gtkgui/ui/mainwindow.ui, pynicotine/gtkgui/ui/privatechat.ui, pynicotine/gtkgui/ui/roomlist.ui, pynicotine/gtkgui/ui/search.ui, pynicotine/gtkgui/ui/settings/downloads.ui, pynicotine/gtkgui/ui/settings/shares.ui, pynicotine/gtkgui/ui/userbrowse.ui, pynicotine/gtkgui/utils.py, pynicotine/slskmessages.py
- Add icons for main tabs to differentiate them more
- More logical bottom bar button grouping on transfer pages
- Remove unnecessary spacing and borders from child notebooks
- Improved spacing
- Automatically grab focus of search field
=> UI refresh

pynicotine/gtkgui/settingswindow.py
Not a pretty solution, but it works.
=> Add workaround for clearing selected theme folder

pynicotine/transfers.py
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/784 (hopefully)
=> Be less aggressive about cancelling uploads

pynicotine/gtkgui/interests.py, pynicotine/slskmessages.py
Looks better to position the narrow rating column before the item column.
=> Change order of interest columns

files/icons/hilite/hilite3.svg, pynicotine/gtkgui/imagedata.py
The old one is a bit too hard to see in certain conditions.
=> Use slightly wider stroke for hilite icon

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/interests.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/transferlist.py, pynicotine/gtkgui/userbrowse.py, pynicotine/pynicotine.py, pynicotine/shares.py, pynicotine/slskmessages.py, pynicotine/slskproto.py, pynicotine/transfers.py
- Add missing break statements to loops
- Use generator instead of list for buddy list checks
- Remove dead and redundant geo block code
- Remove redundant GetUserStatus request for users. AddUser is the only one we need.
- Optimize common upload queue checks
=> Performance improvements for uploads

debian/changelog, files/windows/nicotine.nsi, pynicotine/gtkgui/utils.py, pynicotine/pynicotine.py, pynicotine/utils.py
Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/791
=> Remove callback for unknown peer message

pynicotine/pynicotine.py
Proper fix for https://github.com/Nicotine-Plus/nicotine-plus/issues/791
=> Add empty callback handler for unknown peer message

nicotine, pynicotine/config.py, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/interests.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/tray.py, pynicotine/gtkgui/userinfo.py, pynicotine/gtkgui/userlist.py, pynicotine/gtkgui/utils.py, pynicotine/nowplaying.py, pynicotine/pluginsystem.py, pynicotine/pynicotine.py, pynicotine/shares.py, pynicotine/slskmessages.py, pynicotine/transfers.py, pynicotine/upnp.py, pynicotine/utils.py
Various tweaks to improve application startup times.
=> Improve startup time

pynicotine/gtkgui/tray.py
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/767
=> Improve tray icon detection

pynicotine/gtkgui/frame.py
Should fix issues where the menu bar isn't visible on some systems.
=> Load menu bar earlier

pynicotine/shares.py
- Don't skip file scanning entirely if pytaglib fails
- Actually show stacktrace when expected
=> Improved exception handling when scanning shares

pynicotine/gtkgui/ui/userbrowse.ui, pynicotine/gtkgui/ui/userinfo.ui, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userinfo.py, pynicotine/gtkgui/utils.py, pynicotine/pynicotine.py
Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/766
=> Show info bar if connection to peer fails

pynicotine/plugins/now_playing_sender/PLUGININFO, pynicotine/plugins/now_playing_sender/__init__.py
This was requested in the IRC channel, and I thought it would be a good opportunity for me to get used to the plugin system.
The plugin currently contains an issue where the song is sent twice, which I haven't been able to resolve yet, but otherwise it works fine.
=> Add 'Now Playing Sender' plugin

pynicotine/gtkgui/search.py, pynicotine/plugins/now_playing_search/PLUGININFO, pynicotine/plugins/now_playing_search/__init__.py, pynicotine/plugins/plugindebugger/__init__.py, pynicotine/pluginsystem.py
Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/664
=> Add 'Now Playing Search' plugin

pynicotine/shares.py
Adding this to make it easier to debug https://github.com/Nicotine-Plus/nicotine-plus/issues/829.
=> Log exception when failing to open shares

nicotine
Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/829
=> Inform user about missing semidbm module

pynicotine/pynicotine.py
Some clients never attempt a direct connection to us first, always asking us to connect to them instead (indirect connection). Nicotine+ assumes these users already attempted to connect to us directly, and thus gives up connecting completely, leading to "Cannot connect" errors for some uploads.
Make sure we always ask others to connect to us at least once too (do this for file transfers only for now, since this seems to be the most affected area).
=> Always attempt an indirect connection at least once

po/it.po
=> Update Italian localization

.github/workflows/tests.yml, README.md, doc/DEPENDENCIES.md, pynicotine/gtkgui/tray.py, pynicotine/gtkgui/ui/userbrowse.ui, pynicotine/gtkgui/ui/userinfo.ui, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userinfo.py, pynicotine/gtkgui/utils.py, pynicotine/nowplaying.py, pynicotine/plugins/reddit/__init__.py, pynicotine/shares.py, pynicotine/upnp/ssdp.py, pynicotine/utils.py
- Run tests on Python 3.9
- Update dependency list with separate section for test dependencies
- Fix a few warnings reported when running `python -W always nicotine`
- Fix a small GTK 3.18 compatibility issue with the info bar
=> Preparations for a new release

README.md
Replaces the old image variant in https://github.com/Nicotine-Plus/nicotine-plus/pull/856
Closes https://github.com/Nicotine-Plus/nicotine-plus/pull/856
=> Add Nicotine name origin to readme

pynicotine/config.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/ui/settings/icons.ui
Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/864
=> Add configuration option to minimize to tray on startup

NEWS.md, pynicotine/config.py, pynicotine/gtkgui/frame.py, pynicotine/utils.py
Fix for errors such as "'ascii' codec can't decode byte 0xe8 in position 41: ordinal not in range(128)".
=> Improved compatibility for loading saved shares from older version

pynicotine/gtkgui/frame.py
We don't want to process any callbacks after the program has mostly shut down already, otherwise we will stumble upon warnings about missing elements and closed dbs depending on the timing.
=> Reject all UI callbacks when shutting down

pynicotine/pynicotine.py, pynicotine/transfers.py
This will make it easier for me to debug issues, ease the work for translators, and prevent a lot of disk read.
=> Stop translating debug messages

NEWS.md, README.md, debian/changelog, files/org.nicotine_plus.Nicotine.metainfo.xml, files/windows/nicotine.nsi, pynicotine/utils.py
@kiplingw If no serious bugs arise, and you're fine with a new release, I'm tagging 2.2.0 stable on Friday.
=> Version 2.2.0

pynicotine/transfers.py
=> Handle a few cases of mojibake file names for queued uploads

pynicotine/config.py, pynicotine/pynicotine.py, pynicotine/shares.py, pynicotine/transfers.py
Several changes to config.py to clean it up and make it less error-prone. Hopefully also helps with the situation where the config file sometimes disappears after a hard shutdown.
=> Clean up config-related code

NEWS.md, README.md, debian/changelog, files/org.nicotine_plus.Nicotine.metainfo.xml, files/windows/nicotine.nsi, pynicotine/utils.py
I'm releasing 2.2.1 later today, as there are some important fixes that need to get out there. Afterwards, I'll probably focus on one last bug fix release in the 2.2.X series.
=> Version 2.2.1

NEWS.md, README.md, debian/changelog, files/org.nicotine_plus.Nicotine.metainfo.xml, files/windows/nicotine.nsi, pynicotine/utils.py
Wish I had caught this issue before the 2.2.1 release, but what can you do...
=> Version 2.2.2

doc/SLSKPROTOCOL.md, pynicotine/slskmessages.py, pynicotine/slskproto.py
Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/876
=> Use correct server code for CantCreateRoom message

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/dialogs.py, pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/ui/mainwindow.ui, pynicotine/gtkgui/ui/search.ui, pynicotine/gtkgui/ui/settings/censor.ui, pynicotine/gtkgui/ui/settings/colours.ui, pynicotine/gtkgui/ui/settings/downloads.ui, pynicotine/gtkgui/ui/settings/events.ui, pynicotine/gtkgui/ui/settings/fonts.ui, pynicotine/gtkgui/ui/settings/nowplaying.ui, pynicotine/gtkgui/ui/settings/tts.ui, pynicotine/gtkgui/ui/settings/urlcatch.ui, pynicotine/gtkgui/userlist.py, pynicotine/gtkgui/utils.py, pynicotine/plugins/now_playing_search/__init__.py, pynicotine/plugins/now_playing_sender/__init__.py, pynicotine/pynicotine.py
=> Replace final instances of GtkComboBox with GtkComboBoxText

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/interests.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/transferlist.py, pynicotine/gtkgui/ui/buddylist.ui, pynicotine/gtkgui/ui/chatrooms.ui, pynicotine/gtkgui/ui/interests.ui, pynicotine/gtkgui/ui/mainwindow.ui, pynicotine/gtkgui/ui/privatechat.ui, pynicotine/gtkgui/ui/search.ui, pynicotine/gtkgui/ui/userbrowse.ui, pynicotine/gtkgui/ui/userinfo.ui, pynicotine/gtkgui/uploads.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userinfo.py, pynicotine/gtkgui/userlist.py, pynicotine/gtkgui/utils.py
- Add support for opening context menus with the keyboard (menu key or Shift+F10) and by long pressing on a touch screen.
- Several code cleanups and consistency improvements
=> Add support for opening context menus with keyboard and touch screen

pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/ui/chatrooms.ui, pynicotine/gtkgui/ui/settings/autoreplace.ui, pynicotine/gtkgui/ui/settings/away.ui, pynicotine/gtkgui/ui/settings/ban.ui, pynicotine/gtkgui/ui/settings/censor.ui, pynicotine/gtkgui/ui/settings/completion.ui, pynicotine/gtkgui/ui/settings/downloads.ui, pynicotine/gtkgui/ui/settings/events.ui, pynicotine/gtkgui/ui/settings/fontscolors.ui, pynicotine/gtkgui/ui/settings/geoblock.ui, pynicotine/gtkgui/ui/settings/icons.ui, pynicotine/gtkgui/ui/settings/ignore.ui, pynicotine/gtkgui/ui/settings/log.ui, pynicotine/gtkgui/ui/settings/notebook.ui, pynicotine/gtkgui/ui/settings/notifications.ui, pynicotine/gtkgui/ui/settings/nowplaying.ui, pynicotine/gtkgui/ui/settings/plugin.ui, pynicotine/gtkgui/ui/settings/search.ui, pynicotine/gtkgui/ui/settings/server.ui, pynicotine/gtkgui/ui/settings/tts.ui, pynicotine/gtkgui/ui/settings/uploads.ui, pynicotine/gtkgui/ui/settings/urlcatch.ui, pynicotine/gtkgui/ui/settings/userinfo.ui
New pull request, in place of https://github.com/Nicotine-Plus/nicotine-plus/pull/933.
=> Clean up Preferences' strings and related occurrences

pynicotine/config.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/ui/popovers/searchfilters.ui, pynicotine/gtkgui/ui/search.ui, pynicotine/gtkgui/ui/settings/search.ui
Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/677
Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/946
=> Add file type filter for search results

pynicotine/gtkgui/frame.py, pynicotine/gtkgui/ui/userinfo.ui, pynicotine/gtkgui/uploads.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userinfo.py, pynicotine/pynicotine.py, pynicotine/search.py, pynicotine/slskmessages.py, pynicotine/transfers.py
Rebased version of #960
Closes #956
=> Optimize file uploads

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/fastconfigure.py, pynicotine/gtkgui/fileproperties.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/interests.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/roomlist.py, pynicotine/gtkgui/roomwall.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/statistics.py, pynicotine/gtkgui/transferlist.py, pynicotine/gtkgui/tray.py, pynicotine/gtkgui/ui/interests.ui, pynicotine/gtkgui/ui/mainwindow.ui, pynicotine/gtkgui/ui/userinfo.ui, pynicotine/gtkgui/uploads.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userinfo.py, pynicotine/gtkgui/userlist.py, pynicotine/gtkgui/utils.py, pynicotine/gtkgui/wishlist.py
This is an unnoticeable change on the user's end, but a rather painful (but necessary) context menu rewrite for future GTK4 compatibility. This should be the last tedious blocker of a potential GTK4 port in a few years. :)
Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/1045
=> Use Gio.Menu for context menus

NEWS.md, nicotine, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/fastconfigure.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/interests.py, pynicotine/gtkgui/notifications.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/roomlist.py, pynicotine/gtkgui/roomwall.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/statistics.py, pynicotine/gtkgui/transferlist.py, pynicotine/gtkgui/uploads.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userinfo.py, pynicotine/gtkgui/userlist.py, pynicotine/gtkgui/widgets/popupmenu.py, pynicotine/gtkgui/widgets/trayicon.py, pynicotine/gtkgui/wishlist.py, pynicotine/logfacility.py, pynicotine/plugins/now_playing_sender/__init__.py, pynicotine/pynicotine.py, pynicotine/shares.py, pynicotine/transfers.py
Removes the dependency on NicotineFrame and NetworkEventProcessor to access config properties.
=> Decouple the config from NicotineFrame and NetworkEventProcessor

packaging/macos/dependencies-packaging.sh, packaging/windows/dependencies-packaging.sh
PyInstaller 4.3 was released three days ago.
=> Pin stable PyInstaller 4.3 version

NEWS.md, README.md, debian/changelog, doc/DEVELOPING.md, files/org.nicotine_plus.Nicotine.metainfo.xml.in, packaging/windows/nicotine.nsi, pynicotine/utils.py
Closes #1040 
Closes #1329 
Closes #1338
=> Version 3.0.5

NEWS.md, README.md, debian/changelog, files/org.nicotine_plus.Nicotine.metainfo.xml.in, packaging/windows/nicotine.nsi, pynicotine/utils.py
Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/1361
=> Version 3.0.6

packaging/windows/dependencies-packaging.sh, packaging/windows/nicotine.spec, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/notifications.py, pynicotine/gtkgui/widgets/trayicon.py
Thanks to @Inso-m-niaC!
This PR implements notification bubbles linked to our tray icon on Windows.
Fixes #1354
=> Add custom implementation for Windows notifications (@Inso-m-niaC)

pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/transferlist.py, pynicotine/gtkgui/ui/downloads.ui, pynicotine/gtkgui/ui/uploads.ui, pynicotine/gtkgui/uploads.py
=> Add dropdown menu for clearing transfer groups

AUTHORS.md
Since almost a year has passed now, it's time to update the list of active contributors.
@lene Thanks again for your hard work on the Python 3 port! You're always welcome back if you ever feel like working on Nicotine+ again. :)
=> Update list of active contributors

pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/ui/settings/shares.ui, pynicotine/gtkgui/widgets/treeview.py
Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/991
=> Add option to change buddy state of shared folder

README.md, packaging/windows/dependencies-packaging.sh
=> Downgrade PyInstaller to reduce number of false positives

pynicotine/config.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/ui/settings/network.ui, pynicotine/pynicotine.py, pynicotine/slskproto.py, test/unit/config/config, test/unit/protocol/test_slskproto.py
Implements support for Linux and macOS.
#871
=> Add option to specify a network interface

NEWS.md, README.md, data/org.nicotine_plus.Nicotine.metainfo.xml.in, debian/changelog, pynicotine/config.py
Letting this PR sit for a few days while I'm away.
=> Version 3.1.0

pynicotine/plugins/youtube_info/__init__.py
https://regex101.com/r/Jh91Bb/1
=> youtube_info: Only match URLs containing a video id

pynicotine/gtkgui/frame.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/transferlist.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/utils.py, pynicotine/gtkgui/widgets/popupmenu.py, pynicotine/gtkgui/widgets/textentry.py, pynicotine/gtkgui/widgets/treeview.py
This PR makes it easier to create new accelerators, and splits callbacks into separate functions.
=> Rework code related to keyboard accelerators

pynicotine/gtkgui/ui/settings/userinterface.ui
Also remove a dot, it's the only tooltip with a dot.
=> Actually, this is what really happens.

AUTHORS.md, pynicotine/gtkgui/ui/dialogs/about.ui
```
slook
- Tester
- Accessibility improvements
```
=> Add contributor (slook)

doc/DOWNLOADS.md
- Fixed: Broken href link TESTING.html -> TESTING.md
=> DOWNLOADS.md: Fix broken link for macOS Monterey

pynicotine/gtkgui/notifications.py
- Fixed: Bug caused by https://github.com/nicotine-plus/nicotine-plus/commit/33af2a6ef24da7a05c979ba8d32438fafcaa9030
=> notifications.py: Fix Critical Error image -> icon

pynicotine/gtkgui/transferlist.py, pynicotine/transfers.py
- Added: Bright tab highlight when a file is finished downloading
=> Finished download tab notification highlight

doc/TRANSLATIONS.md
After a discussion on IRC, we decided it's a good idea to explain the underscores a bit.
=> Explain underscores in translation strings.

pynicotine/plugins/plugin_debugger/PLUGININFO, pynicotine/plugins/plugin_debugger/__init__.py
+ Added: `search_request_notification`
+ Added: `distrib_search_notification` (verbose: no logging)
+ Added: `user_status_notification`
+ Changed: Logged function names from deprecated CamelCase to new snake_case notation
+ Changed: Arguments=Values in parens() to match Python syntax, because this makes it easier to copy from the log for pasting into code
=> Plugin Debugger: Add missing notifications (search_request; distrib_search; user_status)

doc/TRANSLATIONS.md
- discussing suggestions to the original translation
- discussing with other translators on conflicting opinions.
=> add tips for translators

debian/control, debian/rules, debian/tests/control
@SwampRabbit Are these changes enough?
=> Debian: use python3-pytest-xvfb plugin for tests

pynicotine/gtkgui/dialogs/preferences.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/ui/privatechat.ui, pynicotine/privatechat.py
+ Added: Text-to-Speech toggle button in Private Chat, functions the same as Public Chats
=> Private Chat: Add Text-to-Speech toggle button

pynicotine/gtkgui/chatrooms.py
+ Changed: Nothing, the function output is exactly the same but is achieved slightly more gracefully
=> Chat Rooms: Cleanup line assembly

pynicotine/gtkgui/chatrooms.py
Optimized the order to reduce lag, it appears significantly faster to update the UI as soon as possible
=> Chat Rooms: Write log file after append line

pynicotine/gtkgui/chatrooms.py
Fixes #1790
Added: Check that a username mention is not a substring, and don't do find() in text unless it contains a possible mention
=> Chat Rooms: Simple check username whole word

NEWS.md
+ Added: New section "Version 3.2.2 (Release Candidate 2)"
This edit has all the closed issues which do not relate to master. For those issues see PR #1956 (master).
> Some of the issues are questions and environment-related problems, those should probably be removed too.
=> NEWS.md: Update release notes for 3.2.2

doc/DOWNLOADS.md
Closes #1969
+ Added: Link to instructions for macOS Monterey 12 'Open a Mac app from an unidentified developer'
=> DOWNLOADS.md: macOS post-installation instructions

pynicotine/gtkgui/userlist.py
=> gui/userlist.py: add user note edit Cancel not OK

doc/DEPENDENCIES.md
Added links to aid navigation on the website.
=> DEPENDENCIES.md: add links to stable installers

doc/TESTING.md
Correction for the version of the file in the 3.2.x branch.
=> TESTING.md: "after every commit to the "master" -> "3.2.x" branch"

pynicotine/transfers.py, pynicotine/utils.py, test/unit/transfers/test_transfers.py
@AtticFinder65536 Does this solution work fine on your end?
=> transfers.py: limit incomplete file names to 255 bytes

pynicotine/gtkgui/search.py
+ Moved: Avoid doing string operations unless it is needed, this improves performance if filter is None or hasn't changed
+ Added: Tolerate spaces in pipe separated conditions (rather than just the first and last ones)
=> gui/search.py: on_refilter() optimize country

pynicotine/gtkgui/search.py
Since the filter checks are performed on each row, it makes sense to do more work when creating the filters.
=> search.py: various optimizations for search filters

NEWS.md, README.md, data/org.nicotine_plus.Nicotine.appdata.xml.in, debian/changelog, pynicotine/config.py
=> Version 3.2.3

NEWS.md, README.md, data/org.nicotine_plus.Nicotine.appdata.xml.in, debian/changelog, pynicotine/config.py
=> Version 3.2.4

pynicotine/gtkgui/dialogs/preferences.py
If anyone can provide an even better version, I wanna hear it. :-)
=> Better wording for the Music Player

pynicotine/gtkgui/dialogs/preferences.py
Say the same thing in simpler English.
=> Avoid overly ingenious language constructions.

pynicotine/pynicotine.py
Clarify what kind of privileges we're referring to.
=> pynicotine.py: privileges -> Soulseek privileges

pynicotine/gtkgui/frame.py
+ Added: 1 second cooldown for Ctrl+H keyboard shortcut to prevent server ban
- Moved: Action declaration code within set_up_actions() since Away is not an item in the File menu, also grouped Away Mode functions as appropriate.
Alternative to #2207
=> frame.py: cooldown for away shortcut key to prevent server ban

pynicotine/cli/application.py, pynicotine/gtkgui/frame.py, pynicotine/shares.py
=> Abort rescan if shares are unavailable

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/popovers/chathistory.py, pynicotine/gtkgui/ui/buddylist.ui, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userlist.py, pynicotine/gtkgui/widgets/popupmenu.py, pynicotine/gtkgui/widgets/trayicon.py, pynicotine/gtkgui/widgets/treeview.py, pynicotine/networkfilter.py, pynicotine/plugins/leech_detector/__init__.py, pynicotine/pynicotine.py, pynicotine/search.py, pynicotine/shares.py, pynicotine/transfers.py, pynicotine/userlist.py, test/unit/transfers/test_get_upload_candidate.py
This work turned out to be more exhausting than expected. I would appreciate some quick testing to ensure I'm not doing something stupid like screwing up buddy lists.
=> Buddy list: move to core and port to TreeView class

pynicotine/gtkgui/search.py
Closes #2141
+ Changed: `<` and `>` is now mathmatically correct, i.e. less/more than instead of less/more or equal to
+ Added: `<=` and `>=` operators to be specified, also allow `==` and `!=` syntax
+ Fixed: Return match on exact match even if the filter isn't factorized (i.e. on Bitrate, raw Bytes, raw Seconds)
The operator library is supposed to be called directly, it is more efficient than using string matching for doing math operations.
This PR is a does not contain the potentially undesirable changes in #2238 , the nature of the filter seperation remains the same.
=> Result Filters: Enable every operator in digit conditions

pynicotine/gtkgui/widgets/textentry.py, pynicotine/headless/application.py, pynicotine/plugins/core_commands/__init__.py
+ Added: `/quit` command with `force` flag argument, now also available in headless CLI.
=> core_commands: quit command

pynicotine/gtkgui/widgets/textentry.py, pynicotine/plugins/core_commands/__init__.py
+ Moved: `/pm` command into core_commands plugin, no functional changes.
=> core_commands: pm command

pynicotine/plugins/core_commands/__init__.py, pynicotine/pluginsystem.py
+ Changed: Standardize internal local variable names to `command_interface`
=> pluginsystem.py: command_type -> command_interface

pynicotine/core.py, pynicotine/gtkgui/ui/dialogs/fastconfigure.ui
These two strings are more to the point.
=> declunkificationarry

pynicotine/gtkgui/widgets/textentry.py, pynicotine/plugins/core_commands/__init__.py
+ Moved: `/clear` command into core_commands plugin, don't accept any arguments.
=> core_commands: clear command

pynicotine/gtkgui/widgets/textentry.py, pynicotine/plugins/core_commands/__init__.py
+ Moved: /whois command into core_commands plugin
+ Added: Enable usage from chat rooms or other private chat windows with the `<user>` argument
=> core_commands: whois command

pynicotine/slskproto.py
+ Changed: Minor optimization, no functional change, use the existing local variable and only set it when needed.
=> slskproto.py: minor cleanup local num_sockets

pynicotine/slskproto.py
+ Changed: Avoid an unnecessary reference to a class variable
=> slskproto.py: loop count increment cleanup

pynicotine/gtkgui/widgets/textentry.py, pynicotine/plugins/core_commands/__init__.py, pynicotine/pluginsystem.py
- Removed: `/toggle` command (was undocumented)
+ Added: `/plugin` command with `toggle` and `info` sub-commands
+ Changed: toggle_plugin() function does update config with enabled plugins
=> core_commands: plugin command

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/transferlist.py, pynicotine/gtkgui/ui/userbrowse.ui, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userlist.py, pynicotine/gtkgui/widgets/theme.py, pynicotine/gtkgui/widgets/treeview.py, pynicotine/shares.py
I was curious how much effort it would take to implement this. Turns out it's quite straightforward, and doesn't seem to impact performance.
=> Implement file type column with icons

TRANSLATORS.md, pynicotine/gtkgui/dialogs/about.py
Congrats and much appreciated!
=> Add credit for hylau finishing the Chinese(simplified) translation.

pynicotine/gtkgui/application.py, pynicotine/gtkgui/dialogs/preferences.py, pynicotine/gtkgui/mainwindow.py, pynicotine/gtkgui/ui/mainwindow.ui, pynicotine/gtkgui/ui/userinfo.ui, pynicotine/gtkgui/userinfo.py
=> Add button to view personal profile

pynicotine/gtkgui/ui/userinfo.ui, pynicotine/gtkgui/userinfo.py
Also remove the option to manually zoom. We're many things, but not an image viewer...
=> userinfo.py: automatically resize user picture

doc/SLSKPROTOCOL.md, pynicotine/slskmessages.py, pynicotine/slskproto.py
=> Implement search request delivery to child peers

TRANSLATORS.md, pynicotine/gtkgui/dialogs/about.py
=> update translator credits

pynicotine/chatrooms.py, pynicotine/gtkgui/popovers/chatcommandhelp.py, pynicotine/plugins/core_commands/__init__.py, pynicotine/plugins/examplars/port_checker/__init__.py, pynicotine/pluginsystem.py, pynicotine/privatechat.py
=> Plugins: remove all instances of 'usage' term

pynicotine/chatrooms.py, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/ui/chatrooms.ui
This is a simpler alternative to the current "Auto-join room" toggle.
https://github.com/nicotine-plus/nicotine-plus/discussions/2519#discussioncomment-6026386
=> Always restore previously joined chatrooms on startup

pynicotine/gtkgui/chatrooms.py
+ Changed: Don't expose internal function, because it's not intended to be called by any external module.
=> gtkgui/chatrooms.py: minor cleanup _show_notification()

pynicotine/gtkgui/search.py
+ Added: Consider new wishlist result to be important.
=> gtkgui/search.py: implement wish tab is_important

pynicotine/chatrooms.py, pynicotine/core.py, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/interests.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/userinfo.py, pynicotine/gtkgui/userlist.py, pynicotine/gtkgui/widgets/textview.py, pynicotine/interests.py, pynicotine/userbrowse.py, pynicotine/userinfo.py, pynicotine/userlist.py
Cache user stats instead of re-requesting them.
=> Avoid redundant WatchUser requests to the server

pynicotine/gtkgui/privatechat.py
+ Added: Consider messages that are explicitly addressed to us by mentioned name, or are from buddies, to be important.
=> gtkgui/privatechat.py: implement buddy tab is_important

pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/mainwindow.py, pynicotine/gtkgui/transferlist.py, pynicotine/gtkgui/ui/downloads.ui, pynicotine/gtkgui/ui/uploads.ui, pynicotine/gtkgui/uploads.py, pynicotine/gtkgui/userinfo.py, pynicotine/gtkgui/userlist.py, pynicotine/gtkgui/widgets/treeview.py, pynicotine/transfers.py
Only the search view remains after this, which will be ported after https://github.com/nicotine-plus/nicotine-plus/pull/2464 is merged. We can then start using Gtk.ColumnView in GTK 4.
=> transferlist.py: port to new TreeView class

pynicotine/gtkgui/search.py, pynicotine/gtkgui/ui/search.ui, pynicotine/gtkgui/widgets/treeview.py
We can eventually look into creating a FileTreeView class or similar, but this will do until I've added support for Gtk.ColumnView.
Please keep the "Blocked" tag on treeview-related issues until we're using Gtk.ColumnView and know what's possible and what isn't.
=> search.py: port to new TreeView class

pynicotine/core.py, pynicotine/gtkgui/dialogs/preferences.py, pynicotine/slskmessages.py, pynicotine/slskproto.py
=> Support binding to network interfaces on Windows

pynicotine/gtkgui/dialogs/fastconfigure.py, pynicotine/gtkgui/dialogs/preferences.py, pynicotine/plugins/core_commands/__init__.py, pynicotine/shares.py
Replaces #2313
Should also contain most fixes from the previous PR, but it's possible I forgot to implement something. I tried to make the code as straightforward as possible, let me know if something is unclear or missing. @slook
=> core_commands: share and unshare commands

pynicotine/gtkgui/search.py, pynicotine/gtkgui/ui/search.ui, pynicotine/gtkgui/widgets/textentry.py
Should hopefully make item selection work well in both GTK 3 and 4.
=> Rework item selection in search filter dropdowns

pynicotine/chatrooms.py, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/mainwindow.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/ui/dialogs/shortcuts.ui, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userinfo.py, pynicotine/gtkgui/widgets/iconnotebook.py, pynicotine/plugins/core_commands/__init__.py, pynicotine/search.py
Adds Ctrl+Shift+T shortcut for reopening recently closed tabs.
Closes #1424 
I don't use this feature in other applications, so I'm not entirely sure if the behavior is correct, but feedback is welcome.
=> Support reopening closed tabs

pynicotine/gtkgui/application.py, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/dialogs/preferences.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/ui/settings/chats.ui, pynicotine/gtkgui/widgets/textentry.py
=> textentry.py: implement SpellChecker class

TRANSLATORS.md, po/LINGUAS, pynicotine/gtkgui/dialogs/about.py
This PR can be committed as soon as the Romanian translation is done. Just doing my homework.
=> Add Romanian Translation

pynicotine/gtkgui/ui/dialogs/fastconfigure.ui
I asked bard to reword this sentence. It looks more natural indeed.
=> reword open_port dialogue

pynicotine/gtkgui/dialogs/preferences.py, pynicotine/gtkgui/mainwindow.py, pynicotine/gtkgui/ui/settings/userinterface.ui, pynicotine/gtkgui/widgets/textentry.py
This is easier to maintain than radio menu items, and seems like an option that wouldn't be used frequently. We already include other position-related options in the Preferences dialog, might as well be consistent here.
=> Move buddy list position option to Preferences dialog

pynicotine/core.py, pynicotine/events.py, pynicotine/gtkgui/application.py, pynicotine/gtkgui/dialogs/about.py, pynicotine/gtkgui/mainwindow.py, pynicotine/gtkgui/ui/dialogs/about.ui, test/unit/test_version.py
=> Move version checker to About dialog

pynicotine/gtkgui/dialogs/preferences.py, pynicotine/gtkgui/ui/settings/uploads.ui
=> settings/uploads.ui: improve a few strings

pynicotine/gtkgui/ui/userbrowse.ui, pynicotine/gtkgui/ui/userinfo.ui, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userinfo.py, pynicotine/gtkgui/widgets/theme.py
These use less space and are only shown when needed.
=> userbrowse/info.ui: use overlay progress bars

pynicotine/gtkgui/search.py, pynicotine/gtkgui/transfers.py, pynicotine/gtkgui/ui/mainwindow.ui, pynicotine/gtkgui/ui/search.ui, pynicotine/gtkgui/ui/userbrowse.ui, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/widgets/theme.py
There are some issues left to sort out related to horizontal scrolling, but otherwise the path bar works fine.
The new design also allows for adding a filter bar later, similar to searches.
=> userbrowse.py: implement path bar

pynicotine/gtkgui/dialogs/pluginsettings.py, pynicotine/plugins/leech_detector/__init__.py
Closes #2105 
I opted for a list string option, since it exposes a convenient list of leechers that can be modified in the GUI.
=> Leech Detector: remember previous leechers

NEWS.md
Nit picks as per comments in https://github.com/nicotine-plus/nicotine-plus/commit/3b251cd19c5f3d14432fb3542a812c1f897ccaf0
=> Update NEWS.md with minor grammatical clarifications

pynicotine/gtkgui/transfers.py, pynicotine/gtkgui/widgets/treeview.py
Makes it easier to find transfers that were recently added.
=> gtkgui/transfers.py: select parent rows of new transfers

doc/DEVELOPING.md
- Added authoritative reference links to official Python docs, instead of "Search engines".
- Added command syntax help for running `nicotine` with `py-spy`.
=> DEVELOPING.md: specific guidance on profiling

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/dialogs/preferences.py, pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/interests.py, pynicotine/gtkgui/mainwindow.py, pynicotine/gtkgui/popovers/downloadspeeds.py, pynicotine/gtkgui/popovers/transferspeeds.py, pynicotine/gtkgui/popovers/uploadspeeds.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/ui/mainwindow.ui, pynicotine/gtkgui/ui/settings/userinterface.ui, pynicotine/gtkgui/ui/userlist.ui, pynicotine/gtkgui/uploads.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userinfo.py, pynicotine/gtkgui/userlist.py, pynicotine/gtkgui/widgets/accelerator.py, pynicotine/gtkgui/widgets/textview.py
It makes refactoring difficult, and is generally incompatible with static code analyzers.
=> Stop using getattr() when possible

pynicotine/plugins/leech_detector/__init__.py, pynicotine/userbrowse.py
Also remove redundant user stat request, since we're watching all queued users.
Fixes #1565
=> Leech Detector: add fallback check for users with no shares

pynicotine/chatrooms.py, pynicotine/config.py, pynicotine/events.py, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/ui/privatechat.ui, pynicotine/gtkgui/widgets/textview.py, pynicotine/privatechat.py, pynicotine/slskmessages.py, pynicotine/tests/unit/protocol/test_slskmessages.py, pynicotine/utils.py
Still needs a bit more cleanup. This was way more tedious than I expected.
=> Move chat logging to core

TRANSLATORS.md, pynicotine/gtkgui/dialogs/about.py
https://hosted.weblate.org/projects/nicotine-plus/nicotine-plus/#reports
Range 05-03-2023/14-11-2023, anyone with more than 50 lines changed gets a mention.
Except for some credits by me. Trust me, my Slovak is non-existant.
=> update the translation credits since the latest release

TRANSLATORS.md, pynicotine/gtkgui/dialogs/about.py
- Add credits for ssantos, who just finished the portuguese translation (1024 additions!)
- Reorder about.py, so the order is the same as with TRANSLATORS.md
=> a last minute job from ssantos

NEWS.md
+ #2537 since PR #2244 does satisfactorily resolve it.
=> NEWS.md: add closed issue

.github/workflows/tests.yml, debian/control, debian/tests/control, doc/DEVELOPING.md, setup.cfg, setup.py
As long as we support Python 3.6, this is a good way to ensure packaging works.
=> Restore support for Ubuntu 18.04

NEWS.md
Closes #2842 resolved by https://github.com/nicotine-plus/nicotine-plus/commit/714a8c4b15644eb102d2c7ed2c8e32a3a7b0b5c1
=> NEWS.md: closed issue

NEWS.md
+ Added: Version 3.3.1.dev1 (Unreleased) - Issues closed on GitHub
=> NEWS.md: add closed issues in 3.3.1

NEWS.md
If there are no other outstanding bug reports to fix, then suggest bump to 3.3.1rc1
=> NEWS.md: add latest changes, corrections and closed issues

pynicotine/gtkgui/userbrowse.py
+ Fixed: slight regression in the refresh mechanism since 952a3f44
=> userbrowse.py: remember path on refresh of local shares

pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/userbrowse.py
+ Changed: Label of user actions popup menu to match that used everywhere else.
=> "User Actions" menu labels

pynicotine/gtkgui/userbrowse.py
missing since https://github.com/nicotine-plus/nicotine-plus/commit/5427c5ec212789c6433493df45457f78f3c200bd
This PR includes 2 string changes.
=> gtkgui/userbrowse.py: restore download folder menu item accelerators

pynicotine/search.py
+ Changed: Import only the required function `random` from the `random` package
+ Changed: Import only the required function `shlex` from the `shlex` package
It's not needed to load an entire package if only a single function is called from it.
=> search.py: minor code cleanup imports

pynicotine/gtkgui/dialogs/preferences.py, pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/transfers.py, pynicotine/gtkgui/ui/downloads.ui, pynicotine/gtkgui/uploads.py
Matches other lists in the application.
Related to #2922
=> Transfers: rename Clear button to Remove

pynicotine/gtkgui/widgets/trayicon.py
Some desktop environments only support the legacy X11 tray icon implementation. We can keep it around until we drop support for GTK 3.
Fixes #2928
Fixes #2944
=> trayicon.py: restore GtkStatusIcon implementation

TRANSLATORS.md, pynicotine/gtkgui/dialogs/about.py
=> Add translator username to Toine

pynicotine/downloads.py
Delete incomplete download files that are no longer in the list.
=> downloads.py: delete stale incomplete downloads

pynicotine/gtkgui/widgets/textview.py
Minor code cleanup only. This function may be used more frequently in future.
=> textview.py: unify get_iter_at_line() function

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/ui/chatrooms.ui, pynicotine/gtkgui/ui/privatechat.ui, pynicotine/gtkgui/widgets/textentry.py
Prerequisite to port from Gtk.EntryCompletion to our ComboBox replacement. Also simplifies things a lot, since we no longer have to re-parent entry completion widgets and spell checkers separately.
=> ChatEntry: integrate chat completion and reuse between chats

pynicotine/events.py, pynicotine/gtkgui/application.py, pynicotine/gtkgui/dialogs/fastconfigure.py, pynicotine/gtkgui/ui/dialogs/fastconfigure.ui, pynicotine/headless/application.py, pynicotine/users.py
Try to be more helpful than just throwing people into the Preferences dialog.
=> Replace 'Invalid Password' dialog with setup assistant page

NEWS.md, data/org.nicotine_plus.Nicotine.appdata.xml.in, debian/changelog, pynicotine/__init__.py
We're still waiting for the GTK 4.14.5 release, which should hopefully happen this month.
=> Bump version to 3.3.5rc1

AUTHORS.md, TRANSLATORS.md, pynicotine/gtkgui/dialogs/about.py
I most likely forgot someone, but hopefully the majority of contributors are here.
=> AUTHORS.md: add list of contributors

debian/copyright
Format was changed in PR #3053, as a result, 2 files were removed and 1 file was added.
=> debian/copyright: ip_country_data.csv new file

pynicotine/gtkgui/ui/settings/network.ui
+ Changed: Preferences section header, reuses an existing string.
=> network.ui: Miscellaneous -> Connections

NEWS.md
=> NEWS.md: Close fixed issue in 3.3.7

pynicotine/__init__.py, pynicotine/config.py, pynicotine/core.py, pynicotine/gtkgui/application.py, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/dialogs/preferences.py, pynicotine/gtkgui/mainwindow.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/transfers.py, pynicotine/gtkgui/ui/settings/chats.ui, pynicotine/gtkgui/ui/settings/log.ui, pynicotine/gtkgui/ui/settings/plugin.ui, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/widgets/filechooser.py, pynicotine/pluginsystem.py
For situations where external applications are not available, such as Docker containers.
Related to #3219
=> Add optional isolated mode

NEWS.md
As a package maintainer I think it's worth mentioning.
Source: https://github.com/nicotine-plus/nicotine-plus/commit/77e5dc6d603bc8e1bac7159ff3727e34072d34a8
=> news: add line about skipping network unittests

doc/DEVELOPING.md
We haven't effectively followed semver for a while, and it's quite vague for a GUI application anyway. Attempt to document the current versioning scheme we've been using.
=> DEVELOPING.md: document current versioning scheme

pynicotine/downloads.py, pynicotine/events.py, pynicotine/gtkgui/dialogs/download.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/ui/dialogs/download.ui, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/widgets/treeview.py, pynicotine/search.py, pynicotine/tests/unit/transfers/test_downloads.py
TODO:
Maybe an option to add downloads in paused mode, but I want to implement https://github.com/nicotine-plus/nicotine-plus/issues/110 first to see if this is needed.
Closes #1659 
Closes #2686
=> Implement file download dialog

pynicotine/gtkgui/ui/settings/downloads.ui, pynicotine/gtkgui/ui/settings/uploads.ui
=> Preferences: improve download/upload auto-remove strings

pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userinfo.py
=> userbrowse/info.py: show different error message for offline users

pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/transfers.py, pynicotine/gtkgui/uploads.py, pynicotine/gtkgui/userbrowse.py
=> Transfers: add menu items to search for folder and file name

pynicotine/config.py, pynicotine/events.py, pynicotine/gtkgui/dialogs/preferences.py, pynicotine/gtkgui/ui/settings/shares.ui, pynicotine/shares.py
=> Implement automatic rescanning of shares

pynicotine/downloads.py, pynicotine/gtkgui/dialogs/download.py, pynicotine/gtkgui/ui/dialogs/download.ui
=> dialogs/download.py: add button to download paused

pynicotine/config.py, pynicotine/gtkgui/dialogs/preferences.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/ui/search.ui, pynicotine/gtkgui/ui/settings/search.ui
=> search.py: add filter to only show public files

pynicotine/plugins/plugin_debugger/PLUGININFO, pynicotine/plugins/plugin_debugger/__init__.py
+ Added: Settings for easily toggling each caller on or off as desired
=> plugin_debugger: Plugin Debugger Settings

pynicotine/gtkgui/widgets/combobox.py
Gtk.EntryCompletion is deprecated and doesn't support screen readers in GTK 4.
Implement a replacement that combines the entry completion with the combobox. Allows for reusing the model and menu popover.
Replaces #3071
=> Implement GTK 4 replacement for Gtk.EntryCompletion

pynicotine/config.py, pynicotine/gtkgui/ui/userinfo.ui, pynicotine/gtkgui/userinfo.py
Also remember the choice when browsing future profiles, and don't parse pictures until 'Show Picture' is clicked.
=> userinfo: add button to show/hide user pictures

pynicotine/gtkgui/application.py, pynicotine/gtkgui/dialogs/download.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/userbrowse.py
=> downloads.py: remember previously selected download folder path

pynicotine/gtkgui/buddies.py, pynicotine/gtkgui/css/style.css, pynicotine/gtkgui/dialogs/chathistory.py, pynicotine/gtkgui/dialogs/preferences.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/ui/chatrooms.ui, pynicotine/gtkgui/ui/dialogs/chathistory.ui, pynicotine/gtkgui/ui/dialogs/fileproperties.ui, pynicotine/gtkgui/ui/dialogs/statistics.ui, pynicotine/gtkgui/ui/mainwindow.ui, pynicotine/gtkgui/ui/privatechat.ui, pynicotine/gtkgui/ui/search.ui, pynicotine/gtkgui/ui/settings/search.ui, pynicotine/gtkgui/ui/userbrowse.ui, pynicotine/gtkgui/ui/userinfo.ui, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/widgets/treeview.py
Ensure numerical values and timestamps have consistent widths.
=> GUI: use tabular numbers when appropriate

pynicotine/gtkgui/dialogs/chathistory.py, pynicotine/gtkgui/dialogs/download.py, pynicotine/gtkgui/dialogs/fastconfigure.py, pynicotine/gtkgui/dialogs/pluginsettings.py, pynicotine/gtkgui/dialogs/preferences.py, pynicotine/gtkgui/dialogs/roomlist.py, pynicotine/gtkgui/dialogs/wishlist.py
Some list/tree views were missing them, mainly in the Preferences dialog.
=> GUI: add context menu to every tree/list view
