nicotine-plus/nicotine-plus

pynicotine/slskproto.py
Although there's some support for throttling open fd's, it's somewhat
unreliable. The upshot is select() continually fails on too many open
connections for popular search terms. Instead of doing nothing and
retrying select() (only to fail again), try to kill off a
non-transferring peer connection.
=> randomly kill connections on select() out of range failure

pynicotine/gtkgui/nicotine-settings.glade
pygtk would silently truncate any password longer than the max length
when setting the field with set_text. fixes #5
=> remove max length on settings password field

pynicotine/metadata_mutagen.py, pynicotine/shares.py
These fixes address problems with shares building where the mutagen library is used to gather metadata. In some cases metadata would incorrectly not be generated and in others, bogus metadata (values out of bound) would be generated, particularly for asf/wmv/etc type files. This bogus metadata would cause crashes when the files where requested.
=> Fix shares build / crashes caused by bogus metadata.

pynicotine/metadata_mutagen.py
Starting with Mutagen commit 65d5910c12d9a4a4e0c7de0316b494ac064828c9 the code
for detecting the VBR detection in nicotine is no longer working as it was
using a private interface.
In Mutagen commit 1ffd7dd97b145316b56ac7bd586a8ad8779d2b6d a public interface
to detect the VBR for MP3 files was introduced. Use it by default and fallback
to the old code in case an old version of Mutagen is in use.
=> Fix variable bitrate detection for MP3 files

pynicotine/gtkgui/settingswindow.glade
Per user request made via nicotine room ([><((((*>] on 2016-03-27).  Gives user the option to load more than 1000 previous chat lines when they rejoin a chat room.  The new limit is 10000.
=> Increase chatroom loglines

languages/fr/LC_MESSAGES/nicotine.po, languages/nicotine.pot, languages/pl/LC_MESSAGES/nicotine.po, manpages/nicotine.1, nicotine, pynicotine/gtkgui/frame.py, pynicotine/pynicotine.py, pynicotine/slskproto.py
Right now nicotine+ listens on all interfaces. This is not desirable for VPN usage because the Soulseek port will be exposed on non-VPN routes, or if the VPN disconnects.
You can verify the listening address with `lsof -i`.
=> Use bindip option for server socket

pynicotine/gtkgui/frame.py
The ui/icontheme which defaults as the empty string, was being evaluated
as to whether it existed (as opposed to was non-empty). Thus the code
always ran, and the path for a theme was constructed using the default
empty string ("") + the image path for the icon.
This meant if there was path-local resolvable images of the same name
and no theme, they would get dropped into the interface as if it was
a theme.
The fix is to use `dict.__getitem__'s` shortform of `dict.get` which
evaluates the empty string as a bottom value, as intended.
This bug appears to have been introduced in 40a0d921 when the icontheme
was first implemented in 2006.
=> Fixes loading of images from the launch directory (#113)

pynicotine/gtkgui/checklatest.py
Make the dialogs work in the GTK3 port.
=> Remove PyGTK leftovers in update check dialog

pynicotine/pynicotine.py, pynicotine/shares.py
* set messages about closed peer connection to the appropriate debug level
* fixed warning about possible corrupt files
=> Stop log spamming

nicotine, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/ui/mainwindow.ui
- Start logging earlier instead of fetching the log history after startup. Fixes a crash issue in some scenarios.
- Remove GTK 3.22 "set_propagate_natural_height" dependency, make the log view fill the height immediately instead. Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/140
- Fix Color/RGBA mismatches in chats
- Make tick dialog radio buttons functional again
- Reduce statusbar padding to default
=> Fixes to chats and log view

plugins/README, pynicotine/pluginsystem.py, setup.py
Would be nice to have the plugins included by default, and potentially detect issues in them.
=> Ship plugins system-wide

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/uploads.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userinfo.py, pynicotine/gtkgui/userlist.py, pynicotine/gtkgui/utils.py, pynicotine/pynicotine.py, setup.py
Attach menus to a parent widget to prevent them from closing unintentionally.
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/143
Fixes a few console warning messages when using Wayland.
=> Attach menus to a parent widget

pynicotine/config.py, pynicotine/gtkgui/chatrooms.py
Let the last column of every page fill the remaining width, instead of resizing it to a ridiculous width.
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/165
=> Let last column expand naturally

pynicotine/gtkgui/frame.py, pynicotine/gtkgui/ui/mainwindow.ui, pynicotine/gtkgui/ui/userinfo.ui, pynicotine/gtkgui/userinfo.py
Since it seems like a GtkScrolledWindow inside a GtkExpander won't fill the available space in GTK3, no matter what you do, I've removed the expanders and utilized more horizontal space instead.'
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/148
Screenshots:
=> Remove GtkExpander

pynicotine/gtkgui/frame.py
The Soulseek protocol supports a MOTD feature, but I don't think the official server sends one. Don't show an empty line if the MOTD is empty. Also no point in decoding the message here, since it's already decoded.
=> Don't show empty MOTD

pynicotine/gtkgui/ui/mainwindow.ui
Glade added these, but we don't want them, since it breaks text input.
=> Accept text input again

pynicotine/config.py, pynicotine/gtkgui/fastconfigure.py
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/64
There is nothing wrong with username/password configuration, but the log messages caused confusion. Remove log messages about unset username/password, and add a log message when setup was successful.
=> Remove unnecessary log messages

pynicotine/metadata_mutagen.py
Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/62
I was not able to reproduce the issue, I'd assume it's fixed in mutagen. If it still occurs, there isn't much we can do about it.
Mutagen exceptions can still show up in the console, but hide them from the log view.
=> Don't add Mutagen exceptions to log

pynicotine/config.py, pynicotine/gtkgui/fastconfigure.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/utils.py
Don't rely on commands/handlers by default to open links, which seems to have failed on Windows. Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/65
GnomeVFS was deprecated in 2008.
=> Use GTK way of opening links by default

pynicotine/gtkgui/frame.py
"default font" is not a valid font, and caused lists to use some fallback font instead of the application default.
=> Don't use invalid font for lists

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/userinfo.py, pynicotine/gtkgui/utils.py
If no custom color was specified, a default color for the currently applied theme was hardcoded. If the theme was changed, the color would therefore not update. Instead of doing this, we now set the color to None.
Fixes the color issue in https://github.com/Nicotine-Plus/nicotine-plus/issues/186
Also cleaned up needless complexity and some unused code.
=> Clean up color handling

debian/control, test/integration/nicotine.robot
This dependency was introduced somewhere but not added to debian/control. Fixing this.
=> gir1.2-notify-0.7 dependency

pynicotine/gtkgui/settingswindow.py
It's old and doesn't support picking colors from your screen on Wayland.
=> Replace deprecated GtkColorSelectionDialog

pynicotine/config.py, pynicotine/gtkgui/frame.py, pynicotine/pynicotine.py
Part of https://github.com/Nicotine-Plus/nicotine-plus/issues/215. Cuts loading time of the main window in half for me. Improvements can possibly be made in the settings dialog later.
Also remember if the main window is maximized or not.
=> Initialize a few windows/dialogs later

pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/frame.py
If the away timer expires, we shouldn't attempt to remove it, since it's already destroyed.
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/103
=> Don't remove non-existent away timer

pynicotine/gtkgui/frame.py
A GTK error would show up if the buddy list tab was hidden/non-existent. The buddy list tab is still listed in the tab order section of the config, and an attempt was made to change the order of it.
=> Don't attempt to change order of non-existent tab

pynicotine/gtkgui/downloads.py, pynicotine/multiselect.py, pynicotine/slskproto.py
This way we automatically use the best syscall for the platform (epoll, poll etc.), thus bypassing the file descriptor limit of select().
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/77 (this happened when there were many search results, and thus too many connections)
=> Use Python selectors module instead of select()

pynicotine/gtkgui/tray.py
In case Nicotine+ was not installed system-wide.
=> Look for tray icons in local folder too

pynicotine/gtkgui/frame.py
Prevent needless tab order and visibility writes to config by registering tab events after the tabs have been set up completely. 
Also stops the tab order in config from changing before the tabs are reordered for the first time. Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/242
=> Register tab events later

pynicotine/gtkgui/frame.py
Reverts a mistake in https://github.com/Nicotine-Plus/nicotine-plus/pull/230. Don't show an empty pane if the buddy list is not set to always visible, hide it like before.
=> Buddy list pane should be hidden when always show is not selected

NEWS, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/utils.py
- Read log files line by line instead of loading the whole file into memory
- Unify ScrollBottom functions into one
- Drop textbuffer history clearing code, since 1. it caused issues, and 2. there isn't really a point in limiting visible chat rows to 400. Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/253
=> Small chat improvements

pynicotine/gtkgui/dirchooser.py
- Use the native file chooser of the platform (fall back to the GTK file chooser on GTK <3.20)
- Fix some deprecation warnings
=> Use native file chooser when possible

README.md, files/appdata/org.nicotine_plus.Nicotine.appdata.xml
See https://hughsie.github.io/oars/generate.html
- social-chat set to intense, since the chatrooms seem quite uncontrolled/unmoderated and contain all kinds of nasty content (are there any moderators?).
- social-info (Information Sharing) set to mild, due to using an "API" (not exactly the case, but still. Soulseek is somewhat vague on this part).
=> Add OARS rating

pynicotine/gtkgui/frame.py
Gets rid of most, if not all remaining GTK warnings.
I think we can finally close https://github.com/Nicotine-Plus/nicotine-plus/issues/99 :)
=> Don't attempt to scroll down in a hidden log view

nicotine
I'm not sure how the c interface works but it was setting the process title to "n" for me. When passing it as a list of bytes like this it is correctly set to "nicotine".
Also not sure why I've ran into this on two machines (finally updated the one on my seedbox) and no-one else has reported it.
Locales shouldn't be an issue as it doesn't look like the string passed is being localized.
=> Fix setting process title without procname

pynicotine/gtkgui/search.py
If you had a preset filter, and searched for something, only results from the first 500 stored ones would show up. Thus, you ended up with significantly less results displayed than the 500 limit. Before adding results, we now check the length of the actual results model, instead of the result's count, allowing us to add data from the full 1500 stored results.
Also store the status at the correct index in the row.
=> Show correct number of results with filters enabled

pynicotine/slskproto.py
Hard-cap MAXFILELIMIT at 1024, since allowing more connections causes the GUI performance to tank when searching for popular files. Eventually we should look into improving the performance, if possible, but I suspect the constant callbacks to the GUI thread cause quite a large performance hit.
I remember reading some performance regression bug report a while ago, could possibly be because the file limit was bumped from 1024 to 2048 in 2011, after the 1.2.16 release: https://github.com/Nicotine-Plus/nicotine-plus/commit/c57c20aae465433dc6c1f852166a7cd57693b4f8#diff-690875db582e0a4efbe417b755ad2882
=> Set MAXFILELIMIT to 1024

pynicotine/upnp.py
The only environment we support on Windows nowadays is MinGW, which doesn't need these workarounds.
=> Remove Windows-specific upnp code

pynicotine/slskmessages.py
Allows us to properly display special characters sent from the old Soulseek NS client.
=> Add encoding fallback for incoming strings

pynicotine/gtkgui/frame.py, pynicotine/shares.py, pynicotine/transfers.py
- If we're sharing our downloads folder, make sure we use the virtual directory name instead of the real one when adding new files, otherwise people can't download our files.
- If buddy shares were enabled, the downloads share wouldn't update properly due to code errors.
- Don't attempt to show the notification if the file didn't download properly
=> Properly share downloaded files

pynicotine/gtkgui/dirchooser.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/userbrowse.py
- Get rid of CREATE_FOLDER file choosers, since FileChooserNative doesn't support them
- Remove a few PyGTK leftovers
- Prevent segfault when removing rows from the auto-replace list
=> A few minor fixes

NEWS, pynicotine/gtkgui/userbrowse.py
An empty folder is not necessarily going to be listed in the shares list, which results in the recurse code never being reached due to the d != dir check. Move the code outside the main loop instead.
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/311
=> Make recursive downloads functional in empty folders

pynicotine/gtkgui/transferlist.py
A selected transfer shouldn't be absent from the transfer list.
=> Remove unnecessary loop when deleting downloads

NEWS, pynicotine/gtkgui/entrydialog.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/userbrowse.py, pynicotine/transfers.py
The getFile function is also called when retrying a file download, both automatically and manually. We should not check for duplicate downloads in this case.
Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/312
=> Only check for duplicate downloads when appropriate

NEWS, README.md, doc/SLSKPROTOCOL.md, pynicotine/pynicotine.py, pynicotine/shares.py, pynicotine/slskmessages.py, pynicotine/slskproto.py
- Clean up and update Soulseek protocol documentation with newer information
- Clean up protocol message code
- Add distrib type 93 (https://github.com/jpdillingham/Soulseek.NET/issues/228). Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/322
- Add padding to search term bytes when unpacking, if necessary. This prevents the program from breaking if distributed search terms are shorter than 4 characters, since struct.unpack needs exactly 4 bytes.
=> Improvements to distributed searches

doc/SLSKPROTOCOL.md, pynicotine/slskmessages.py
This allows Nicotine+ to download >2GB files from other Nicotine+ clients by not truncating the file size, but attempting to download a large file from someone using the official SoulseekQt client still results in a 0 byte file size reported from them...
=> Use long long for file size in file request

pynicotine/gtkgui/frame.py, pynicotine/pynicotine.py
Requesting the hostname of an IP address could freeze/block the UI for up to 15 seconds in some cases. Also fixed an issue where the worldwide flag image wouldn't show up in the user list, if the user's country is unknown.
=> Don't request hostname for IP addresses

NEWS, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/privatechat.py
I forgot to remove is_mapped from other parts of the code after I removed it from tray.py. This should also fix some notification issues.
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/330
=> Properly check if window is hidden or not

NEWS, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/transferlist.py, pynicotine/gtkgui/uploads.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userlist.py, pynicotine/gtkgui/utils.py
T.I.L. Nicotine+ allows you to reorder columns... Disable this functionality for now, since the current way of saving column widths isn't designed with this in mind.
Also allow rubber banding (selection of multiple rows by dragging your cursor), and remove the deprecated rules-hint-property.
=> TreeView tweaks

pynicotine/gtkgui/transferlist.py
Non-folder downloads currently have an empty path, which resulted in all downloads being added to the first user with an empty path in the downloads TreeView. Make sure downloads are added to the correct user.
=> Ensure we don't group downloads under the wrong user

pynicotine/gtkgui/search.py
In search results, a queue position is sometimes sent even though the immediate download flag is sent. I don't think it makes sense to show the number of queued transfers for the user, if it doesn't have an impact on our download. The official client doesn't do this either.
=> Set queue counter to zero if immediate download

pynicotine/config.py, pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/transferlist.py, pynicotine/gtkgui/ui/mainwindow.ui, pynicotine/gtkgui/uploads.py, pynicotine/slskproto.py, pynicotine/transfers.py
Several fixes to hopefully resolve https://github.com/Nicotine-Plus/nicotine-plus/issues/336, and some general improvements.
- Hopefully ensure that the UI always shows the correct file percentage
- If a transfer happens to be initiated when the the progress is 100%, move it to the finished downloads folder instead of endlessly trying to download more from the peer
- Remove toggle to disable auto-retry of failed downloads, make this feature mandatory
- Add option to autoclear finished downloads
- Actually display our own uploads aborted by the remote as aborted, and include them in the autoclear uploads-feature, like SoulseekQt does
Don't merge yet, I'm waiting for feedback from @hboetes
=> Improved handling of transfers

pynicotine/config.py
This limit (100 MB) was supposed to represent the size of a full album according to the old Nicotine+ guide, but is pretty low today due to increasing interest in lossless music. Bump it to a generous 10GB to prevent issues where large files can't be shared if a user forgot to modify their limits.
=> Bump default megabyte limit for queue

pynicotine/gtkgui/frame.py, pynicotine/gtkgui/ui/mainwindow.ui
I feel like these menu items are a bit redundant, considering we already have a website link in the about-window, and a link to report bugs.
=> Remove redundant links

pynicotine/gtkgui/frame.py
There have been times where I accidentally started searching before upnp mapping had finished, and the networking seemed to stall as a result.
=> Disable a few elements until client is logged in

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/roomlist.py, pynicotine/gtkgui/ui/buddylist.ui, pynicotine/gtkgui/ui/roomlist.ui, pynicotine/gtkgui/userlist.py, pynicotine/gtkgui/utils.py
User statuses would reset if you changed the position of the buddy list. The code comment mentions "Reinitialize the userlist to avoid an error that freeze the UI on recent GTK versions", but this doesn't seem to be the case anymore.
Also some minor cleanup, and removal of buttons that were oddly placed.
=> Don't reset buddy list when moving it

pynicotine/gtkgui/search.py
Previously, the length of the audio file was shown as the bitrate for lossless audio files. Show the actual length and bitrate of the audio. This will be a bit inaccurate for lossless compressed audio (e.g. flac), but an approximation is better than nothing in terms of filtering.
=> Show proper metadata of lossless files

plugins/leech_detector/PLUGININFO, plugins/leech_detector/__init__.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/ui/settingswindow_PluginFrame.ui
I'd imagine this is a feature people want.
Also some code tweaks to immediately enable the plugin properties button when enabling a plugin.
=> Add option to change leech detector message

pynicotine/config.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userinfo.py, pynicotine/transfers.py, pynicotine/utils.py
- There are multiple code snippets for reading audio lengths and bitrates that have been forgotten over the years. Use a unified function instead.
- Show human-readable upload speeds on the user info page
- Show human-readable file sizes on the user browse page
=> Show correct audio length and bitrate everywhere

pynicotine/pynicotine.py, pynicotine/slskmessages.py, pynicotine/slskproto.py
This function needs to accept the conn argument. Fixes messages about no handler for class when receiving this message.
=> Fix for peer message 12547

pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/transferlist.py, pynicotine/gtkgui/uploads.py, pynicotine/gtkgui/userbrowse.py, pynicotine/transfers.py
- Don't add downloads and uploads to the wrong panels
- Remove transfers properly
- Make direct upload to user feature functional again (found when right-clicking files in your own user share)
- Tell the remote user when we abort our upload
=> Multiple transfer list fixes

README.md, pynicotine/config.py, pynicotine/gtkgui/fastconfigure.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/ui/fastconfigure.ui, pynicotine/gtkgui/ui/settingswindow_ServerFrame.ui, pynicotine/upnp.py
- List miniupnp as a required dependency, and enable UPnP by default (like SoulseekQt) to cut down on potential connection issues among new users
- Unlink UPnP and direct connection checkboxes, since UPnP doesn't guarantee that direct connections are possible (e.g. ports blocked on ISP level). UPnP will still help if there are many clients on the same network.
=> Add miniupnp to required dependencies

NEWS, pynicotine/gtkgui/search.py, pynicotine/shares.py
- Don't open tabs for wishlist search results if the results won't be added due to being spoofed/incorrect/filtered
- Don't send search responses to our own search requests
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/380
=> Only show new wishlist tabs when supposed to

pynicotine/upnp.py
No need to see this message every time you start Nicotine+. Warning messages are more important. Also stop setting the status message to "Listening on port x", since this was already done much earlier.
=> Make UPnP map message a debug message

README.md
Don't merge until Nicotine+ 2.0.0 has made it out of Manjaro unstable.
=> Add install instructions for Arch and Parabola

NEWS.md
I replaced the issue numbers with clickable links.
This is basically the result of this command:
```
sed -i 's|#\([0-9]*\)|([#\1](https://github.com/Nicotine-Plus/nicotine-plus/issues/\1))|' NEWS.md
```
I hope the renderer picks it up properly, otherwise we could consider dropping the parenthesis around the issues numbers.
=> Change the ticket numbers to real links in the NEWS.md file

NEWS.md
Second attempt at fixing the NEWS.md, the first created an unintended additional set of parenthesis. Also some lines contained multiple ticket numbers, they have been linked as well.
Thanks for understanding, I don't have access to a renderer. I should look into one.
=> Change the ticket numbers to real links in the NEWS.md file, 2nd attempt

README.md, doc/PACKAGING.md, files/windows/nicotine.nsi, files/windows/nicotine.spec, pynicotine/utils.py
- Fixed an error that prevented Nicotine+ from starting if translations were requested.
- Cleanups
Corrected 2.0.1 installers to attach to GitHub release:
- 64-bit: https://github.com/mathiascode/nicotine-plus/blob/42b9136bf815f40a90b3c1eee92602a2172ace45/files/windows/Nicotine+-2.0.1-x86_64.exe?raw=true
- 32-bit: https://github.com/mathiascode/nicotine-plus/blob/42b9136bf815f40a90b3c1eee92602a2172ace45/files/windows/Nicotine+-2.0.1-i686.exe?raw=true
=> Improvements to Windows build

pynicotine/gtkgui/about.py, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userinfo.py, pynicotine/gtkgui/utils.py
Considering nobody has reported any of the issues associated with detached tabs recently (popups not appearing on the correct window, crammed content, errors when closing windows, a boatload of gtk warnings), and I didn't realize detached tabs were supported until now, I'm going to assume the usage is very low. For now, I don't see a point in maintaining support for detached tabs.
=> Remove support for detached tabs 

pynicotine/config.py, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/fastconfigure.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/utils.py, pynicotine/pluginsystem.py, pynicotine/pynicotine.py, pynicotine/shares.py, pynicotine/transfers.py, pynicotine/utils.py
Yay to less platform-specific code. :)
Pretty sure none of this is needed in Python 3 anymore. I didn't detect any issues when testing in Windows.
The config is now saved as utf-8 on Windows, to fix problems when using non-latin characters.
=> Remove Unicode-related Python 2 leftovers

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/ui/about/privatechatcommands.ui, pynicotine/gtkgui/ui/chatrooms.ui, pynicotine/gtkgui/ui/mainwindow.ui, pynicotine/gtkgui/ui/privatechat.ui, pynicotine/gtkgui/ui/roomlist.ui, pynicotine/gtkgui/ui/userbrowse.ui
An attempt to reduce the number of vertical elements in the user browse UI to leave more room for files, and just make everything tidier in general.
=> Improve chat room and user browse UI

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/roomlist.py, pynicotine/gtkgui/ui/mainwindow.ui, pynicotine/gtkgui/ui/roomlist.ui, pynicotine/gtkgui/ui/search.ui
At the protocol level, enabling/disabling private rooms doesn't disable the whole private rooms feature, it just toggles your ability to be added to a private room. Update the UI to make this clear.
=> Rework confusing enable/disable private rooms option

pynicotine/gtkgui/fastconfigure.py, pynicotine/gtkgui/nowplaying.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/ui/about/chatroomcommands.ui, pynicotine/gtkgui/ui/about/privatechatcommands.ui, pynicotine/gtkgui/ui/about/searchfilters.ui, pynicotine/gtkgui/ui/fastconfigure.ui, pynicotine/gtkgui/ui/nowplaying.ui, pynicotine/gtkgui/ui/settingswindow.ui
- Now using GtkDialog for all windows, to bring back esc to close-functionality
- Text in about search filters-dialog is now selectable
- Chat commands can now be selected with tab key in the about-dialogs
=> Fix accessibility issues related to dialogs

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/checklatest.py, pynicotine/gtkgui/dialogs.py, pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/fastconfigure.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/nowplaying.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/tray.py, pynicotine/gtkgui/ui/nowplaying.ui, pynicotine/gtkgui/ui/wishlist.ui, pynicotine/gtkgui/uploads.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userlist.py, pynicotine/gtkgui/utils.py, pynicotine/pynicotine.py
Painstaking work, but almost every small dialog should now use the GtkMessageDialog GTK 3 style. The only two dialogs that still contain deprecated elements are the find and metadata ones. Still not entirely sure what to do with find, and the metadata dialog should preferably be ported to a ui file.
=> Port most dialogs to GtkMessageDialog

pynicotine/config.py, pynicotine/gtkgui/frame.py, pynicotine/shares.py, pynicotine/slskmessages.py
- Large improvements to performance when scanning user share
- Reduced memory usage
- Improve user browse response performance by using a byte array. On a share with 1.5 million files, this change cuts down the startup time of Nicotine+ from indefinite (hanging) to ~4 seconds.
=> Improve user share performance

pynicotine/gtkgui/settingswindow.py
Didn't realize the deprecated get_font_name had been replaced by the similarly named get_font function.
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/458
=> Fix errors regarding getting and saving fonts

pynicotine/config.py, pynicotine/gtkgui/frame.py, pynicotine/shares.py
- Send number of files and folders a bit later, to ensure that the shares db is open. Should fix https://github.com/Nicotine-Plus/nicotine-plus/issues/454
- Remove pointless creation of list
- No need to sync shelves, as we're not in writeback mode
- Compress file share response in a new thread, to get consistent startup times no matter how large your file share is
- Remove unneeded code
- A whole lot of changes according to profiling results
=> Further file scanning optimizations

NEWS.md
So we hopefully don't have packages still including Mutagen as a dependency after 2.1.0 is released.
=> Clarify that Mutagen has been replaced

pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/transferlist.py, pynicotine/gtkgui/uploads.py
- Replace outdated dialog code
- Use sets instead of lists for selected transfers and users, to ensure entries are always unique
- Remove unnecessary calls to select_transfers
=> Improvements to transfer list

pynicotine/gtkgui/ui/search.ui
Allows the items in the filter bar to wrap when the window is smaller. Partially fixes. https://github.com/Nicotine-Plus/nicotine-plus/issues/474
=> Use GtkFlowBox for filter bar

pynicotine/gtkgui/search.py
When search filters are enabled, the data in all_data and the results model don't match up, so we can't rely on the index to get the correct result.
=> Fix user status update in ungrouped search mode with filters

pynicotine/gtkgui/ui/chatrooms.ui
Use an icon that's more widely recognized on systems.
=> Use different icon for room wall button

pynicotine/shares.py
If it's in place, SoulseekQt gets stuck when rebrowsing a share. The user share list is only generated once on startup, so sending it isn't a performance problem.
=> Remove user browse cooldown

pynicotine/gtkgui/ui/chatrooms.ui
To account for the small spacing added to columns recently.
=> Slight width increase of chat room user list

files/windows/dependencies.sh
Temporarily fixes Windows packaging.
=> Downgrade PyInstaller to 3.6 for now

AUTHORS.md, pynicotine/gtkgui/ui/about/about.ui
@Mutnick If you're still around, and ever feel like contributing to Nicotine+ again, feel free to add yourself back to the list of active devs.
=> Update list of active developers

files/macos/dependencies.sh
PyInstaller 4.0 is adding around 1GB of unnecessary files to the MacOS builds...
=> Use PyInstaller 3.6 on macOS for now

nicotine, pynicotine/gtkgui/frame.py
We can't handle multiple instances of Nicotine+. Ensure users don't open multiple windows by mistake.
=> Only allow one instance of Nicotine+ to be open at a time

pynicotine/gtkgui/ui/settings/server.ui, pynicotine/gtkgui/ui/settings/settingswindow.ui
In my opinion, reduced lock-in is a good idea for Nicotine+. If people want to change the port of the official server, or host their own Soulfind server, let them do so.
=> Allow users to change the server in the settings

doc/SLSKPROTOCOL.md, pynicotine/pynicotine.py, pynicotine/slskmessages.py, pynicotine/slskproto.py
The "NetInfo" name is misleading. The only purpose of this server message is to send us a list of parents to connect to.
=> Rename NetInfo message

pynicotine/pynicotine.py
I'd assume this is false by default on the server level, but just to make sure.
=> Tell the server we don't accept children for now

pynicotine/shares.py, pynicotine/slskmessages.py, pynicotine/utils.py
Turns out SoulseekQt also switched to TagLib a few years ago, and dropped variable bitrate information for tracks, as TagLib doesn't provide it.
=> Remove variable bitrate information

pynicotine/pynicotine.py
Previously, it could take a long time to find a working parent connection to send us search requests, since in the worst case scenario we connected to a potential parent, waited for a response or timeout, and then proceeded to the next parent in the list. I noticed that SoulseekQt connects to all 10 potential parents at once, and adapted the same behavior in Nicotine+. As a result, distributed searches should be up and running within a minute of starting Nicotine+.
=> Make distributed searches more reliable

pynicotine/pluginsystem.py
As far as I can tell, there is no point in starting a new thread for every incoming event. It adds overhead when events are frequent (e.g. distributed search requests).
=> Plugin system: don't start new thread for every incoming event

pynicotine/gtkgui/downloads.py
Since the file attribute is now removed from the transfer object after the download has finished, the function exited too early.
=> Make "send to player" feature functional when file has downloaded

pynicotine/shares.py
After the changes in https://github.com/Nicotine-Plus/nicotine-plus/pull/494, the check has to go higher up in the code. It can happen quite frequently when Nicotine+ is shutting down and we're receiving a search request.
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/545#issuecomment-674294623
=> Check earlier if wordindex is closed before processing search request

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/transferlist.py, pynicotine/gtkgui/ui/mainwindow.ui, pynicotine/gtkgui/ui/settings/downloads.ui, pynicotine/gtkgui/ui/settings/fonts.ui, pynicotine/gtkgui/ui/settings/shares.ui, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userinfo.py
- Use icon name "document-edit-symbolic", which is more common, instead of "edit-symbolic"
- Remove option to set background color on lists for now, since it breaks item highlights and usability
- Move option to hide transfer buttons out of font settings
=> Minor UI improvements and corrections

pynicotine/pynicotine.py
By the time our old parent disconnects, the connection stored in parentconn has most likely become out of sync with the one in the peer conn list, which leads to Nicotine+ never asking the server for a new parent. Revert to the old way of getting our parent connection.
=> Fix issue where we don't get a new parent after previous disconnected

pynicotine/gtkgui/uploads.py, pynicotine/transfers.py
Makes the retry and abort buttons on the uploads page functional again, and fixes a small issue with duplicate downloads I discovered when downloading my own files.
=> Minor fixes related to uploads

pynicotine/gtkgui/uploads.py
Seems like this was broken in 1.4.x too.
=> Make "send to player" feature on uploads page functional

pynicotine/pynicotine.py, pynicotine/transfers.py
If we attempt to transfer a file to a user from our end, but the connection to the user doesn't go through for some reason (most likely firewall issues), the uploads are now cancelled instead of being stuck in a connecting state.
Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/564
=> Properly cancel uploads if we can't connect to user

pynicotine/gtkgui/downloads.py, pynicotine/transfers.py
The queue position is currently only updated when adding a download or manually requesting the position. Request the queue position regularly instead.
=> Regularly ask for queue position of downloads

pynicotine/slskproto.py
Reverts Nicotine-Plus/nicotine-plus#543
This change is too dangerous. It caused uploads to cancel if the user limited their download speed.
=> Revert "Close stale connections more frequently"

pynicotine/gtkgui/frame.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/wishlist.py, pynicotine/pynicotine.py
- Separate wishlist code from the rest of the search-related code
- Reduce code redundancy a bit
- Add ability to rename wishlist items by clicking on them. Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/499
- Search for one wishlist item instead of three per search interval (12 mins), since the server only accepts one. This should resolve issues with poor wishlist results due to "skipping" wishlist search terms.
=> Improve wishlist feature

pynicotine/pynicotine.py
"remotedownloads" contains a True/False value, but we expect an integer when creating the UserInfoReply message.
=> Don't send UserInfoReply message containing a boolean

pynicotine/config.py, pynicotine/gtkgui/settingswindow.py
All of these integers are replaced with booleans after saving settings once, so just use boolean from the beginning.
=> Config: use boolean instead of integer when possible

pynicotine/config.py, pynicotine/gtkgui/roomwall.py, pynicotine/pynicotine.py
We have no reason to remember our ticker messages anymore, since they are always per-room now and remembered by the server.
=> Config: remove everything ticker-related

pynicotine/pynicotine.py
Since we're only finding a single connection, removing it, and exiting the loop, there's no need to create a copy of the peerconns list.
=> Don't create copy of peerconns list

pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/fastconfigure.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/notifications.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/ui/about/about.ui, pynicotine/pynicotine.py
- Cache a few strings that are used often, to prevent requesting them from disk every time.
- Status strings that are sent to other clients should not be translated. The translation of the "geoip" string was needlessly requested from disk every time we received a search request (10-20 times a second).
- Consistency improvements for dialog titles
=> Optimize string translation access in a few cases

pynicotine/gtkgui/frame.py, pynicotine/gtkgui/transferlist.py, pynicotine/gtkgui/utils.py, pynicotine/slskproto.py, pynicotine/transfers.py
- Simplify code a bit
- Cache status strings to prevent requesting translations too often
- Reduce stress from updating transfer list text color
- When removing all transfers under a folder or user, there is no longer a delay before the folder and user rows are removed
- Don't create useless outsocks list
=> Transfer list improvements

pynicotine/gtkgui/search.py
If we have selected several search results that belong to the same folder, and press "Download folder", we shouldn't repeatedly send a folder content request for every selected search result.
=> Don't spam users with folder content requests

pynicotine/gtkgui/frame.py, pynicotine/logfacility.py
- Removed logfacility history, since it's not used for anything
- Avoid log callbacks if a debug level is not enabled in the log view
=> Reduce unnecessary log callbacks

files/windows/nicotine.spec
At some point we should do some launch tests on Windows and macOS packages too, to detect issues like this sooner.
=> Temporary fix for Windows build not launching

pynicotine/pynicotine.py, pynicotine/slskproto.py, pynicotine/transfers.py
- Add break statements in places where we don't need to complete a loop
- Make use of the transfer direction value where possible, to determine if we should update a transfer in the downloads or uploads list
- When starting Nicotine+, avoid sending a peer address request for every download in the transfer list, if the downloads are from the same user
=> Further performance optimizations for transfers

pynicotine/slskproto.py
There were two cases where a UI callback was missing in the network thread: when removing stale connections that timed out, and when the connection count limit was exceeded. This caused PeerConnection objects to stay around in the UI thread's peerconns list (https://github.com/Nicotine-Plus/nicotine-plus/issues/416#issuecomment-666034572). It was quite common for the peerconns list to grow quite large when repeatedly searching for popular search terms.
=> Don't let PeerConnection objects exist indefinitely

README.md
Ubuntu 19.10 has reached EOL and is no longer built.
=> Remove Ubuntu 19.10 from readme

files/windows/nicotine.spec
Fixes update checker on Windows.
=> Include CA bundle for update checker with PyInstaller

pynicotine/gtkgui/dirchooser.py, pynicotine/gtkgui/ui/about/chatroomcommands.ui, pynicotine/gtkgui/ui/about/privatechatcommands.ui, pynicotine/gtkgui/ui/about/searchfilters.ui, pynicotine/gtkgui/ui/fastconfigure.ui, pynicotine/gtkgui/ui/mainwindow.ui, pynicotine/gtkgui/ui/nowplaying.ui, pynicotine/gtkgui/ui/roomwall.ui, pynicotine/gtkgui/ui/settings/downloads.ui, pynicotine/gtkgui/ui/settings/shares.ui, pynicotine/gtkgui/ui/wishlist.ui, pynicotine/gtkgui/utils.py
Fixes a few issues I found when using older GTK3 versions (Ubuntu 16.04, GTK 3.18)..For some strange reason, a few elements had a negative height when dialogs weren't resizable.
=> Fix minor issues in older GTK versions

pynicotine/shares.py
Might make scanning performance slightly worse, but it's necessary to prevent the client from sending duplicate search results.
=> Avoid sending duplicate file results

pynicotine/shares.py
If someone searched for, say, "°  °   °", the stage 1 loop would effectively be skipped, when the intent was to iterate over the ° characters.
=> Fix error where search term loop is skipped

pynicotine/gtkgui/frame.py, pynicotine/gtkgui/nowplaying.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/utils.py, pynicotine/utils.py
For the small number of http-related features we need, importing urllib.request is overkill. Since version checking is not done often, we can also cut down on startup import time a bit by importing http.client on demand.
=> Drop urllib.requests import

pynicotine/gtkgui/chatrooms.py
Not sure why it was decided to remove dates to begin with, but it makes it impossible for me to check from which day past messages are, without opening the log files themselves.
=> Show log entry dates in chatrooms

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/privatechat.py
Since utf-8 isn't default on Windows. Luckily the log files have been saved as utf-8 for a long time, so there's no need to convert anything.
=> Open log files as UTF-8

pynicotine/shares.py, pynicotine/slskmessages.py
Since https://github.com/Nicotine-Plus/nicotine-plus/pull/637 replaced the filter in favor of a faster set solution, there is no need to create a result list anymore.
=> Remove unnecessary list creation when sending search results

pynicotine/gtkgui/transferlist.py, pynicotine/transfers.py
Sometimes queue failure messages will be sent when the transfer status is not "Queued". If you tried to download files from a SoulseekQt user who had unshared their files, the transfer status would be stuck on "Getting address".
I suspect this could "solve" a few cases where downloads can seem stuck when adding them.
=> Update transfer status on queue failure in more cases

pynicotine/transfers.py
The "QueueFailed" message (confusing name) is sent for transfers in progress as well, so abort those. Also send the correct ban message for transfers in progress.
=> Quit transfers in progress on queue failure

files/appdata/org.nicotine_plus.Nicotine.appdata.xml
Necessary for Flathub, unfortunately I forgot to do this. I think I'll just bump the commit used for building the Flatpak once this is merged.
=> Add 2.1.0 to appdata

pynicotine/pynicotine.py
There are times where GetPeerAddress will be called outside the ProcessRequestToPeer function, and the user_addr_requested list isn't used in those cases.
=> Minor fix for user address request list

pynicotine/gtkgui/search.py
This would be an easy way to get a full search term from a previous tab and easily make changes to it.
Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/383
=> Add option to copy a previous search term

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/userlist.py
These were some low-hanging fruit I noticed in py-spy.
Since usernames in public rooms never have a special style, and private rooms can't be converted to public rooms, there doesn't seem to be a point in constantly setting the cell properties to the defaults.
=> Don't update room username styles in vain

pynicotine/gtkgui/utils.py, pynicotine/slskproto.py
If our transfer speed limit is set too low while we have too many concurrent downloads, the limit can become negative, effectively bypassing the max limit. Cap the min speed per transfer to 1 KB/s.
=> Make sure transfer speed limit can't be bypassed

pynicotine/gtkgui/transferlist.py, pynicotine/slskproto.py
Use per-transfer cooldowns instead of a global one, since it was fairly common that only one transfer would be updated in the UI, if there were many simultaneous transfers.
=> Improvements to UI callback cooldown for transfers

.github/workflows/packaging.yml, files/windows/nicotine.spec
Once the checks pass, the Windows installers from this PR can be added to the 2.1.1 release. I've tested both the 32-bit and 64-bit ones.
=> Disable UPX on 32-bit Windows

debian/changelog, files/windows/nicotine.nsi, pynicotine/config.py, pynicotine/gtkgui/frame.py, pynicotine/pynicotine.py, pynicotine/shares.py, pynicotine/slskmessages.py, pynicotine/transfers.py, pynicotine/utils.py
- When rescanning shares, save a lot of memory by writing data directly into the file index db. This also reduces GUI freezes.
- Fix "add downloads to share"-feature, which was calling a removed function
- Use the correct progress bar when rescanning buddy shares
- Remove everything shares-related from config.py, simplify shares loading code
- Remove unnecessary code, move code not related to GUI to shares.py
=> Refactor code related to shares

doc/SLSKPROTOCOL.md, pynicotine/gtkgui/privatechat.py, pynicotine/pynicotine.py, pynicotine/slskmessages.py
The server sends us a boolean value that we can use to figure out if a private message was sent to us while we were offline. Use this value instead of our previous calculation, and don't display offline messages as new ones (small error on line 223 in privatemessages.py).
The server value was previously assumed to indicate whether a private message was sent by an admin or not, but this turned out to be incorrect.
=> Properly display messages sent to you while offline

pynicotine/gtkgui/frame.py, pynicotine/pynicotine.py, pynicotine/shares.py
This should fix the build issues. I'll do similar cleanups in the transfers.py file later, as there's some UI-related code that shouldn't be there.
=> Remove GLib import from non-GUI code

pynicotine/config.py
MediaDefender is defunct since 2009.
=> Remove MediaDefender bots from default block list

pynicotine/pynicotine.py
Set our custom log levels on startup, otherwise only messages in level 0 and 1 (defaults) will be logged until we modify our level list.
=> Set logging levels on startup

pynicotine/pynicotine.py, pynicotine/shares.py, pynicotine/slskmessages.py
This is a fix for a regression in https://github.com/Nicotine-Plus/nicotine-plus/commit/9b527ce709f7aa09eab9ba584dfce244e9fde973#diff-686974e33d233586bc64ec1e339db17b.
Before we started packing the file size as a long long (8 bytes), it seems like Nicotine+ sent the file size as an integer (4 bytes), and some dummy content (4 bytes) to take up the 8 bytes required by the protocol (slskmessages.py, line 2161). Since I didn't remove this dummy content, we now inserted 4 unwanted bytes between the file size and file extension.
The folder contents are also identical to the ones we saved while rescanning our shares, so use our cached data instead.
=> Don't include invalid data in folder contents response

pynicotine/gtkgui/frame.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/ui/settings/search.ui
Since GtkSpinButton inherits from GtkEntry, `isinstance(widget, Gtk.Entry)` would prematurely set the entry text of the spin button, but not the actual value. This caused an issue where the default value of a spin button would overwrite any custom values when closing the settings window.
=> Fix GtkSpinButton inheritance issue

nicotine, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/userbrowse.py, pynicotine/shares.py, pynicotine/upnp.py, pynicotine/utils.py
There were two cases where Nicotine+ incorrectly attempted to use the XDG dirs on Windows.
=> Always use correct data directory on Windows

pynicotine/gtkgui/settingswindow.py, pynicotine/shares.py
Let's say we have shared and scanned a bunch of normal folders. If we then enable buddy shares without modifying the folders, the buddy share list will be empty, even though it should contain the normal shares too. Make sure buddy shares are automatically rescanned if they are enabled.
Also prevent compressing shares if not necessary.
=> Always rescan buddy shares when enabling them

pynicotine/gtkgui/ui/about/about.ui
The license should be GPL-3.0-or-later, not GPL-3.0-only.
=> about.ui: use correct license

AUTHORS.md, README.md, pynicotine/gtkgui/ui/about/about.ui
Since Nicotine was based on PySoulSeek, I feel it would be a kind gesture to also credit the people who made PySoulSeek possible. The author list is taken from PySoulSeek 1.2.4, the last version Nicotine used code from.
=> AUTHORS.md: add PySoulSeek authors

.gitignore, debian/control, doc/PACKAGING.md, doc/RUNFROMGIT.md, files/macos/dependencies.sh, files/windows/dependencies.sh, requirements.txt, setup.cfg, setup.py
The only reason I opted to use setuptools previously was due to `find_packages`. However, the `single-version-externally-managed` option, which we need to install files to the correct folders on the system, has caused a lot of pain so far, as it's not recognized by pip. Drop the setuptools dependency in favor of distutils, and use our own method of finding the correct packages and package data.
Pretty sure the introduction of setuptools also causes an issue where Nicotine+ is installed to /usr/lib/python3.X/dist-packages instead of /usr/lib/python3/dist-packages.
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/531
=> Drop setuptools dependency

debian/control
This seems to be the way to go to install Nicotine+ to the more generic /usr/lib/python3/dist-packages folder, instead of /usr/lib/python3.X/dist-packages. We want to avoid installing files to a minor version folder, as it breaks our deb packages on Debian installations if the minor Python 3 version doesn't match, and almost every other Python-based package doesn't install its files here.
=> Debian: install to /usr/lib/python3/dist-packages

README.md
Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/530
Stable builds currently don't work on Debian when installing from the PPA, but this will be solved when we release 2.1.2 (thanks to https://github.com/Nicotine-Plus/nicotine-plus/pull/719).
=> Updated Debian instructions

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/settingswindow.py
A spell checker object seems to take up quite a lot of memory, so reuse it across chats instead of creating new ones.
master branch: 200MB memory usage after joining 20 rooms
this PR: 62MB memory usage after joining 20 rooms
=> Reuse spell checker object for every chat

debian/control, doc/DEPENDENCIES.md, files/macos/dependencies.sh, pynicotine/config.py, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/notifications.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/settingswindow.py, pynicotine/transfers.py, setup.cfg
This seems to be the logical step going forward, see https://developer.gnome.org/GNotification/.
As a side effect, we now support notifications on macOS. A Windows backend isn't present yet, but there's an open issue for it: https://gitlab.gnome.org/GNOME/glib/-/issues/1234
=> Migrate from libnotify to GNotification

pynicotine/config.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/ui/settings/icons.ui
The tray icon functionality is completely broken on macOS at the moment. The tray icon popup does not appear, and minimizing Nicotine+ to tray doesn't hide the icon from the dock.
I've opted to disable the tray icon on macOS, as it's not worth dealing with GtkStatusIcon, which is a deprecated mess removed in GTK4. macOS has some kind of "Hide" button when right-clicking a dock icon, which seems good enough.
=> Disable tray icon on macOS

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/utils.py
Reverts a minor change in https://github.com/Nicotine-Plus/nicotine-plus/pull/698. For some reason the "page" input variable is None...
Also removes on_focused leftover from detachable tabs.
=> Clear tray and title notifications properly

.github/workflows/packaging.yml, .github/workflows/tests.yml, doc/PACKAGING.md, files/macos/dependencies-core.sh, files/macos/dependencies-packaging.sh, files/windows/dependencies-core.sh, files/windows/dependencies-packaging.sh
Since we don't include GTK-related functions in the core, and our unit tests currently only cover the core, there's no need to waste bandwidth installing unnecessary dependencies. Packaging software is also not needed for tests.
=> Don't install unneeded dependencies for unit tests

pynicotine/config.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/settingswindow.py, pynicotine/pynicotine.py
What exactly this option does was unclear for me when I started using Nicotine+, and apparently others have had a similar experience. I don't see what kind of purpose it serves anymore, there's always the manual toggle to disable sending of search results if you really need it.
=> Remove option to stop responding to searches for a certain time

files/windows/nicotine.spec, pynicotine/gtkgui/settingswindow.py, pynicotine/pluginsystem.py
- Attempt to load plugins by module name when possible, since the __init__.py files are not included in Windows and macOS builds. Include plugin modules in these builds. Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/761
- Ensure that the setting key for a plugin matches the plugin folder name (use the folder name directly instead of converting the plugin name to lowercase). Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/762, fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/763
- Remove unnecessary macOS notification code from .spec file
=> Improve plugin loading and setting detection

pynicotine/gtkgui/chatrooms.py, pynicotine/slskmessages.py
This allows us to get more search results from Soulseek NS users, and reduces the number of download errors from these clients.
=> Attempt to send latin-1 encoded strings, fall back to utf-8

pynicotine/pynicotine.py, pynicotine/shares.py
We previously had a check for this that was lost after the shares refactor.
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/768
=> Don't send number of shared files if not connected

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/tray.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userinfo.py, pynicotine/gtkgui/userlist.py, pynicotine/gtkgui/utils.py, pynicotine/pynicotine.py
- If we aren't able to connect to a user for some reason, Nicotine+ would not open the user browse and info pages at all, giving the impression that buttons/items to open these pages didn't work. Always open these pages instead, and let them update if we receive any data from the user.
- If the user browse tab was hidden, and we requested to see a user browse, Nicotine+ would make the user info tab visible instead.
- Cleanups, reduce code duplication
=> Improvements to user browse and info

pynicotine/gtkgui/frame.py, pynicotine/gtkgui/tray.py
This was already done in the menu bar, but not the tray menu.
=> Tray: disable server actions when disconnected

pynicotine/gtkgui/dirchooser.py, pynicotine/gtkgui/userinfo.py
Makes more sense to allow the user to save pictures to specific folders, rather than dumping them to the downloads directory with minimal feedback given.
=> Show file chooser dialog when saving user pictures

pynicotine/gtkgui/frame.py, pynicotine/gtkgui/notifications.py, pynicotine/gtkgui/tray.py, pynicotine/gtkgui/ui/menus/menubar.ui
- Mirror the appearance of the away item in the menu bar and tray
- Check/uncheck the checkbox if the away mode changes
- Code cleanup
=> Keep away mode checkbox in sync with away status

doc/SLSKPROTOCOL.md, pynicotine/pynicotine.py, pynicotine/slskmessages.py, pynicotine/slskproto.py
The "Can't create room" server message code was added to PySoulSeek in 2003. It seems like it hasn't been used on the server in a very long time, as the server now sends a private message if a room can't be created, but it seems to belong to the special server error codes (1000-range).
=> Add documentation for 'can't create room' server message

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/ui/buddylist.ui, pynicotine/gtkgui/ui/chatrooms.ui, pynicotine/gtkgui/ui/mainwindow.ui, pynicotine/gtkgui/ui/search.ui, pynicotine/gtkgui/ui/userbrowse.ui, pynicotine/gtkgui/ui/userinfo.ui, pynicotine/gtkgui/userbrowse.py
- Add badges behind numbers (number of chatroom users, downloads/uploads, shared files, search results)
- Make quick settings buttons rounded
- Move "save shares list to disk" option to popup menu
- Minor spacing tweak
=> UI refresh (part 2)

pynicotine/gtkgui/search.py, pynicotine/gtkgui/utils.py
There hilite icon still takes up some space in the tab when no image is set, so hide it.
=> Hide hilite image if empty

pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/uploads.py, pynicotine/gtkgui/userbrowse.py
- Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/790 (regression from the last major refactoring)
- Don't collapse the download/upload treeview whenever a transfer is updated
=> Recursive download fix

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/notifications.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/transferlist.py, pynicotine/gtkgui/tray.py, pynicotine/gtkgui/uploads.py, pynicotine/gtkgui/userinfo.py, pynicotine/gtkgui/utils.py, pynicotine/pynicotine.py
- Consolidate duplicate efforts for changing tab hilite icons into one function, "request_tab_icon"
- Remove Nicotine+ version number from window title. It takes up space and is not relevant information for everyday use.
- Don't modify window icon when new messages arrive, as this change is not guaranteed to work across desktop environments. Rely on other notification methods instead, such as window urgency, tray icon, notification bubbles and window title notifications.
- Code cleanups
=> Notification and window improvements

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/interests.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/roomlist.py, pynicotine/gtkgui/roomwall.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/transferlist.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userinfo.py, pynicotine/gtkgui/userlist.py, pynicotine/gtkgui/utils.py, pynicotine/gtkgui/wishlist.py
- Automatically detect widgets that need to be modified instead of hard-coding them. This will make it much easier to expand the theming system in the future if we want to.
- Remove duplicate functions
- Rename incorrect and confusing function names
- Get rid of cell data functions for modifying treeview colors. These were somewhat resource-intensive and completely redundant, as the colors were already modified by other means.
- Move away from deprecated GTK apis, use CSS instead
- Fix minor issue where hilite icons weren't always visible
=> Refactor code related to widget colors and fonts

pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/transferlist.py, pynicotine/gtkgui/uploads.py
This is what the code removed in https://github.com/Nicotine-Plus/nicotine-plus/pull/793 was intended to do, to expand only the user of a newly added transfer instead of all users.
=> Show folders when transfer is added in collapsed group by folder-mode

pynicotine/gtkgui/frame.py, pynicotine/shares.py
Although using a thread to compress shares reduces startup times a lot, it's still blocking program startup slightly if you are sharing a lot of files. Add a two second cooldown before rescanning/compressing shares to let the rest of the program start without delay.
Also stop compressing shares if rescan on startup is enabled, otherwise we do it twice.
=> Add slight cooldown before rescanning/compressing shares on startup

pynicotine/gtkgui/utils.py
Removes the need for the inheritance rules, as there are no previous conflicting CSS providers.
=> Reuse previous CSS providers

pynicotine/pynicotine.py
The IP address of the user isn't guaranteed to exist in our peerconns list at this stage.
=> FolderContentsRequest: extract IP from peer message

pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/transferlist.py, pynicotine/gtkgui/uploads.py, pynicotine/gtkgui/userinfo.py, pynicotine/transfers.py
- Remove redundant "Abort & Delete" item, it works the same way as "Clear"
- Abort queued transfers before removing them
- Fix recursion error when clicking abort upload button
=> Fix a few minor issues related to transfer view

pynicotine/pynicotine.py
Private messages sent directly from a peer to another (nic+ specific feature) would not appear, since status is no longer a valid parameter.
=> Fix direct private messages not appearing

pynicotine/config.py, pynicotine/gtkgui/fastconfigure.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/ui/fastconfigure.ui, pynicotine/gtkgui/ui/settings/server.ui, pynicotine/gtkgui/uploads.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/utils.py, pynicotine/pynicotine.py, pynicotine/shares.py, pynicotine/slskmessages.py, pynicotine/transfers.py
I'm going to propose these changes for master now, to hopefully receive wider testing and detect potential issues. Testing has looked promising so far however.
- Remove "I can receive direct connections" option, which made Nicotine+ only initialize indirect connections to other peers. Instead, we always attempt a direct connection to the peer first, and fall back to indirect ones in case of failure.
- Don't create multiple PeerConnection objects for a single user, if we attempt to send multiple messages before the connection has been established. Instead, add subsequent messages to the existing connection object.
Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/663
=> Corrections to peer connection logic

pynicotine/utils.py
I stumbled upon a few search results that contained file attributes with values of 0. Make sure we handle these correctly.
=> get_result_bitrate_length: avoid division by zero

pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userinfo.py, pynicotine/pynicotine.py, pynicotine/slskmessages.py, pynicotine/slskproto.py, pynicotine/transfers.py
- When searching files, avoid closing peer connections if a file connection is in progress for the same user
- Let peer connections time out instead of forcibly closing them when closing user browse/info tabs
- In cases where we remove a connection on the UI side, and also request the network thread to remove the connection, there's no need for the network thread to call back to the UI again
- Performance improvement for detecting parent connections
=> Minor connection improvements

pynicotine/gtkgui/frame.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/userinfo.py, pynicotine/gtkgui/utils.py
When disconnecting from the server, tabs would display status text even though the option was disabled.
=> Only display tab status text when option is enabled

pynicotine/gtkgui/ui/menus/menubar.ui
`Alt` should not be used in shortcuts, otherwise conflicts with accelerator keys will most likely occur. In Nicotine+, an example of this is the Alt+S shortcut for the preferences window, which currently opens the Shares menu instead.
I've tried to choose shortcuts that aren't reserved by the system or have a different meaning in a majority of other programs. Here's the list:
- Shift+Ctrl+C: connect
- Shift+Ctrl+D: disconnect
- Ctrl+H: away
- Ctrl+P: preferences
- Ctrl+Q: quit
- Ctrl+L: show log window
- Ctrl+R: show room list
- Ctrl+U: show flag columns in user lists
- Ctrl+B: show buttons in transfer tabs
- Shift+Ctrl+P: rescan public shares
- Shift+Ctrl+B: rescan buddy shares
=> Replace old keyboard shortcuts with non-conflicting ones

pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/transferlist.py, pynicotine/gtkgui/uploads.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userinfo.py
It seems like this was the intention from the beginning, but never worked/stopped working. Also fixes an issue where self.current_tab wouldn't point at a tab label until changing tabs, which made hilite icons appear on notebook tabs when not supposed to.
Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/651
=> Automatically open user tab when requesting info/share

pynicotine/gtkgui/frame.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userinfo.py, pynicotine/pynicotine.py, pynicotine/shares.py
- When browsing our own shared files, parse the file list in a new thread instead of blocking the UI
- Parse our pre-built, compressed share list instead of rebuilding it, to save memory and speed up the process a bit
- On startup, immediately create the message for holding our compressed shares list, otherwise browsing our shares could trigger an exception between the time the program has started and the shares list has been fully compressed
=> Parse local shares list in a new thread

pynicotine/gtkgui/frame.py, pynicotine/gtkgui/tray.py
On Windows, it seems like the tray icon doesn't disappear until you move the cursor over the tray area. Hiding the tray icon before quitting Nicotine+ fixes this.
=> Explicitly hide tray icon before exiting Nicotine+

pynicotine/slskproto.py
I'm quite sure this code was originally supposed to check if a socket has any data available. However, the code essentially did nothing due to reading 0 bytes, letting firewalled connections through, and skipping any attempts of initializing indirect connections in the process (leading to "Cannot connect" errors for uploads, even though your port is open).
Actually attempting to read some data from the socket, and not consuming the data yet (MSG_PEEK), seems to have the intended effect.
=> Properly check if socket has data available

pynicotine/config.py, pynicotine/gtkgui/frame.py, pynicotine/pynicotine.py, pynicotine/utils.py
Adds stricter, less hard-coded checks for config file values, to make it harder for someone to break Nicotine+ by messing with the config file. If the type of a custom value differs from the default one, the value is reverted.
=> Stricter type checking for config items

pynicotine/gtkgui/fastconfigure.py, pynicotine/gtkgui/ui/fastconfigure.ui, pynicotine/gtkgui/ui/settings/server.ui, pynicotine/upnp/portmapper.py, pynicotine/upnp/ssdp.py, pynicotine/upnp/upnp.py
- Some minor changes to improve UPnP compatibility with different routers
- Add more debug logging for UPnP
- Remove port spinbuttons from fast configure assistant. There isn't a good way to change the port and UPnP mapping at this point (requires restart), and changing the port should only be necessary in special cases anyway. The port can be changed in the preferences if necessary.
- Remove WAN port checker from UPnP code. Having a different WAN port from LAN port doesn't make sense, as the server is only aware of the LAN port.
=> UPnP: minor corrections 

pynicotine/gtkgui/userinfo.py
Fix for the following traceback:
```
Traceback (most recent call last):
File "/home/default/Documents/nicotine-plus/pynicotine/gtkgui/frame.py", line 1743, in on_get_user_info
self.local_user_info_request(text)
File "/home/default/Documents/nicotine-plus/pynicotine/gtkgui/frame.py", line 1780, in local_user_info_request
self.userinfo.show_user(user, msg=msg)
File "/home/default/Documents/nicotine-plus/pynicotine/gtkgui/userinfo.py", line 92, in show_user
self.users[user].show_user(msg, indeterminate_progress)
TypeError: show_user() takes 2 positional arguments but 3 were given
```
=> show_user: add missing parameter

NEWS.md, debian/control, doc/DEPENDENCIES.md, files/macos/dependencies-core.sh, files/windows/dependencies-core.sh, files/windows/dependencies-packaging.sh, nicotine, pynicotine/gtkgui/ui/about/about.ui, pynicotine/metadata/tinytag.py, pynicotine/shares.py, requirements.txt, setup.cfg
As it turns out, the pytaglib dependency has caused more issues than originally anticipated, see:
- https://github.com/Nicotine-Plus/nicotine-plus/issues/843
- https://github.com/Nicotine-Plus/nicotine-plus/issues/798
- https://github.com/Nicotine-Plus/nicotine-plus/issues/730
- https://tracker.debian.org/pkg/pytaglib (extremely outdated version)
- https://bugs.gentoo.org/750425#c1
Installing pytaglib on less common systems is somewhat painful for a regular user. To make it easier to run Nicotine+, I've opted to use a slightly modified version of the tinytag library (https://github.com/devsnd/tinytag). This library focuses on metadata reading only, is actively maintained, and the code is pure Python and fairly short, which is perfect for our needs. From my testing, the library also seems …
=> Use tinytag for metadata scanning

pynicotine/metadata/tinytag.py, pynicotine/pynicotine.py, pynicotine/shares.py
Since we need to be able to scan massive libraries of music in a short amount of time, and our usage of the tinytag library is very specific and predictable, we can take a few shortcuts in the code and shave off some time from the scanning process.
=> Optimize tinytag to better suit our needs

debian/control, doc/DEPENDENCIES.md, pynicotine/nowplaying.py, pynicotine/plugins/now_playing_sender/__init__.py, setup.cfg
GDBus seems to be the recommended alternative for interacting with dbus nowadays, and we eliminate yet another dependency.
=> Now Playing: port to GDBus

pynicotine/config.py, pynicotine/gtkgui/settingswindow.py
Like the title says, drop the current behavior of creating a timestamped backup when pressing "Cancel", as this goes against expectations.
=> When backing up config, make 'Cancel' button actually cancel the action

README.md, TRANSLATORS.md, _config.yml, doc/DEPENDENCIES.md, doc/PACKAGING.md, doc/RUNFROMGIT.md, doc/TRANSLATIONS.md, files/screenshots/SCREENSHOTS.md, pynicotine/gtkgui/ui/about/about.ui
I much prefer the element styling and spacing of the default Primer theme (which mirrors the README style on GitHub) compared to the Minimal theme. I've also fixed some consistency issues across our Markdown files, and removed the $ sign from command examples, since it made it more difficult to copy commands.
Preview: https://mathiascode.github.io/nicotine-plus/
=> Use default theme for GitHub pages

pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/ui/mainwindow.ui, pynicotine/pynicotine.py, pynicotine/slskmessages.py, pynicotine/slskproto.py, pynicotine/transfers.py, test/unit/test_login.py
This PR is the result of several days of debugging connectivity and transfer issues (many thanks to @alekksander for helping me test).
Some of the changes include:
- Properly close and clean up peer connections immediately after disconnecting from the server. Thanks to this, SoulseekQt clients are informed about us logging out, and the files they're downloading from the Nicotine+ client won't be permanently stuck on queued after we log in again.
- Don't attempt to send any QueueFailed messages after disconnecting from the server.
- Avoid adding two PeerConnection objects for a user, if we receive a direct and indirect connection attempt at the same time. This fixes issues where uploads would be stuck on "Cannot connect" due to messages being sent on the previous, obsolete connection, and …
=> Bug fixes for peer connections and transfers (part 1)

doc/SLSKPROTOCOL.md, pynicotine/gtkgui/transferlist.py, pynicotine/pynicotine.py, pynicotine/slskmessages.py, pynicotine/slskproto.py
- If a connection to a peer is already established, ensure indirect connection attempts from the peer can't override the active connection.
- Stop sending CantConnectToPeer messages to users, if they send us an indirect connection request, and we can't connect to their port. We can no longer be sure that the peer has actually finished an attempt at connecting to us directly before sending us the indirect connection request, as the official client attempts both connection methods simultaneously nowadays.
- Slightly reduce timeout period for connections
- Ensure percentage bar for transfers can never exceed 100%
=> Bug fixes for peer connections and transfers (part 2)

debian/control, doc/DEPENDENCIES.md, files/macos/dependencies-packaging.sh, setup.cfg
Turns out the gobject-introspection package only contains tools we don't need. python3-gobject/python3-gi has everything needed to run Nicotine+.
=> Remove unneeded gobject-introspection dependency

pynicotine/pynicotine.py, pynicotine/slskmessages.py, pynicotine/transfers.py
The timer that checks if downloads are stuck currently runs in a separate thread. When a new download attempt is made, the UI is updated directly from this thread. This can sometimes result in a crash, as GTK is not thread safe.
Run the check_download_queue function in the main thread instead, to prevent this issue.
(Partial?) solution for https://github.com/Nicotine-Plus/nicotine-plus/issues/882
=> Check stuck downloads in the main thread

pynicotine/gtkgui/dialogs.py, pynicotine/gtkgui/tray.py, pynicotine/gtkgui/utils.py
Entry dialogs previously required you to press the "OK" button to finish them, which was very frustrating at times.
=> Allow completing entry dialogs by pressing enter

debian/control, doc/DEPENDENCIES.md, nicotine, pynicotine/shares.py
Even though gdbm should be preinstalled on most systems, I don't want to receive bug reports about slow file scanning due to falling back to dumbdbm.
=> Ensure either gdbm or semidbm is installed

pynicotine/shares.py, test/unit/shares/test_shares.py
As the title says, we previously stopped scanning a folder once a hidden folder was detected inside it, resulting in some regular folders not being added to our collection.
=> Continue scanning folder after hidden subfolder was detected

pynicotine/gtkgui/frame.py, pynicotine/utils.py
- Remove Windows-specific code for translations. It's no longer needed after the port to GTK3/Python 3.
- Show menu bar translations in UI
Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/893
=> Simplify translation-related code

doc/SLSKPROTOCOL.md, pynicotine/pynicotine.py
Sending the version number of Soulseek NS to the server isn't really fair, as the server has no way of easily identifying Nicotine+ clients. I'm also not convinced that Soulseek NS won't be blocked from accessing the server in the future.
The major version is 157 in both SoulseekQt and Soulseek NS, only the minor version has changed. Therefore, it should be safe to pick 160 as the version number for Nicotine+. Version 179+ doesn't receive search requests via the server, likely due to this long-standing bug in Museek+: https://github.com/eLvErDe/museek-plus/issues/5
=> Send custom version number to server instead of Soulseek NS's

pynicotine/shares.py, pynicotine/slskmessages.py
The current exception handling in shares.py doesn't work, as a few metadata objects will already be packed before the exception is thrown. This creates an invalid folder stream.
=> Fix error in exception handling when invalid audio metadata is found

pynicotine/gtkgui/frame.py, pynicotine/gtkgui/ui/about/about.ui, pynicotine/gtkgui/ui/about/chatroomcommands.ui, pynicotine/gtkgui/ui/about/privatechatcommands.ui, pynicotine/gtkgui/ui/about/searchfilters.ui, pynicotine/gtkgui/ui/buddylist.ui, pynicotine/gtkgui/ui/chatrooms.ui, pynicotine/gtkgui/ui/fastconfigure.ui, pynicotine/gtkgui/ui/fileproperties.ui, pynicotine/gtkgui/ui/interests.ui, pynicotine/gtkgui/ui/mainwindow.ui, pynicotine/gtkgui/ui/privatechat.ui, pynicotine/gtkgui/ui/roomlist.ui, pynicotine/gtkgui/ui/roomwall.ui, pynicotine/gtkgui/ui/search.ui, pynicotine/gtkgui/ui/settings/settingswindow.ui, pynicotine/gtkgui/ui/userbrowse.ui, pynicotine/gtkgui/ui/userinfo.ui, pynicotine/gtkgui/ui/wishlist.ui, pynicotine/gtkgui/utils.py
While we won't be able to switch to GTK 4 for a few years, it's a good idea to do whatever we can right now to make the process easier.
This PR takes care of https://developer.gnome.org/gtk4/stable/gtk-migrating-3-to-4.html#id-1.7.4.3.11 for everything except the preferences window, and also changes a few properties removed in GTK 4 to ones supported in both GTK 3 and GTK 4. The files have been partially edited by hand, and simplified using `gtk-builder-tool simplify x.ui > y.ui`.
Checklist:
=> UI file preparations for GTK 4 (part 1)

pynicotine/config.py, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/interests.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/transferlist.py, pynicotine/gtkgui/ui/userbrowse.ui, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userinfo.py, pynicotine/gtkgui/userlist.py, pynicotine/gtkgui/utils.py, pynicotine/gtkgui/wishlist.py, pynicotine/shares.py
This PR includes a refactored column visibility/width saving system, which also takes column positions into consideration. Its more readable, extendable and maintainable than the previous one, and also much less error prone, using non-numerical IDs for columns instead of relying on indices. This will allow us to effortlessly modify and add columns in the future.
Custom column widths and visibility will not be converted from the old system. Not sure if it's worth the effort.
=> Refactor column width/visibility saving, allow column reordering

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/fastconfigure.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/interests.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/transferlist.py, pynicotine/gtkgui/tray.py, pynicotine/gtkgui/uploads.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userinfo.py, pynicotine/gtkgui/userlist.py, pynicotine/gtkgui/utils.py
Over the years, Nicotine+ has accumulated nine pieces of duplicated code for creating a user context menu, resulting in a maintenance nightmare. Refactor the code to create a base user menu that can be extended for certain pages, and eliminate index-based modifications for context menu items, as this has caused a lot of pain when adding or removing items from menus.
=> Refactor code related to popup/context menus

.github/workflows/packaging.yml, packaging/macos/dependencies-packaging.sh, packaging/macos/entitlements.plist
Ad-hoc sign our macOS builds in preparation for the day we're able to generate [universal binaries](https://developer.apple.com/documentation/xcode/building_a_universal_macos_binary).
> New in macOS 11 on Macs with Apple silicon, and starting in macOS Big Sur 11 beta 6, the operating system enforces that any executable must be signed before it’s allowed to run. There isn’t a specific identity requirement for this signature: a simple ad-hoc signature is sufficient. This new behavior doesn’t change the long-established policy that our users and developers can run arbitrary code on their Macs, and is designed to simplify the execution policies on Macs with Apple silicon and enable the system to better detect code modifications. This new policy doesn’t apply to translated x86 binaries running …
=> macOS build: ad-hoc signing

pynicotine/gtkgui/ui/settings/away.ui, pynicotine/gtkgui/ui/settings/log.ui, pynicotine/gtkgui/ui/settings/search.ui, pynicotine/gtkgui/ui/settings/server.ui, pynicotine/gtkgui/ui/settings/shares.ui, pynicotine/gtkgui/ui/settings/uploads.ui
Some additional Preferences tweaks: Changed a couple spacings between texts and UI elements, removed an erroneous tooltip, aligned a label, and reordered "Add, Remove, Rename" buttons to the more logical "Add, Rename, Remove". Tested and working.
=> Additional Preferences UI layout and strings tweaks

pynicotine/gtkgui/ui/dialogs/searchfilters.ui, pynicotine/gtkgui/ui/menus/mainmenu.ui, pynicotine/gtkgui/ui/menus/menubar.ui, pynicotine/gtkgui/ui/search.ui, pynicotine/gtkgui/ui/settings/search.ui
Attempted to improve clarity of the filters' purpose by renaming Search Filters to Result Filters. Also tried to reword parts of the help file on the topic. Think I replaced all the strings referencing "search filters" that affect the UI. Open to feedback.
=> Rename "Search Filters" to "Search Result Filters" and improve help

debian/changelog, packaging/windows/nicotine.nsi, pynicotine/utils.py
Due to the number of user-facing changes and GUI code refactors since 2.2.2, I propose increasing the major version.
=> Bump version number to 3.0.0-dev1

.github/workflows/tests.yml, .gitignore, packaging/windows/dependencies-core.sh, pynicotine/gtkgui/frame.py, pynicotine/utils.py, test/unit/test_version.py
Now that Nicotine+ is available on PyPi, it seems like a more reliable source for checking the latest Nicotine+ version long-term wise.
=> Use PyPi for version checker instead of GitHub

.github/workflows/packaging.yml, .github/workflows/tests.yml, debian/control, debian/copyright, debian/rules, debian/watch, doc/DEVELOPING.md, doc/PACKAGING.md, packaging/windows/dependencies-core.sh
- Remove the "get-orig-source" target, as it is deprecated. Add updated commands to PACKAGING.md utilizing Python's sdist and "mk-origtargz" from devscripts. https://wiki.debian.org/onlyjob/get-orig-source
- Add Debian packaging workflow to GitHub Actions, to allow for easier inspection of logs and built packages.
- Remove old "parallel" build option. This seems to be from a time when we used to ship .png files, nowadays it doesn't seem to make a noticeable difference.
@kiplingw Since you are the author of a large part of the "Debianization", and have more experience with this process, I would appreciate your feedback on these changes.
=> Debian: remove deprecated get-orig-source target

pynicotine/config.py, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/utils.py, pynicotine/transfers.py
Stop using pickles in favor of a sensible, readable and safe format, like json.
=> Replace usage of pickle with json

pynicotine/gtkgui/ui/popovers/searchfilters.ui
~~If you can, double-check that the XML is correct as I am unable to build on Windows currently.~~
The pull request just adds mention of `?ib` and `?b` unit variants for File Size suffixes, and updates the formatting slightly.
**Edit:** I forgot that CI runs on a pull request; I should be able to check if the formatting didn't break.
=> Update result filter's help text

nicotine, pynicotine/config.py, pynicotine/gtkgui/frame.py, pynicotine/pynicotine.py, pynicotine/shares.py, pynicotine/slskmessages.py, pynicotine/transfers.py, test/unit/shares/test_shares.py
This PR decouples file scanning and share db generation from the main Nicotine+ process, which results in significantly increased UI performance while scanning.
=> Move scanning of shared files to a separate process

pynicotine/gtkgui/ui/popovers/searchfilters.ui
128 kibibytes would equal a mebibit, not a mebibyte (1024 KiB).
=> Correct kibibyte string

doc/SLSKPROTOCOL.md, pynicotine/gtkgui/userbrowse.py, pynicotine/pynicotine.py, pynicotine/slskmessages.py, pynicotine/transfers.py
This PR reworks download queuing to send QueueUpload messages instead of TransferRequest, which has been deprecated for at least 13 years. See https://github.com/eLvErDe/museek-plus/commit/285a4a4a6292a93208443df6b713ae0076e11431#diff-e106f5596240e8c28bc4fbd5afd8ce4a9b807e4065c91b2b6fb32194dfdba1f2R197-R199
SoulseekQt, Soulseek NS and Museek+ have been sending QueueUpload messages for many years now, and Nicotine+ has accepted such requests for a long time as well.
=> Don't use deprecated method of queuing downloads

pynicotine/gtkgui/ui/interests.ui
When typing in the recommendations and unrecommendations treeviews in the interests tab, the quicksearch will search in the score column. With this change it'll search in the actual item column.
=> Set correct search column for interests (un)recommendations treeviews

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/utils.py, pynicotine/logfacility.py, pynicotine/pynicotine.py, pynicotine/transfers.py, pynicotine/utils.py
- Rework our path handling to strip out illegal characters for NTFS and FAT drives, instead of hardcoding this behavior for Windows.
- Remove some old code from the PySoulSeek days related to incomplete downloads.
Fixes #1019
=> Fix invalid path character issues on NTFS/FAT drives

doc/SLSKPROTOCOL.md
I discovered this by mistake while inspecting the behavior of `CannotConnect` (see: [Soulseek.Net #517](https://github.com/jpdillingham/Soulseek.NET/issues/517))
=> Add note about SetWaitPort/2

packaging/flatpak/org.nicotine_plus.Nicotine.yaml
Tested it, seems to work fine.
=> Bump Flatpak runtime version to GNOME 40 

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/fastconfigure.py, pynicotine/gtkgui/fileproperties.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/roomwall.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/statistics.py, pynicotine/gtkgui/transferlist.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userinfo.py, pynicotine/gtkgui/userlist.py, pynicotine/gtkgui/widgets/filechooser.py, pynicotine/gtkgui/widgets/iconnotebook.py, pynicotine/gtkgui/widgets/messagedialogs.py, pynicotine/gtkgui/widgets/popupmenu.py, pynicotine/gtkgui/widgets/trayicon.py, pynicotine/gtkgui/wishlist.py
GtkDialog.run() has been removed in GTK 4. Replace it with GtkDialog.show() and the "response" signal.
See https://developer.gnome.org/gtk4/stable/ch41s02.html#id-1.7.4.4.81
=> Stop using blocking dialog functions in preparation for GTK 4

NEWS.md, pynicotine/gtkgui/widgets/iconnotebook.py
When unread tab notifications exist, a button displaying a dropdown menu of unread pages appears in the tab bar.
=> Add dropdown button for unread tabs

nicotine, pynicotine/gtkgui/frame.py, pynicotine/shares.py
- Use the argparse module from the stdlib to simplify our command line argument parsing
- Modify our exit code handling to fall in line with other popular Python programs
=> Use argparse module to parse command line arguments

.github/workflows/packaging.yml, .gitignore, packaging/flatpak/disable-gspell-vapigen.patch, packaging/flatpak/org.nicotine_plus.Nicotine.yaml
- Use Freedesktop runtime instead of GNOME runtime, since we use few GNOME dependencies
- Use source archives instead of repos, since the former downloads faster
=> Flatpak: Use Freedesktop runtime instead of GNOME runtime

.github/workflows/packaging.yml, packaging/windows/dependencies-packaging.sh
This combination seems to yield the smallest number of false positives.
Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/1373
=> PyInstaller: rebuild bootloader on WS2016 to reduce false positives

pynicotine/config.py, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/notifications.py, pynicotine/gtkgui/roomlist.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/ui/mainwindow.ui, pynicotine/gtkgui/utils.py, pynicotine/gtkgui/widgets/trayicon.py, pynicotine/gtkgui/wishlist.py, pynicotine/logfacility.py, pynicotine/nowplaying.py, pynicotine/pynicotine.py, pynicotine/shares.py, pynicotine/slskmessages.py, pynicotine/slskproto.py, pynicotine/transfers.py, pynicotine/upnp/portmapper.py, pynicotine/utils.py
- Add new log categories for downloads, uploads and chats. Disable download log output by default.
- Remove `Warnings` log category, log all non-debug messages in the terminal. These messages contain important information, and should not be disabled.
Fixes #1371
=> Add debug log categories for downloads, uploads and chats

.github/workflows/tests.yml, debian/control, doc/DEPENDENCIES.md, doc/DEVELOPING.md, nicotine, setup.py
Python 3.5 reached EOL last year, and support for Ubuntu 16.04 has also ended. While Debian 9 LTS still uses Python 3.5, I feel it's time to start encouraging users to upgrade. This initial step will be used to verify whether a substantial number of users still want support for this Python version or not. If not, we can start introducing Python 3.6 features into the code base, if desired.
=> Remove Python 3.5 from list of supported versions

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/fastconfigure.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/interests.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/roomlist.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/transferlist.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userinfo.py, pynicotine/gtkgui/userlist.py, pynicotine/gtkgui/utils.py, pynicotine/gtkgui/widgets/iconnotebook.py, pynicotine/gtkgui/widgets/popupmenu.py, pynicotine/gtkgui/widgets/treeview.py, pynicotine/gtkgui/wishlist.py
GTK 4 removed `button-press-event` and `touch-event`, which are currently used for our context menus. To prepare for this change, move as much context menu logic as possible into PopupMenu to make future changes easier, and replace `touch-event` with GtkGestureLongPress.
=> Refactor context menus to use GtkGesture when possible

.github/workflows/packaging.yml, .github/workflows/tests.yml, nicotine, packaging/macos/dependencies-core.sh, packaging/windows/dependencies-core.sh, pynicotine/gtkgui/frame.py
If you are testing the GTK 4 version of Nicotine+ on GNU/Linux or *BSD, you should now launch it using `NICOTINE_GTK_VERSION=4 nicotine` instead of `nicotine --gtk4-unstable`.
=> Run integration tests with GTK 4

pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/ui/privatechat.ui, pynicotine/slskmessages.py
The Nicotine+-exclusive PMessageUser peer message was added in https://github.com/Nicotine-Plus/nicotine-plus/commit/33a82ecdb3b9dffc533445e0e60a3852a2021018 back in 2007. In my opinion, this was a mistake, as we are not supposed to modify the Soulseek protocol.
Due to the small range of possible recipients for these kind of private messages, remove the option to send them from the GUI.
=> Deprecate PMessageUser peer message

doc/SLSKPROTOCOL.md, pynicotine/config.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/ui/settings/search.ui, pynicotine/slskmessages.py
For the sake of transparency, I've added the option to show privately shared/locked files from other clients in search results. Since this is a controversial Soulseek feature, these files will not appear in results unless explicitly enabled in the search preferences.
For more information, see: https://groups.google.com/g/soulseek-discussion/c/vAnknGtihxg/m/pU2ItYSMAQAJ
=> Add option to show locked/privately shared files in search results

pynicotine/gtkgui/settingswindow.py, pynicotine/pluginsystem.py
> As we can see above, the API is pretty straightforward. The only bit of magic involves the DEFAULT section which provides default values for all other sections. **Note also that keys in sections are case-insensitive and stored in lowercase**.
> ~ https://docs.python.org/3/library/configparser.html#quick-start
The default python config parser saves keys case insensitive - meaning plugins with a folder name like `MyPlugin` is saved as `myplugin`. When we read the config tho we used the key `MyPlugin` and thus thought the no plugin settings exist and overwrote them.
=> Fix settings for plugins with uppercase letters

po/nicotine.pot, pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/ui/settings/nowplaying.ui, pynicotine/nowplaying.py
Add `/now` integration for [Listenbrainz](http://listenbrainz.org/). 
Sadly I cannot test it myself as I cannot run N+ from source atm as outlined in [this comment](https://github.com/Nachtalb/more-upload-stats/issues/1#issuecomment-912893610). **If someone else could take over from here that'd be mighty fine.**
The main integration of getting the song should basically work tho as I have tested it in a small plugin I wrote: https://github.com/Nachtalb/listenbrainz_now/blob/3bc9a23dc7454f04c2d14bf935b7da263fe502a6/listenbrainz_now/__init__.py#L29-L51
I'd still like to contribute as much as possible ^_____^  As soon as I am able to test the stuff myself I'll flood you with PRs or something...
During the po update, I get the following error. As such, I can't update the locals myself. There …
=> Add Listenbrainz /now command integration

pynicotine/gtkgui/settingswindow.py
ATM with malformed PLGUININFO data the plugin will be loaded upon start. But if the name was missing it crashed upon opening the plugin list and if other data was missing it crashed upon clicking on the plugin.
=> Prevent crashing with malformed or missing PLUGININFO data

pynicotine/pluginsystem.py
Remove some debug items from standard log, and change to Load / Unload terminology, because Enabled / Disabled was ambiguous (especially at shutdown).
=> Improve logging for pluginsystem

pynicotine/pynicotine.py
- closed_connection [Conn] log message was garbled log output spanning multiple lines making the [Conn] log unreadable.
_With this commit it now prints:_
`17:04:46 [Conn] Connection of type P to user Username closed by peer ('12.34.56.78', 12345)`
- connect_to_peer_direct [Conn] log message changed wording because it's too soon to know if successful init will be possible or not. Also added IP address because it's inexpensive and useful here. _With this commit it now prints:_
`17:06:16 [Conn] Attempting direct connection of type P to user Username ('12.34.56.78', 12345)`
=> Fix log [Conn] Connection closed by peer (user)

pynicotine/gtkgui/frame.py
... even when the Log Pane is visible (otherwise, this is just wasted space that could be better used).
=> Status bar always shows text

pynicotine/plugins/anti_shout/__init__.py, pynicotine/plugins/examplars/memory_debugger/__init__.py, pynicotine/plugins/examplars/port_checker/__init__.py, pynicotine/plugins/examplars/preferences/choices.py, pynicotine/plugins/examplars/preferences/filechooser.py, pynicotine/plugins/leech_detector/__init__.py, pynicotine/plugins/multipaste/__init__.py, pynicotine/plugins/now_playing_search/__init__.py, pynicotine/plugins/now_playing_sender/__init__.py, pynicotine/plugins/plugin_debugger/__init__.py, pynicotine/plugins/reddit/__init__.py, pynicotine/plugins/spamfilter/__init__.py, pynicotine/plugins/testreplier/__init__.py, pynicotine/plugins/youtube_info/__init__.py, pynicotine/pluginsystem.py
- Remove the `__name__` BasePlugin class attribute. Automatically set `internal_name` (plugin folder name) and `human_name` (human-readable name) attributes when the plugin loads.
- Remove arguments from BasePlugin's `__init__` function, allow plugins to safely use this function if they want. Avoids Pylint's "attribute-defined-outside-init" warning.
- Add new notifications:
- `loaded_notification`: plugin has finished loading (settings are loaded)
- `unloaded_notification`: plugin has finished unloading
- Allow unified commands (for both public and private chats) to be defined in the `__commands__` attribute. `__publiccommands__` and `__privatecommands__` can still be used if unified commands aren't desired.
All changes in this PR are backwards compatible.
=> Various improvements to plugin system

pynicotine/gtkgui/ui/popovers/wishlist.ui, pynicotine/gtkgui/wishlist.py
... also fixed UI bugs:
- Fixed: Items starting with `"(Wish) "` appear in the TextEntry when opening the Wishlist popover.
- Fixed: Irrelevant listitem selected after deleting an item.
- Fixed: Incorrect listitem selected after renaming an item.
- Fixed: Incorrect or none highlighted listitem when adding a new Wish.
- Fixed: Existing wish not highlighted if it's (Wish) tab is open.
- Fixed: Shift+Tab key navigation trapped on column header when moving focus between widgets. 
...
...and in wishlist.ui minor UI bugs and accessibility improvements:
- Added: ToolTop for Shift+Delete on the Remove Wish button.
- Fixed: Resolved mnemonic conflict with _Result Filters that meant shortcut had to be pressed twice to Remove item.
- Changed: Duplicate icon used for both buttons, changed to match …
=> Wishlist: Add Shift+Delete shortcut and Keyboard Accessibility Improvements

pynicotine/plugins/leech_detector/PLUGININFO, pynicotine/plugins/leech_detector/__init__.py
- Added: Wait until after a successful download before sending complaint, to avoid ["stern" popup notifications](https://github.com/nicotine-plus/nicotine-plus/issues/1589).
- Added: Allow buddies to leech without complaining to them.
- Added: Init log message on plugin loading to identify the active settings and minimum file/folder count requirements.
- Added: Log the actual file/folder count of leechers for improved logging.
- Added: Log users with zero statistics with a warning that the server could be wrong, and prepare handling for alternate fallback count method to be implemented, see #1565.
- Changed: Settings window strings with abbreviations, ambiguous or unclear terminology.
- Changed: Default complaint message, as appropriate to plugin behaviour.
- Removed: Pointless 'status' …
=> Leech Detector: Reduce aggressiveness

pynicotine/gtkgui/userbrowse.py
- Fixed: Alt+Enter currently has three completely different actions depending on what's focused. _Now there is only two._
- Removed: Ctrl+Enter to download folder recursively when folder contains zero files.
- Removed: Ctrl+Alt+Enter to download folder, because this is only for self browse local folder with Open in File Manager.
- Removed: Ctrl+Alt+Enter to download file, because this is only for self browse local file with Open in File Manager.
- Removed: Ctrl+Alt+Enter to open File Properties, because this function is not expected when Ctrl is pressed.
=> Browse Shares: Simplify accelerator functions

pynicotine/gtkgui/userbrowse.py
- Fixed: Previous commit caused a crash when the user is offline etc, then it was possible for the path to be None.
=> Browse Shares: Fix Critical Error on Key Press

pynicotine/gtkgui/frame.py
The recently connected click pressed gesture is plenty frequent enough to reset the away timer, in https://github.com/nicotine-plus/nicotine-plus/commit/c5ac3b79301a8e506ff5cd78b39dfa1baafdda31 is a very good idea.
The away timer works, however the notification tray icon doesn't, but that is a separate issue.
=> Don't use scroll-event to check auto-away

pynicotine/plugins/youtube_info/PLUGININFO, pynicotine/plugins/youtube_info/__init__.py
Youtube is making statistics.dislikeCount private and will no longer be available after 13th December, 2021.
https://i.imgur.com/9MRwda9.png
=> youtube_info: API changing, remove dislikes

pynicotine/gtkgui/userbrowse.py
The existing string, although well intended, was hard to understand. I tried explaining it differently, and then translated it to German, French and Dutch, to test if the translation still made sense. Since it didn't, I tried again with another string, and that one worked in all four languages.
=> Use strings that can easily be translated

pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/ui/settings/notifications.ui, pynicotine/gtkgui/ui/settings/userinterface.ui
- Added: "Display tray icon" and "Minimize to tray on startup" moved into 'User Interface' (from 'Notifications')
- Changed: "View previous primary tab on startup" -> "Remember previous primary tab on startup"
- Removed: "Primary Tabs" catagory header label, because it was unnecessary, the tabs are a part of the "User Interface".
=> settings/userinterface.ui: Move TraySettings from Notifications

pynicotine/gtkgui/frame.py, pynicotine/gtkgui/wishlist.py
- Changed: Away timer use GLib 'timeout_add_seconds', this function allows for more efficient system power usage.
- Changed: Internal function name to 'on_cancel_auto_away' because "disable" is ambiguous with 'remove_away_timer'.
- Changed: Wishlist timer use GLib 'timeout_add_seconds', because it doesn't use milliseconds anyway.
Applying this change might not improve performance of the away timer but it might improve other timers elsewhere. In any case it seems to be best practice and has no apparent downside for this use case.
According to Gtk3 documentation (see links: [timeout_add](https://docs.gtk.org/glib/func.timeout_add.html) ; [timeout_add_seconds](https://docs.gtk.org/glib/func.timeout_add_seconds.html) ; [timeout_add_seconds_full](https://docs.gtk.org/glib/func.timeout_add_secon …
=> Don't use milliseconds for away and wishlist timers

pynicotine/gtkgui/frame.py, pynicotine/gtkgui/ui/mainwindow.ui, pynicotine/slskproto.py
- Removed: Max sockets don't need to be displayed on SocketStatus bar
- Removed: slskproto doesn't need to be imported into frame, since the whole module is required just to get a static value.
- Added: Standard log entry to report maximum data sockets allowed by OS platform, upon establishing local port binding.
Before: ![image](https://user-images.githubusercontent.com/88614182/141496250-641e1a7f-9948-403f-9c67-bae35f7244ae.png) - - - After: ![image](https://user-images.githubusercontent.com/88614182/141495628-9fccdb03-d976-42f4-b8d0-52777ac619a1.png)
Since the MAXSOCKETS value always seems to be the same (it is usually "1024" on most systems, but can be less in some rare cases), it is a waste of both time and space (and possibly resources).
**_DONE:_** Perhaps if knowing this value is …
=> Don't display maximum sockets on SocketStatus bar

po/nicotine.pot, pynicotine/gtkgui/notifications.py, pynicotine/gtkgui/ui/settings/userinterface.ui
Since the nicotine+ notifications use the system's notification mechanism and no pop-ups, like in a browser, the term 'popup[sic]' is redundant and misleading. Let's remove them from the texts.
=> no more popups

pynicotine/gtkgui/settingswindow.py, pynicotine/gtkgui/ui/settings/plugin.ui
Fixed: The window is called Plugin "Properties", the "Preferences" button label doesn't match the internal "Settings" terminology.
_Changed:_
=> plugin.ui: "Preferences" button / "Properties" window -> "Settings"

pynicotine/shares.py
- Removed: "Finished rescanning shares" message, because the "folders found" count is more useful to end with on the Status bar after a manual scan, helps with #1698 , since the user will be able to see if the number of folders counted is correct or not after a manual rescan at least.
This doesn't fully address the issue for scan at startup, because if there is a folder not found error then it is very likely that the rescan will be completed before other startup messages appear that wipe out any Scanner messages from the Statusbar.
=> shares.py: Display finished count after rescan

pynicotine/pynicotine.py
The date in the version string of the installed Python run-time was ambiguous with the Nicotine+ build date, which is not known.
_Fixed:_
```
12:00:05 Loading GTK 3.22.11
12:00:05 Loading Nicotine+ 3.2.0.rc1
12:00:05 Using Python 3.5.3 (default, Apr  5 2021, 09:00:41) 
[GCC 6.3.0 20170516]
```
The date of Python run-time library is probably not really that useful, but there doesn't seem to be a simple way of excluding it without performing a stripping operation on the string. Unless the Nicotine+ build date can be shown aswell then it would be less confusing to remove the date, or at least show it on a separate line such as has been done here.
=> pynicotine.py: Seperate version strings in log on startup

pynicotine/config.py, pynicotine/gtkgui/dialogs/preferences.py, pynicotine/gtkgui/ui/settings/shares.ui, pynicotine/shares.py, pynicotine/transfers.py, test/unit/shares/test_shares.py
This is an old feature from the PySoulSeek days that causes more harm than good.
- It's somewhat painful to maintain and keep in sync with the rest of the scanning code
- With the addition of the username subfolder feature for downloads, it causes privacy concerns
- The general consensus is that downloads should be moved to another folder and reviewed before sharing, since sharing the download folder directly can contribute to issues with incomplete albums
- The original Soulseek client had this feature, but removed it
=> Remove feature to auto-share download folder

pynicotine/gtkgui/search.py
- Fixed: Counter total and "+" would not update if a default filter is set that causes 0 visible results
- Fixed: Edge case where ">...+" would not be indicated if max_limit was just exactly reached
=> search.py: Update total counter even if all results filtered by default 0+

doc/TRANSLATIONS.md
It makes more sense for these code blocks to be links instead, to make it easier for the translators to add themselves.
If you would prefer hyperlinks instead of local links then I can change it if that would be better.
=> Hyperlinks to TRANSLATORS.md and ABOUT.ui credits list

pynicotine/gtkgui/search.py
- Fixed: Keyboard focus trap in an invisible ComboBox, since the filters can be cleared without clicking the Clear button whilst the Result filters bar is hidden, by clicking the ResultCounter button
=> search.py: After clearing don't focus FilterIn if not visible

pynicotine/plugins/leech_detector/__init__.py
- Added: Extra log line for clients that only seem to report the number of folders, and not files (see Issue #1565)
- Added: State intention upon detection as to what action is "Going to " be taken, and clearly indicate " after transfer..." (see PR #1653)
- Removed: Usage of the word "complain" and "complaint", in preference for "message", because this encourages politeness
- Changed: Improved logging for "getting statistics from server", because "requesting" was ambiguous with a browse shares request
- Changed: Minimum required Files can be set to 0, for users who wish to avoid bugging Qt users whose buggy clients don't send FileStats to server
=> Leech Detector: Improve wording of logging "after transfer..."

doc/SLSKPROTOCOL.md
I was doing some experimentation today and found that Soulseek Qt logged a name for these codes, as opposed to "unknown" for everything else.  I don't have any further information about them.  I suspect they've all been deprecated for quite some time since this is the first I've heard of them.
Qt didn't respond to any of these, including `Queued Downloads`, which seems like it would be a code-only message, presumably one that would return a list of files queued for uploading on the other end.
=> Add newly discovered peer codes

pynicotine/gtkgui/ui/settings/uploads.ui
+ Changed: String "MiBs" -> "MiB" because "MiBs" was ambiguous with "MiB/s"
=> settings/uploads.ui: Queue Limits "MiBs" -> "MiB"

pynicotine/transfers.py, test/unit/transfers/test_get_upload_candidate.py
Add basic tests for get_upload_candidate, and some tidy up.
"basic" in particular because round robin mode has some dependency on `user_update_times` which these tests aren't doing anything with. And that is updated when connections are closed and file transfers are denied or time out which are a bit out of scope of this test.
The test setup and helpers are a bit verbose, I think that is because transfers.py is not written to be particularly testable. Might just be because I ran out of brain power. Hopefully the tests themselves are clear enough though so you only have to read through that stuff once.
=> Add basic tests for get_upload_candidate

pynicotine/gtkgui/dialogs/preferences.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/widgets/iconnotebook.py, pynicotine/networkfilter.py, pynicotine/plugins/examplars/port_checker/__init__.py, pynicotine/pluginsystem.py, pynicotine/privatechat.py, pynicotine/pynicotine.py, pynicotine/search.py, pynicotine/slskmessages.py, pynicotine/slskproto.py, pynicotine/transfers.py, test/unit/protocol/test_slskproto.py
This PR simplifies code related to the Soulseek protocol.
Some of the protocol logic existed in pynicotine.py for no good reason, introducing both overhead and unnecessary complexity due to constantly jumping between the network and main threads, and keeping track of separate connection objects in the main thread. Implement this logic in slskproto.py instead.
Also rename most of the confusing attributes in the code, mainly the "conn" attributes that could either point to a socket or a PeerConnection object depending on the context.
Since this is a rather large change, testing would be appreciated.
=> Move all protocol-related code to slskproto.py

pynicotine/gtkgui/ui/userinfo.ui
- Removed: Label for "User Picture", because the placeholder image makes it obvious that this area is for displaying the picture.
- Changed: Arrangement of user stats labels into a more logical display order:
=> userinfo.ui: Remove "User Picture" label

pynicotine/gtkgui/widgets/notifications.py
+ Changed: Need to account for the null terminated character appended to the message length by Windows
+ Fixed: Crash on Windows if the message is exactly 256 or title is exactly 64 characters long
Fixes #1829
Ref: https://docs.microsoft.com/en-us/windows/win32/api/shellapi/ns-shellapi-notifyicondataw
=> notifications.py: Fix crash on Windows

pynicotine/utils.py
Improve human_speed function
-    replace filesize with speed, which is the appropriate name
-    always use 3 digits of precision (not for 1.00)
-   print values between 1000 and 1024 as 0.98KiB/s
=> Human speed and size

README.md
- Changed: "since" -> "which is not", because it was ambiguous with the Nicotine+ Team used to operate the Soulseek server, since this was never the case.
=> README.md: Clarify Legal and Privacy section

doc/SLSKPROTOCOL.md
+ Added: FileSearchResult Send attribute data: bitrate; duration; vbr
+ Added: FileSearchResult Receive attribute data: *Order varies between clients*
+ Changed: Wording around "Iterate for number of [items]", because "size" was ambiguous with filesize
=> SLSKPROTOCOL.md: Improve info about Peer Code 9 (FileSearchResult)

404.md
+ Changed: URL to '/doc/DOWNLOADS' because README.md no longer contains download links.
=> 404.md: Download Nicotine+ link

doc/DEPENDENCIES.md
The linked websites have international URL redirecting in place, so rely on that instead of forcing English language.
=> DEPENDENCIESmd: Don't force English URL hyperlinks

README.md
- Changed: "Package Nicotine+ for a distribution or operating system, see PACKAGING.md." (was incorrectly DEPENDENCIES.md)
- Moved: DEPENDENCIES.md link added to Download Nicotine+ section.
=> README.md: Correct link to PACKAGING.md

doc/DOWNLOADS.md, doc/TESTING.md
+ Added: Link to TESTING.md, because this makes it easier to navigate around the website.
+ Added: Link to DOWNLOADS.md, incase website visitors get stuck on the wrong page.
+ Added: Link to DEPENDENCIES.md, this is useful and relevant in TESTING.md.
- Changed: Clarify "current stable version" and "latest unstable build" terminology to be more user-friendly.
- Changed: "Download Nicotine+" links to include SEO and user-friendly keywords.
- Changed: Plain text to hyperlinks for Flatpak, pip and Git, incase these tools need setup or config on the platform.
- Removed: Paragraph about source code from DOWNLOADS, it was an irrelevant statement of the obvious.
=> Links between DOWNLOADS.md and TESTING.md

pynicotine/transfers.py
+ Fixed: Usernames with illegal characters cause an error if 'Store completed downloads in username subfolders' is enabled.
=> transfers.py: Clean username subfolders for downloads

debian/copyright
Between 3.2.0 and 3.2.1, the svg flag files have been moved from `pynicotine/gtkgui/icons/flags/` to `pynicotine/gtkgui/icons/hicolor/scalable/intl`.
This pull request updates the `debian/copyright` file to reference the new svg files.
=> Update debian copyright file to reference correct svg flag files.

pynicotine/gtkgui/search.py, pynicotine/gtkgui/widgets/treeview.py
+ Added: Show country code on flag tooltip, because this helps for ease of reference when using the country filter
+ Changed: Use the same format for country code in search File Properties as in other modules
=> Show country code on flag tooltip and in File Properties

pynicotine/pynicotine.py
+ Added: Nicotine+ executable to debug log, because this helps to avoid confusion when testing different dev versions
+ Added: Nicotine+ configuration file path to debug log, because this helps users to discover their profile path
+ Added: Nicotine+ configuration file path to debug log on quit, this could help users to troubleshoot errors or issues
+ Changed: Debug log string map for Python executable, because this follows the syntax of other log lines
+ Changed: The order of the startup debug lines and standard log lines, for better readability
```
04:08:55 Loading GTK 3.22.11
04:08:55 Loading Python 3.5.3 (default, Nov  4 2021, 15:29:10) 
[GCC 6.3.0 20170516]
04:08:55 [Misc] Using Python executable: /usr/bin/python3
04:08:55 [Misc] Using Nicotine+ executable: …
```
=> pynicotine.py: Add application executable and config path into debug log

pynicotine/gtkgui/ui/settings/network.ui, test/unit/protocol/test_slskproto.py
The port-range 1-1023 is reserved for privileged processes and can only
be opened by the administrative user. Of course there is nothing stopping
users from running Nicotine+ as administrative user, but since it's not too
hard to figure out which port a user is using, it's also not too hard to
find users who do run n+ as admin.
=> avoid using privileged ports

pynicotine/gtkgui/transferlist.py
Fixes #1915
`position` is a misleading name for the variable, because it is ambiguous with 'queue_position'. Renamed to avoid such confusion arising.
Typo... column_id(11) is `current_byte_offset` , all other parts of the module are declared correctly as `TYPE_UINT64`
Recent regression since https://github.com/nicotine-plus/nicotine-plus/commit/f4afefc2e982cd9d4cc2318cc9d82e98b86197b0#r67267856
=> transferlist.py: Fix OverflowError TYPE_UINT64

pynicotine/transfers.py
Fixes #1917
Same as patch #1918 for the 3.2.1 branch, I don't know if it's probably easier to cherrypick merges directly from master?
Interestingly, Issues cannot be linked from sub-branches.
=> transfers.py: Don't allow int value for filename (master)

pynicotine/gtkgui/transferlist.py
- Changed: Don't compare values from tree model cell if values are available in transfer[iterator] model variable
- Changed: Only calculate human_speed() and human time elapsed if required during update_parent_row()
Performance slightly improved, functionality unaffected.
=> transferlist.py: Avoid unnecessary human_speed and time conversions

pynicotine/gtkgui/userlist.py
- Removed: Don't write last_seen time to config file every time a buddy changes status, this data isn't that important
+ Added: Write to config file once via save_user_list() during server_disconnect() instead of multiple times
=> userlist.py: Avoid recursive config writes for buddy status

pynicotine/gtkgui/ui/downloads.ui, pynicotine/gtkgui/ui/uploads.ui
Reverts nicotine-plus/nicotine-plus#1902
Perhaps we shouldn't remove this button until we can provide a way to do one-click clean-up of everything that's finished, such as with Ctrl+Click or suchlike.
https://github.com/nicotine-plus/nicotine-plus/commit/d121e9ca6c5233d3517849c54caa4b4d20664d5b#commitcomment-67978741
=> Revert "Remove 'Clear Finished' buttons"

pynicotine/gtkgui/chatrooms.py
+ Fixed: Use `msg`.room instead of `self`.room for TTS, because otherwise all the rooms in the Public feed are "in room Public"
=> Chat Rooms: Speech self.room -> msg.room for the Public room feed

pynicotine/gtkgui/chatrooms.py
+ Fixed: When mentioned in an action, `speech` is correctly sliced `text` without "/me " displayed in the notification popup
+ Changed: Show notification after appending line to chat TextView, to avoid the slight UI stutter upon mention
Suggest we could rename the `speech` variable to something more universally applicable such as `text_trimmed`
=> Chat Rooms: Fix broken string mentioned in action notification

pynicotine/gtkgui/dialogs/fileproperties.py
+ Added: Display the filesize Bytes in brackets after factorized size, as is common for file management interfaces
Helps with #1948 until perhaps some kind of options for customizing the filesize column can be implemented.
=> File Properties dialog: Also display filesize in Bytes

pynicotine/gtkgui/dialogs/preferences.py
+ Fixed: Critical Error on open Preferences Chats page after previously being allowed to set invalid TTS format string:
```
Error in sys.excepthook:
Traceback (most recent call last):
File "/home/user/Git/dev/nicotine-plus/pynicotine/gtkgui/dialogs/preferences.py", line 3077, in on_switch_page
page.set_settings()
File "/home/user/Git/dev/nicotine-plus/pynicotine/gtkgui/dialogs/preferences.py", line 1350, in set_settings
self.default_private(None)
AttributeError: 'ChatsFrame' object has no attribute 'default_private'
```
ToDo: Validate TTS format strings when changed to avoid crash in new_tts()
=> Preferences: Fix Critical Error on Chats page when TTS format string invalid

pynicotine/gtkgui/widgets/textentry.py
+ Changed: Respect the 'When closing Nicotine+' setting preference, instead of terminating unexpectedly when typing "`/q`"
A one letter command is too short for a function which kills the application when entering any string starting with "`/q `..."
Suggest the aliases could be split into different functions if anybody wants a way to do termination without prompt.
The dialog without the 'remember' toggle is shown, to avoid confusing the user's window close settings.
=> textentry.py: Show exit dialog (if set) on /quit /exit or /q command

pynicotine/gtkgui/chatrooms.py
+ Changed: Text-To-Speech off by default in Public feed, because messages are relentless and way too fast for TTS to keep up
Should a TTS user wish to enable Auto-join for the Public feed, then Speech always needs to be turned off at the start of every session, otherwise the speech message queue quickly becomes overwhelmed (it never catches up).
=> Chat Rooms: TTS off by default in Public feed

doc/SLSKPROTOCOL.md
I was able to confirm the attributes returned by Qt > 2015-6-12 for the most common lossless and lossy formats.  I tried an AIFF and it returned only bitrate and length, but from what I can tell there are both lossless and lossy versions so I'm reluctant to commit that to documentation at the moment.
For slskd I'm choosing to include the VBR attribute for lossy formats because NS and Nicotine+ both display it and I think there's some benefit for client-side filtering.  Interestingly, Qt doesn't display the VBR flag on the UI, but it does appear to work when filtering with `isvbr`.
=> Document attribute combinations for Qt > 2015-6-12, slskd

pynicotine/plugins/README.md
+ Added: Brief guidance for installing custom plugins aimed at end-users.
+ Changed: Minor changes to the wording in the For Developers section.
=> plugins/README.md: move For Developers heading

pynicotine/gtkgui/widgets/trayicon.py
+ Added: Check that the custom icon theme path setting is not "(None)" before scanning directory for icons
`[2022-03-25 14:20:24] [Misc] Error accessing custom tray icon path : [Errno 2] No such file or directory: ''`
=> trayicon.py: Suppress error if no custom icon theme path is set

pynicotine/pynicotine.py
Displaying and logging the value of this setting in clear text doesn't seem appropriate, because it could pose a security risk.
_Confirmation dialog:_
_Log:_
`[2022-05-18 18:14:43] Your password has been changed.`
=> pynicotine.py: don't log new password string value after changing it

pynicotine/gtkgui/frame.py
It doesn't make sense to hide 'important' level log messages from the Log Pane, since they are displayed in the console and to file, so why not show them in the interface too... This is handy after closing the dialog box to see what it said.
=> frame.py: show important log messages in log view

doc/SLSKPROTOCOL.md
https://nicotine-plus.org/doc/SLSKPROTOCOL.html#sending-login-example
This table does not render properly on the Nicotine+ website, because the page's HTML flattens the table as a paragraph into `<p>` tags instead of `<table>` tags. It's fine when viewing the markdown page from within the GitHub website.
I don't know if the issue is caused by italic `<em>` "`*Data*`" `</em>` text in the table headers, or if it's the lack of `</p>` line breaks after the "`*Message:*`" titles, so this PR tries both fixes, but I don't have an easy way of testing how GitHub Pages will convert the MD into HTML until this PR is merged.
This has been broken since commit https://github.com/nicotine-plus/nicotine-plus/commit/8a9490ae921ee562034b8c1b922fe678be976d0e#r74084767
=> SLSKPROTOCOL.md: rendering problem with HTML table

pynicotine/__init__.py, pynicotine/gtkgui/__init__.py, pynicotine/gtkgui/application.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/widgets/trayicon.py
The -t and -d command line options are not very useful and perhaps confusing to the user (as to this being a temporary state and not permanent config change). Also the command line arguments have no effect in certain modern environments such as macOS.
- Removed: Obsolete "-t" command line option and "--enable-trayicon" argument
- Removed: Obsolete "-d" command line option and "--disable-trayicon" argument
In the future the removed options could be better used for example:
+ `-d file` `--download file` specified by an slsk:// URL then exit (or stay running)
+ `-d folder` `--download folder` count the files and size of a remote folder and prompt to download it
+ `-t` print a list of currently active `--transfers` or do some `--terminal` console related function
+ `-t abort` stop and clear …
=> pynicotine: remove "-t" and "-d" command line options for Tray Icon

doc/SLSKPROTOCOL.md
Correction to documented server generated reason string "Bad Password" was incorrect...
Receive Login Failure
-    **bool** failure **0**
-    **string** reason _Almost always:_ **INVALIDPASS** _(sometimes it's a banned message or another error)._
=> SLSKPROTOCOL.md: Server Code 1 reason "Bad Password" -> "INVALIDPASS"

pynicotine/config.py
... because showing 15 old messages is not very useful by modern standards.
=> Chat Logs: increase default chat log read lines up to 200 old messages

pynicotine/gtkgui/chatrooms.py
+ Fixed: The fix for #1790 is now also applied to previously logged public chat messages
- Removed: Don't strip() spaces from username strings while reading public chat log
- Changed: When matching text it's faster to find from after start position
+ Added: Support usernames containing an open square bracket "[" and also a closed "] " bracket who said a /me action
=> gui/chatrooms.py: Only find whole word mentions when reading old message log

NEWS.md
and other minor changes to Changes section in **3.2.3rc1 (Release Candidate 1)**
- It wasn't obvious enough that the new scroll wheel feature doesn't apply to the Main Tabs
- The private TTS button only appears if it is enabled in Preferences
- "GUI consistency" LOL :D
TODO: This latest news is also needed on the website (i.e. in the `master` branch), and how to the thing with TESTING.md?
=> NEWS.md: clarify the secondary tabs have mouse scrolling

NEWS.md
+ Added: "IMPORTANT" issue about CPU usage in Uploads tab (we don't really know if this is rare or not, and it is severe).
+ Added: @AtticFinder65536's solution to prevent incomplete filename from exceeding 255 bytes
- Changed: The order of the Corrections section in 3.2.3 into the order of subjective importance.
- Changed: Clarified about "total" time, and changed word order about subfolders of folders containing subfolders.
=> NEWS.md: Nicotine+ 3.2.3 Bug Fixes, Changes and Corrections

pynicotine/gtkgui/popovers/roomwall.py
+ Fixed: Visual bug where a new Room Wall entry does not have the "`> `" prefix upon first being submitted
It was necessary to close and re-open the popover for our own recent entry into the top of the Room Wall text view to appear correctly.
=> roomwall.py: add missing "> " character to new entry

NEWS.md
+ Added: Document the change of Windows installer format to reflect the GitHub release history
> Version 3.2.0 (December 18, 2021)
> ---------------------------------
>
> **WINDOWS USERS: The installer format has changed in Nicotine+ 3.2.0 and above. If you are upgrading from Nicotine+ 3.1.1 or earlier, please uninstall Nicotine+ first (this will not remove your existing settings).**
=> NEWS.md: note for Windows users since 3.2.0

NEWS.md
+ Added: Correction about Update locally saved upload speed less often
- Changed: Increased importance of long path and file names issues, since both related bugs are now fixed
- Changed: Grammer of the location of folders "into" subfolders that are contained within folders that have subfolders inside the parent folder when downloading folders with subfolders.
=> NEWS.md: lastest bug fixes in Nicotine+ 3.2.3

po/nicotine.pot, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/frame.py, pynicotine/gtkgui/ui/settings/log.ui
Some lines don't use the rooms_timestamp and log_timestamp preference, but I feel like they should. See commit messages.
[privatechat.py uses the private_timestamp pref for disconnected/reconnected messages](https://github.com/nicotine-plus/nicotine-plus/blob/master/pynicotine/gtkgui/privatechat.py#L297) so all messages in private chats use the same user-specified timestamp format, so 9c721c4da801899f947628323399109094de1f5e should be ok, just fixing something that was forgotten. As for 1ba07ffb79ecb44cdc37f08a31caca4a26dc0572 I'm not 100% sure if this is a welcome change, but I personally prefer it. To allow the user to set the timestamp format of the messages in the log history pane, we could create a new config option next to the existing log_timestamp option for it, but I think …
=> gtkgui: use timestamp format preferences in more contexts

pynicotine/plugins/examplars/testreplier/__init__.py
This PR removes any "!" from the start of reply strings before sending it, because it seems undesirable for this plugin to be able to trigger other user's plugin commands out-of-the-box.
Since it is not grammatically correct for a sentence to begin with an exclamation mark, then normal operation should not be affected for most use cases.
=> testreplier: don't allow sending a plugin command!

pynicotine/gtkgui/chatrooms.py
Include the actual room name in notifications for mentions in the Public feed, and avoid duplicate notifications if the room's chat tab is open.
Fixes https://github.com/nicotine-plus/nicotine-plus/discussions/2145#discussioncomment-3418096
=> Chat Rooms: Include room name in Public feed mention notification

pynicotine/__init__.py
- Removed: "Nicotine+ is a Soulseek client" string, in favour of the string defined in `config.summary`
+ Added: Footer epilog with `config.author` + `config.website_url` to match the `man nicotine` page
```
$ ./nicotine --help
usage: nicotine [-h] [-c file] [-u dir] [-p dir] [-t] [-d] [-s] [-b ip]
[-l port] [-r] [-n] [-v]
Graphical client for the Soulseek peer-to-peer network
...
Nicotine+ Team <https://nicotine-plus.org/>
$ 
```
On most windowed posix terminals the URL <link> is clickable.
=> nicotine: Improve command line usage help description string

pynicotine/gtkgui/ui/mainwindow.ui
"Room List" is ambiguous with list of Users in a room.
The name of the user list is "Users", so the room list should be "Rooms"
=> mainwindow.ui: Room List -> Rooms

pynicotine/gtkgui/ui/mainwindow.ui
The primary function is "/join" so that word should be first.
Creating a room is not a common function that is hardly used.
=> mainwindow.ui: "Join or create room…"

pynicotine/gtkgui/ui/mainwindow.ui
GNOME HIG
Matches string in the main menu, so it can be backported to 3.2.x
=> mainwindow.ui: "Show Log History Pane"

pynicotine/gtkgui/ui/mainwindow.ui
Use header capitalization in (short) tooltips according to the new GNOME HIG: https://developer.gnome.org/hig/patterns/feedback/tooltips.html
=> mainwindow.ui: capatalize Configure tooltips

pynicotine/gtkgui/ui/mainwindow.ui, pynicotine/gtkgui/ui/search.ui
Unify this tooltip string in Search Files, Downloads and Uploads.
Use header capitalization in (short) tooltips according to the new GNOME HIG: https://developer.gnome.org/hig/patterns/feedback/tooltips.html
=> "Result/File grouping mode" -> "File Grouping Mode"

pynicotine/transfers.py
Otherwise with a low token number it appears to be how many retry attempts ie:
+ "download request 1" -> "download request with token 1"
Also slightly improve punctuation of the non-translated Transfers logging `from user: username, allowed: True, reason: None`, otherwise the colons look like the transfer is permitted as in "username: allowed" but "allowed: False".
=> transfers.py: clarify logged digit is a token

pynicotine/gtkgui/ui/mainwindow.ui, pynicotine/gtkgui/ui/search.ui, pynicotine/gtkgui/ui/settings/network.ui, pynicotine/gtkgui/ui/userbrowse.ui
Use header capitalization in (short) tooltips according to the new GNOME HIG: https://developer.gnome.org/hig/patterns/feedback/tooltips.html
That's most of the obvious ones in the main interface done now.
=> Capitalize Short Tooltips

pynicotine/config.py
Closes #2228 
It might be a good idea to move this log entry into the debug log, since it is not really an important enough problem for it to be in the standard log.
=> config.py: move "Unknown config option" into debug log

doc/SLSKPROTOCOL.md
Closes #1985
> It would be a good idea to add common transfer status messages to the Soulseek protocol documentation.
Please feel free to suggest what headers and content is required to populate the new table, or take it over as you deem appropriate.
=> SLSKPROTOCOL.md: Transfer Status Strings table and NS >2GB offset

pynicotine/gtkgui/privatechat.py
Fix #2247 "Delete chat log... >> Value: 'PrivateChats' object has no attribute"
+ Fixed: Regression caused by backport commit b5423cd1c: "chatrooms.ui: use snake case widget names"
+ Checked: No other instances of `chat.history` are found in the 3.2.x branch tree
```
gtkgui/privatechat.py L348 | b5423cd1c (2022-04-09 02:56:58 +0300 348)             self.chats.history.remove_user(self.user)
```
- **TODO: Bump to 3.2.7 before merging this fix.**
=> [3.2.x] privatechat.py: remove call to non-exist module

pynicotine/gtkgui/search.py, pynicotine/gtkgui/ui/popovers/searchfilterhelp.ui
+ Added: Enable matching of usernames in the Include and Exclude search result filters
Only entire username strings are exact-matched such that it is unlikely to interfere with path string searching.
As the future intention of #1887 is to integrate filters into the wishlist for the purpose of ignoring unwanted results, then excluding usernames will be key data for that purpose, and filtering by username could be useful in any case.
=> Result Filters: Match usernames

pynicotine/userlist.py
- Changed: String to disambiguate "Online" status of buddy who could be "offline"
Having the word "Online" appearing in the title of message is confusing if the buddy is going offline.
=> userlist.py: Buddy Status notification title

pynicotine/gtkgui/application.py
+ Added: Raw system platform identifier in Critical Error message
In some cases it is useful to know which platform a reported error occurred.
Example output on "linux" platform:
```
Nicotine+ Version: 3.3.0.dev4
GTK Version: 3.24.24
Python Version: 3.9.2 (linux)
```
=> show sys.platform in critical error dialog

TRANSLATORS.md, pynicotine/gtkgui/application.py, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/dialogs/about.py, pynicotine/gtkgui/dialogs/preferences.py, pynicotine/gtkgui/mainwindow.py, pynicotine/gtkgui/ui/mainwindow.ui, pynicotine/gtkgui/ui/settings/userinterface.ui, pynicotine/gtkgui/userinfo.py, pynicotine/gtkgui/widgets/popupmenu.py, pynicotine/gtkgui/widgets/trayicon.py, pynicotine/userinfo.py
The idea is that the user description becomes more prominent, in order to learn more about a user before interacting with them. User profiles contain buttons to then perform various actions, like sending a private message.
- Move user profile item to the top of user menus
- Double-clicking usernames in chatroom list opens user profile
- Rename user info -> user profile
=> Prioritize user profiles in user actions

pynicotine/gtkgui/dialogs/fastconfigure.py
+ Fixed: Allow adding all the other multiple selected folders even if one of them is already shared
Otherwise, it appears baffling as to why the attempted Add operation was only partially successful, especially if the existing share is a buddy-only share which are not shown in this list. The silent fail makes the interface frustrating to use in this scenario.
In future, we should consider moving the duplicated shares-related code from fastconfigure.py and preferences.py into shares.py (perhaps an _apply_config_ boolean flag can be used to determine if the config file is updated straight away or not, and _mapping_ can be returned to populate the calling list).
=> fastconfigure.py: continue adding shared folders

.github/workflows/packaging.yml
Tray icon and notification support isn't present yet, but I still want to start testing GTK 4 in time.
=> Use GTK 4 in Windows builds

pynicotine/gtkgui/ui/settings/userinterface.ui
Whenever I browse the "User Interface" settings page, I'm always confused by the tab-related preferences being split between the general section and a "Secondary Tabs" section. It doesn't feel intuitive to jump between them when you want to change tab preferences.
Combine the preferences in a single section, as such:
=> settings/userinterface.ui: combine tab prefs in a single section

pynicotine/gtkgui/ui/dialogs/fastconfigure.ui, pynicotine/gtkgui/ui/settings/shares.ui
Matches the string in Setup Assistant
better alternative to #2204 , The minor detail about "hidden files" is ambiguous with Soulseek 'private files' or buddy-only shares, it's confusing to mention this here.
=> settings/shares.ui: change explanation

pynicotine/plugins/examplars/port_checker/PLUGININFO, pynicotine/plugins/examplars/port_checker/__init__.py
+ Changed: `/port` command to use new core_commands system, with syntax usage and help description etc.
=> port_checker: move port command to core_commands

pynicotine/gtkgui/widgets/textentry.py, pynicotine/plugins/core_commands/__init__.py
- Moved: `/join` command into core_commands plugin, no functional changes.
- Moved: `/leave` into core_commands plugin, Added error message if specified chat room is not joined.
- Removed: `/p` and `/part` aliases from the `/leave` chat room command
=> core_commands: join and leave chat room commands

pynicotine/gtkgui/widgets/textentry.py, pynicotine/plugins/core_commands/__init__.py
+ Moved: `/me` command into core_commands plugin, no functional changes.
=> core_commands: me command

pynicotine/gtkgui/widgets/textentry.py, pynicotine/plugins/core_commands/__init__.py
+ Moved: `/search` command into core_commands plugin, no functional changes.
+ Moved: `/rsearch` command into core_commands plugin, no functional changes.
+ Moved: `/bsearch` command into core_commands plugin, no functional changes.
`/usearch` command requires _shlex_ syntax parsing to support usernames that contain spaces, so it will follow in a separate PR.
=> core_commands: search rsearch bsearch commands

pynicotine/plugins/core_commands/PLUGININFO, pynicotine/plugins/core_commands/__init__.py, pynicotine/pluginsystem.py
+ Added: Human name of "core_commands" plugin to application_name + "Commands", i.e: "Nicotine+ Commands"
The string appears for the main group in the `/help` output as well as for the title of `self.log` messages.
Without a `human_name` value, the plugin log function is not really usable, if we were to ever want to use that.
=> pluginsystem.py: give core_commands a human_name

pynicotine/pluginsystem.py
+ Fixed: Always enable the core_commands plugin, even if the user has disabled the plugin system.
The core_commands plugin cannot be disabled whilst the application is running, but if the application was restarted after disabling the plugin system then the entire command system is unavailable, which totally bricks the headless mode CLI and the command help popover is blank.
=> pluginsystem.py: always enable core_commands

pynicotine/plugins/core_commands/__init__.py
+ Changed: Escape invisible alternate whitespace with `\t`
Otherwise my text editor wants to convert it into a space every time the file is saved.
=> core_commands: escape tab in help message output

pynicotine/gtkgui/dialogs/preferences.py, pynicotine/gtkgui/widgets/textentry.py, pynicotine/networkfilter.py
This PR includes what is needed to support the user filtering related CLI core_commands being developed in #2281
+ Added: Support for adding IP addresses directly into the IP Ban/Ignore filters, without needing to know a username
+ Added: Try to establish a username, if known, whilst adding a IP ban/ignore filter in the Preferences or `/ignoreip` command
As a result of the intended implementation, it has been necessary to address the following issues:
+ Changed: Prefer locally stored `core.user_addresses` where possible to avoid unnecessary excessive GetPeerAddress() calls
+ Fixed: Several issues that made it impossible to reliably ban/ignore more than one offline user at a time
+ Fixed: Prevent duplicate username lookups for improved performance when getting and setting cached ban/ignore …
=> networkfilter.py: support explicit ip addresses and handle offline users

pynicotine/networkfilter.py
+ Fixed: Possible AttributeError when attempting to remove a non-existant IP filter of a user who isn;t banned or ignored nor has never been seen online
Regression since https://github.com/nicotine-plus/nicotine-plus/pull/2287
It is not clear if we are supposed to use `"0.0.0.0"` or `None` or `""` or something else for expressing the address unknown/offline users throughout different parts of the application. It is awkward handling variables that may contain different data-types.
=> networkfilter.py: fix AttributeError if IP address is None

pynicotine/core.py, pynicotine/gtkgui/dialogs/preferences.py, pynicotine/gtkgui/widgets/popupmenu.py, pynicotine/networkfilter.py, pynicotine/privatechat.py, pynicotine/search.py
- If an IP-banned user changes their IP address, keep the filter for the old IP address in place until the user is unbanned.
- Various code cleanups
=> networkfilter.py: remember previous IP addresses of user

pynicotine/gtkgui/widgets/textentry.py, pynicotine/networkfilter.py, pynicotine/plugins/core_commands/__init__.py
+ Moved: `/ip` command into core_commands plugin
+ Changed: `/ip` command get address from core and print to output if available, fallback to request only if user is unknown
+ Added: `/ip` command can accept IPv4 address as argument for looking up an online address to output associated username
There is no text around the raw output strings, which makes copy & paste nice and easy when working with the network filters in a terminal, but it could be debated as to if more verbosity could be desirable.
- The future plan is to also output the Online/Offline status and Banned/Ignored states, as well as listing any stored IP addresses/usernames associated with a particular user/address.
-  For now this PR brings all the functionality that is required to replace the existing `/ip` command.
=> core_commands: ip command

pynicotine/gtkgui/widgets/textentry.py, pynicotine/plugins/core_commands/__init__.py
+ Moved: `/ban` `/unban` `/ignore` `/unignore` commands into core_commands plugin
+ Changed: `/ban` and `/ignore` commands can accept either username or IPv4 address as argument to add appropriate filter
+ Changed: `/unban` and `/unignore` commands removes both username-based and IP-based filters at the same time
+ Added: Echo output of added/removed filter item(s)
- Removed: `/ignoreip` command (was undocumented, Changed: `/ignore` command to also accept an IPv4 address instead)
=> core_commands: ban unban ignore unignore commands

pynicotine/gtkgui/widgets/textentry.py, pynicotine/plugins/core_commands/__init__.py
+ Moved: `/msg` command into core_commands plugin
+ Changed: Don't switch to the tab on entering `/msg` command, because that's what the /pm command is for
Tab switching is not desirable because that defeats the purpose of a having command which gives the ability to send a message to a user other than the current tab window.
_Note: The current /msg command cannot send messages to "user names" that contain spaces. For a suggested working solution to that problem see PR #2344, meanwhile this PR can be merged as it retains the functionality of the existing command._
=> core_commands: msg command

pynicotine/gtkgui/widgets/textentry.py, pynicotine/plugins/core_commands/__init__.py
+ Moved: `/browse` command into core_commands plugin
+ Added: Enable usage from chat rooms or other private chat windows with the `<user>` argument
=> core_commands: browse command

pynicotine/gtkgui/widgets/textentry.py, pynicotine/plugins/core_commands/__init__.py
+ Moved: `/usearch` command into core_commands plugin, no functional changes.
_Note: The positional `<user>` argument has to be mandatory even in private chat, because otherwise it is ambiguous with the first word of the `<query>` argument. Only single-word usernames are supported, this is the same way as the original command works._
In future we could support parsing quoted arguments to improve this, but that isn't needed for our purposes right now. This PR completes the full suite of existing commands as is in the "Search Files" category.
=> core_commands: usearch command

pynicotine/gtkgui/widgets/textentry.py, pynicotine/plugins/core_commands/__init__.py
+ Moved: `/add` and `/rem` (alias `/buddy` and `/unbuddy`) commands into core_commands plugin, no functional changes.
- Removed: `/ad` alias from the `/add` buddy command, because it seems useless clutter in the help.
There is no output to confirm the requested operation was successful or not. That might belong better in userlist.py as standard logging.
=> core_commands: add buddy rem unbuddy commands

pynicotine/plugins/core_commands/__init__.py
+ Added: `/say` command into core_commands plugin, as it was traditionally in previous versions of Nicotine
+ Added: Don't attempt to send chat room message unless joined, fail with error message if not
_Note: Only single-word room names are currently supported._ 
If we don't want to include this command in the project right now, then it can be excluded with the `"disabled"` property, (or perhaps be placed into a hidden help group, or an optional plugin?). rather than it being omitted entirely.
=> core_commands: say command

pynicotine/plugins/core_commands/__init__.py, pynicotine/pluginsystem.py
+ Changed: Unknown command string "for a list of commands" -> "to list available commands"
+ Added: Help command output string if there are no matching results for the given argument
The word "to" is more to the point than using "for", "a" and "of" in the sentence:
```
Unknown command: /tfgyuhjio. Type /help to list available commands.
```
The word "available" matches how it is used in the other descriptions:
```
/help uyighuihuh
Listing 0 available commands matching "uyighuihuh":
Type /help to list available commands
/help
Listing 25 available commands:
Nicotine+ Commands:
/help, /? [query]  -  List available commands
...
```
=> pluginsystem.py: "to list available commands"

pynicotine/networkfilter.py
+ Changed: Avoid doing an unnecessary membership test in most cases, it is not possible for a placeholder to exist if the user is online.
=> networkfilter.py: skip offline placeholder check for online users

pynicotine/plugins/core_commands/__init__.py
+ Changed: Correct the alphabetical display order of chat related command groups, for more logical help output.
+ Changed: Logical order of Private Chat commands, instead of alphabetical, to match logical order of Chat Rooms commands.
+ Removed: /sample command don't return True.
```
Listing 8 available commands matching "chat":
Chat:
/clear, /cl  -  Clear chat window
/me <something..>  -  Say something in the third-person
Chat Rooms:
/join, /j <room>  -  Join chat room
/leave, /l <room>  -  Leave chat room
/say <room> <message..>  -  Say message in specified chat room
Private Chat:
/pm <user>  -  Open private chat
/close, /c [user]  -  Close private chat
/msg, /m <user> <message..>  -  Send private message to user
```
=> core_commands: logical order of chat commands

pynicotine/gtkgui/widgets/textentry.py, pynicotine/plugins/core_commands/__init__.py
+ Moved: `/away` command into core_commands plugin
+ Added: Print output to state current online status
It would be better if the core had a toggle_away_status() function, to avoid needing the UserStatus import, also perhaps that logged status change similar to that of a buddy status notification.
=> core_commands: away command

pynicotine/gtkgui/search.py, pynicotine/shares.py
Allows you to use filters such as "audio|image", "audio|text|!mp3", "!video|!image".
=> search.py: implement generic file type filters

pynicotine/portmapper.py
As per discussion in #2408, *send with retry* mechanism was implemented for NAT-PMP port-mapping requests. The maximum number of retry attempts was set to 2, which should be enough (the spec says 9).
=> portmapper.py: repeat NAT-PMP requests with increasing timeout

pynicotine/gtkgui/search.py
Resolve #2415.
Commit [d14494ac](https://github.com/nicotine-plus/nicotine-plus/commit/d14494ac316f3813abdc835df6ac2e5187c306ce) introduced a new column -- file type icon, which shifted some columns, changing their index. Therefore, the `fullpath` column is now at `12`. This change was reflect in a number of places in the code, but the one causing this bug was missed.
=> gtkgui/search.py: use correct fullpath column index

pynicotine/gtkgui/ui/userbrowse.ui, pynicotine/gtkgui/userbrowse.py
+ Changed: "Save Shares List to Disk" button sensitivity is reactive to the folder list view having any items in it or not
+ Fixed: Don't allow the `Ctrl+S` keyboard shortcut whilst shares are loading or not present
=> gtkgui/userbrowse.py: don't allow saving an empty shares list

NEWS.md
+ Changed: Clarify that a correction was a visual bug unrelated to actual transfer progress
=> Update NEWS.md for Nicotine+ 3.2.9.dev1

pynicotine/gtkgui/widgets/textview.py
+ Changed: Use the appropriate cursor for username tags in chat, which should be the "default" (arrow) cursor.
The "pointer" finger cursor is only suitable for indicating a hyperlink action, it not appropriate for an interface widget with a standard click action that simply shows a context-menu.
The "default" arrow cursor could also be set by setting `cursor = None`, but defining the default cursor in a constant seems like the right thing to do.
=> textview.py: use default cursor for username tags

pynicotine/gtkgui/userbrowse.py
+ Changed: Use path instead of iterator for expanding and collapsing, path is already provided by the tree view widget
=> userbrowse.py: minor optimization folder tree view

pynicotine/pluginsystem.py
+ Fixed: An IndexError is encountered if the final or only argument in `usage` is an [optional] choice but no choice is entered.
The intention is to allow the possibility for a choice argument to be optional, but a crash occurs.
Allow usage, for example `"[option2|option3]"` (where implicit 'option1' is considered to be the default if no choice is entered).
If a positional required argument is missing then it will be already be picked up by the "Missing {arg} argument" condition.
=> pluginsystem.py: fix IndexError on no choice argument

pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/widgets/treeview.py
Resolves https://github.com/nicotine-plus/nicotine-plus/discussions/1881#discussioncomment-3263521
+ Added: Expand into first level upon initial loading of Browse Shares list, instead of fully collapsed.
The required functionality already exists for `"folder_grouping"` view mode, the new method can be used for that as well, as commented in the legacy function.
The Expand / Collapse All button function is unaffected, it is still useful to remember the expand preference if desired.
=> treeview.py: new expand_root_rows() method implemented for Browse Shares

pynicotine/plugins/core_commands/__init__.py
+ Changed: Network Filter commands had two separate optional arguments but it read like two positional arguments.
=> core_commands: combine usage ambiguous optional arguments

pynicotine/gtkgui/application.py, pynicotine/shares.py, pynicotine/userbrowse.py
Code cleanup. No functional changes.
userbrowse.py: A single method can handle any local share group without hard-coding the share group name.
shares.py: If the share group name does not exist (for example "public"), then fall back to "normal".
=> userbrowse.py: cleanup browse_local_shares()

pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/widgets/treeview.py
If the file and/or folder still exists in the refreshed shares, then it was frustrating that the selection is lost after doing a refresh operation, because finding the desired item again can be difficult if the shares are large, as there are no location history features.
+ Added: Return to the currently selected location (file and/or folder) after doing a Refresh
+ Changed: Add a trailing slash onto to the end of folder path copy to clipboard string
+ Fixed: Grab the focus onto the relevant list view widget when entering a URL even if the tab is already open
The clipboard copy code is slightly repurposed for this. The new getter functions are designed to be useful for other purposes too, such as for storing location history, status text, tooltips, etc.
If the selected file doesn't exist …
=> gtkgui/userbrowse.py: remember selection after refresh

pynicotine/gtkgui/search.py
+ Fixed: Crash on search with default length or type filter set
+ Changed: Loop iteration instead of elif ladder
correction to #2457
=> gtkgui/search.py: cleanup populate_default_filters()

pynicotine/gtkgui/search.py
Code cleanup, minor performance.
+ Changed: Update number of active filters counter label when the number of active filters change, instead of when the number of visible results change.
+ ~Changed: Render the filter combobox list separator in sequence, while the list is short, before adding filter history items~
The update_filter_counter() call was in the wrong place. While incoming search results are being received or refiltered, the number of visible search results is unrelated to any interactions that would change which result filters are currently active.
~Draft: Slight bug exists where Undo icon does not change to Clear icon if the a filter's most recent history item is selected again.~ _Edit: Turns out that bug existed before and is not caused by this Pr._
=> gtkgui/search.py: update active filter counter with filter widgets

pynicotine/gtkgui/search.py
+ Fixed: Slight bug where Undo icon does not change to Clear icon if a single filter's most recent history item is selected again
The button got confused if the field value is manually set to the same value as is stored in the undo.
This PR simplifies the undo mechanism by consolidating the setting of it into one place. The Restore Filters button now becomes enabled even if the only active filter entry is cleared manually.
=> gtkgui/search.py: correctly Restore/Clear Filters

pynicotine/gtkgui/userbrowse.py
The current sentence is hard to properly translate:
> you both have a closed listening port
will result in the following automatic translation:
> Sie haben beide einen geschlossenen Empfangsport
Which doesn't make sense since the translation engine does not understand the difference of you singular and you plural, but:
> the listening ports are closed on both sides
Will result in
> die Empfangsporten sind beidseitig geschlossen
Which is spot on.
I generally would try to avoid `you`, because of this ambiguity. Consider
> Do you really want to clear all uploads?
and the shorter:
> Really clear all uploads?
=> This formulation is easier to translate.

pynicotine/shares.py
Code cleanup. No functional changes.
These methods are easily made agnostic, such that any `share_type` may be specified as the prefix for the database file.
`"public"` is the only special case because the database files have no prefix, otherwise reducing the hard-coding of share_type names could help to make the shares module more extensible.
=> shares.py: get share_dbs destination from share_type

pynicotine/plugins/core_commands/__init__.py, pynicotine/shares.py
Provides a workaround for issues like #2447 and #2472 , whereby it is desired to force an entire rebuild of the database regardless of the folder mtimes.
+ Added: Optional `rebuild` choice argument for the /rescan command
+ Changed: Optional `force` flag argument into choice argument
+ Added: New string in shares to log the mode of rescan/rebuild
+ Changed: swap the order of initial log strings, and remove superfluous word from before folder count string.
"rebuild" also implies "force", otherwise if the rescan is interrupted by the Shares Not Available dialog prompt, then the rebuild option flag would be ineffectual.
=> core_commands: rescan force rebuild optional choices

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/widgets/iconnotebook.py
+ Added: `prepend_page()` It makes sense to open the global room feed chat tab in the first position.
+ Added: `insert_page()` Sometimes it may be useful to open a new tab at a specific position, such as adjacent to current tab.
+ Fixed: Fail to activate new foreground tab if the Public room feed was enabled and is disabled then enabled again.
Since a custom position for the Public chat feed tab cannot be remembered across restarts, this avoids the risk of it getting buried in amongst other open chat tabs. If it is found to be annoying, then the opportunity close it is more easily presented this way, because it will be visible in the same position as it is on startup.
This approach might become more relevant if clickable room name tags as suggested in #2482 are implemented, therin it will …
=> iconnotebook.py: prepend_page for global room feed

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/widgets/textview.py
Since https://github.com/nicotine-plus/nicotine-plus/commit/af9d32cbcceab8b8d3ff499ea9f0a9f61b153e1d the private chat log file readback now has highlighted mentions but incomming new messages don't.
+ Added: private chat mention tag line highlighting for incoming new messages, as well as log file readback.
+ Fixed: Mention of login username in chat failed to highlight during log file readback if mentioned at end of line.
+ Changed: code cleanup, attempt to reduce complexity of chat line tag assignment logic.
The addition of mention highlights in private chats was incidental to the unification of log file readback, however it may be considered useful perhaps to signal priority importance by enabling a caller to set the is_important tab icon urgency hint.
=> ChatView: new get_line_tag() method

pynicotine/gtkgui/widgets/iconnotebook.py
Regression since https://github.com/nicotine-plus/nicotine-plus/commit/20f28f862ff0b9a0cb224c9ef412ca98626a020d caused by #2516. Aims to resolve point 2 in issue #2482.
+ Fixed: wrongly highlighted the global room feed tab on new message when it's the current page and active parent window tab.
=> iconnotebook.py: don't highlight current tab on global feed

pynicotine/chatrooms.py, pynicotine/core.py, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/dialogs/preferences.py, pynicotine/gtkgui/userinfo.py, pynicotine/gtkgui/widgets/popupmenu.py, pynicotine/networkfilter.py, pynicotine/plugins/examplars/port_checker/__init__.py, pynicotine/privatechat.py, pynicotine/userinfo.py, pynicotine/userlist.py
We're now in a position where we can do a better job at avoiding redundant IP address requests to the server, e.g. when joining multiple rooms with overlapping users at once, or a room where several of the members are in our buddy list.
Also fixes an issue where we would keep storing stale IP addresses of room members after leaving a room.
=> Avoid redundant GetPeerAddress requests to the server

pynicotine/gtkgui/chatrooms.py
+ Changed: Don't allow usernames that contain URL's to be hyperlinks in the activity view.
=> gtkgui/chatrooms.py: don't parse URL's in activity_view

pynicotine/gtkgui/__init__.py, pynicotine/gtkgui/application.py, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/dialogs/fastconfigure.py, pynicotine/gtkgui/dialogs/preferences.py, pynicotine/gtkgui/dialogs/statistics.py, pynicotine/gtkgui/dialogs/wishlist.py, pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/uploads.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userlist.py, pynicotine/gtkgui/widgets/dialogs.py, pynicotine/gtkgui/widgets/iconnotebook.py, pynicotine/gtkgui/widgets/popupmenu.py, pynicotine/gtkgui/widgets/theme.py, pynicotine/gtkgui/widgets/trayicon.py
- Use Adw.MessageDialog instead of deprecated Gtk.MessageDialog when libadwaita is enabled
- Use clearer labels for affirmative buttons according to GNOME HIG
- Add support for suggested/destructive buttons
- Make affirmative buttons activate by default according to GNOME HIG
- Stop using deprecated Gtk.ResponseType when possible
- Various API cleanups
=> Modernize message dialogs

pynicotine/shares.py
=> shares.py: don't use recursion when scanning shares

pynicotine/config.py, pynicotine/gtkgui/dialogs/fastconfigure.py, pynicotine/gtkgui/dialogs/preferences.py, pynicotine/gtkgui/widgets/filechooser.py, pynicotine/gtkgui/widgets/theme.py, pynicotine/logfacility.py, pynicotine/plugins/core_commands/__init__.py, pynicotine/shares.py, pynicotine/transfers.py, pynicotine/userbrowse.py, pynicotine/userinfo.py, pynicotine/utils.py, test/unit/transfers/test_transfers.py
MinGW's Python uses forward slashes as path separators, but paths from e.g. GTK's file chooser use backslashes. Ensure that we don't end up with a mix of different separators on Windows.
=> Normalize all incoming file paths

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/widgets/textview.py
Code cleanup/optimization (no functional changes)...
+ Refactor with block, only keep file open for as long as needed to deque lines.
+ Don't wrap the getting of user tags, url tags, inserting text and other functions within try/except OSError block.
The only purpose of catching the OSError is in case the log file does not exist, no point including all the other calls within it.
=> ChatView: cleanup open read_room_logs

pynicotine/config.py, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/widgets/notifications.py
Closes #2551
+ Added: Window title notification and taskbar urgency hint for "Wishlist Results Found"
- Removed: Defunct ["ui"]["urgencyhint"] config setting (it was not in Preferences dialog)
+ Changed: Urgency hints now follows the ["notifications"]["notification_window_title"] config setting
=> gtkgui/notifications.py: wishlist urgency hint

pynicotine/gtkgui/application.py, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/interests.py, pynicotine/gtkgui/mainwindow.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/userbrowse.py, pynicotine/gtkgui/userinfo.py, pynicotine/gtkgui/userlist.py, pynicotine/gtkgui/widgets/textentry.py, pynicotine/gtkgui/widgets/textview.py, pynicotine/gtkgui/widgets/theme.py, pynicotine/plugins/auto_user_browse/__init__.py, pynicotine/plugins/core_commands/__init__.py, pynicotine/userlist.py
Code cleanups:
- Removed: Unused `message_class` argument and variable from textentry.py.
- Removed: Don't import entire `slskmessages` module in 15 cases where only `UserStatus` is required.
- Removed: Don't import entire `slskmessages` module in 2 cases where only `FileListMessage` is required.
=> ChatEntry: remove unused message_class argument

pynicotine/gtkgui/transferlist.py
The call to get the human speed or time values can and should be avoided in most iterations of the row update, because it's not required if it's the same value.
=> transferlist.py: don't get human speed unless value is changed

pynicotine/portmapper.py
Closes #2573 
- Avoid strange NoneType Critical Error if `_active_implementation` is None.
- It is slightly easier to understand the exceptions nested the other way around.
This PR does not the address the reason why the Critical Error handler incorrectly picked up a mapping failure in the bug report.
=> portmapper.py: mapping error handler cleanup

pynicotine/gtkgui/application.py, pynicotine/gtkgui/dialogs/preferences.py, pynicotine/gtkgui/mainwindow.py, pynicotine/gtkgui/widgets/notifications.py, pynicotine/gtkgui/widgets/trayicon.py
Restores tray icon and notification support on Windows.
=> trayicon.py: add Win32 implementation

pynicotine/gtkgui/search.py, pynicotine/gtkgui/widgets/textentry.py
+ Fixed: regression since commit 58483c7005806e2b4f589a4001d132f00699f62d in Search Files whereby the filter entries cannot be cleared using the Clear All Filters button. Instead some most recent list items are selected and this screws up `filters_undo`.
- Removed: Selection of list item handling from within the search module, since we want the selection characteristics to be native to our ComboBox widget because it is appropriate for the current item (if present in the list) to be highlighted in all cases.
- Changed: Don't select first item but instead highlight the most recently selected item if the text does not match any list items, this it what should happen anyway... We have to be careful not to overwrite any previous manually entered settings in Preferences.
=> ComboBox: select item on dropdown visible

pynicotine/plugins/core_commands/__init__.py, pynicotine/plugins/examplars/commands/PLUGININFO, pynicotine/plugins/examplars/commands/__init__.py
- Moved: `/sample` command into examplars.
There is scope for more elaborate examples with explanatory comments and documentation, but for now it is just moved out of the core_commands plugin.
=> core_commands: move sample command to examplars

.flake8, .github/workflows/packaging.yml, .github/workflows/tests.yml, MANIFEST.in, doc/DEPENDENCIES.md, packaging/windows/dependencies.py, setup.cfg, setup.py
flake8 bundles pycodestyle, pyflakes and mccabe, but pylint already includes all rules that exist in pyflakes and mccabe.
=> Use pycodestyle instead of flake8

pynicotine/gtkgui/search.py
+ Fixed: Filter could become stuck if the history was changed on another search page, then clear on click action was inop.
- Changed: Compare the actual filter text instead of item from stored history, because that is liable to be changed elsewhere.
Bug probably existed since original implementation of the icon_press action, i.e. unrelated to recent development.
=> gtkgui/search.py: fix on filter entry icon press to clear

pynicotine/utils.py
STARTF_USESHOWWINDOW and STARTUPINFO seem to be Windows-only functions, on Linux the import fails when calling utils.py (when clicking on a link, for example).
=> Only import STARTF_USESHOWWINDOW and STARTUPINFO if platform is win32

pynicotine/core.py, pynicotine/gtkgui/application.py, pynicotine/gtkgui/mainwindow.py, pynicotine/gtkgui/ui/dialogs/shortcuts.ui, pynicotine/gtkgui/ui/mainwindow.ui, pynicotine/gtkgui/ui/settings/userinterface.ui, pynicotine/slskproto.py, pynicotine/transfers.py, test/unit/transfers/test_get_upload_candidate.py
Current behavior in this PR:
- Quitting Nicotine+ from the tray icon or operating system's quit menu item exits immediately, since showing confirmation dialogs here is not common behavior for applications (and users have requested to not show them here before)
- Quitting inside Nicotine+ (Menu -> Quit or Ctrl+Q) always shows a confirmation dialog, with an option to finish uploads before exiting. As before, the Ctrl+Alt+Q shortcut can be used to quit immediately.
- Closing the main window (using the X button or Alt+F4) follows the preference set in Preferences -> User Interface (Quit, show confirmation dialog or run in background)
Closes #885
=> Add option to wait for uploads to finish when quitting

pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/transferlist.py
User profiles are an integral part of the Soulseek network. It's where you learn more about a user's collection, requirements and how to get access to private files.
Currently, the menu item for viewing a user's profile is buried in a submenu, making it awkward to access frequently. Add a primary menu item to make user profiles more obvious and easier to access, similar to SoulseekQt.
=> search.py: add context menu item to view user profiles

doc/SLSKPROTOCOL.md, pynicotine/downloads.py, pynicotine/gtkgui/transfers.py, pynicotine/uploads.py
Soulseek NS only sends this status message in response to legacy download requests, which we no longer use.
Modern Soulseek clients send a UploadFailed message when a file connection closed unexpectedly, but Soulseek NS also sends it at the beginning of an upload attempt when it can't read a file. Instead of marking these files with a "Remote file error" status, which will be incorrect in most cases, add a new local "Connection closed" status.
Additionally, start sending a "File read error." rejection message when we can't read a file when uploading, instead of a "File not shared." message. This is what SoulseekQt does (although SoulseekQt sends an incorrect path, making the message not appear in the UI).
=> Stop using 'Remote file error' transfer status

pynicotine/core.py, pynicotine/gtkgui/application.py, pynicotine/gtkgui/mainwindow.py, pynicotine/gtkgui/ui/dialogs/shortcuts.ui, pynicotine/gtkgui/widgets/trayicon.py, pynicotine/uploads.py
Behavior is currently as follows:
- Confirmation dialog only shows 'Wait for uploads to finish' checkbox when there are active uploads
- Ctrl+Q always shows confirmation dialog, to prevent accidentally quitting Nicotine+
- Window X button always shows confirmation dialog (can be changed in preferences)
- Ctrl+Alt+Q and OS-level menus (tray icon and main icon right-click menu) force quit Nicotine+
- In all other cases, a confirmation dialog is only shown when 1. there are active uploads, and 2. Nicotine+ is running in the foreground. Showing detached dialogs when attempting to quit an application running in the background usually doesn't work well, and can be disruptive (see e.g. #2487).
Feedback welcome.
=> Changes to confirmation dialog behavior when quitting

pynicotine/chatrooms.py, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/popovers/roomlist.py, pynicotine/gtkgui/ui/chatrooms.ui, pynicotine/privatechat.py, pynicotine/slskmessages.py
Instead of waiting for a response from the server before showing a chat room tab, show it immediately.
Benefits:
- All tabs in Nicotine+ now behave the same
- Can read chat room history before connecting to the server
- Makes Nicotine+ feel faster, since slow connections no longer determine when tabs will be added
- If you're no longer able to join a private room that you've joined in the past, the tab still appears, allowing you to remove the room without manually editing the config. Redirect private messages from the server about room join failures to the appropriate chat room tab.
=> Show chat room tabs before connecting to server

pynicotine/cli.py, pynicotine/core.py, pynicotine/headless/application.py, pynicotine/plugins/core_commands/__init__.py
These changes are enough to get you up and running in headless mode, but avoids adding commands for logging in as another user or changing your password.
We should add these eventually, but it will require more discussion and work to get them right. For now, I'm simply adding the bare minimum to get Nicotine+ 3.3.0 out the door.
=> CLI: prompt for username and password when necessary

pynicotine/downloads.py, pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/transfers.py, pynicotine/tests/unit/transfers/test_downloads.py, pynicotine/tests/unit/transfers/test_uploads.py, pynicotine/transfers.py, pynicotine/uploads.py
- Use a dictionary for download list for fast transfer object retrievals
- Update parent rows of individual transfers once per second, to prevent redundant updates in case of many upload rejection messages
=> Performance improvements for transfers

.github/workflows/tests.yml, debian/control, pynicotine/tests/integration/test_startup.py
Note that Ubuntu 22.04 doesn't ship gtk4-broadwayd, so we still need to use Xvfb there.
=> test_startup.py: remove dependency on Xvfb

pynicotine/gtkgui/dialogs/statistics.py, pynicotine/transfers.py
Minor performance optimization
+ Fixed: After the Statistics dialog is shown once or more then closed then it's unnecessary to make the strings thereafter
=> Statistics: update ui values only if dialog is visible

pynicotine/gtkgui/dialogs/statistics.py, pynicotine/gtkgui/ui/dialogs/statistics.ui
Stats for both started and finished transfers were originally added when Nicotine+ had several bugs in its transfers module, and we wanted to know what percentage of transfers failed.
The statistics for started transfers have a flaw though: pausing and resuming a transfer counts as a new one. I don't think they are worth keeping, since the number of completed transfers seems more useful. It would also give us more space to potentially add more statistics to the GUI.
I don't want to remove any stored statistics yet, but I'd like to remove started transfers from the GUI, and see if we get any feedback/complaints about it. If not, we can remove them completely in a future release.
=> Statistics: remove started transfers from GUI

pynicotine/tests/unit/transfers/test_downloads.py, pynicotine/userbrowse.py
=> userbrowse.py: don't select folders with similar name when recursing

pynicotine/gtkgui/buddies.py, pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/transfers.py, pynicotine/gtkgui/widgets/treeview.py
For now, this is only done for downloads, uploads, buddies and chat room users. Remembering the sort order of searches and user shares is too intrusive, always sort search results by speed instead.
Closes #373 
Closes #2170 
Closes #2758
=> treeview.py: remember column sort order

pynicotine/gtkgui/application.py, pynicotine/gtkgui/widgets/trayicon.py
The dialogs have existed for many years, but it doesn't seem like they would be used very often. Since we have chat and wishlist notifications, add shortcuts to these tabs instead.
This simplifies things a bit, and also gets rid of a few translatable strings.
Closes #2805
=> Tray Icon: replace dialogs with main tab shortcuts

NEWS.md, README.md, data/org.nicotine_plus.Nicotine.appdata.xml.in, debian/changelog, doc/DOWNLOADS.md, pynicotine/__init__.py
PR is mainly for testing CI in preparation for release. We could try to target February 1 as the release date if no serious bugs emerge, but we can revisit the situation in a week.
=> Version 3.3.0

pynicotine/shares.py
Added the Synology #snapshot and #recycle folders to be excluded from Share as these folders contain data that have been already deleted which may be a security issues and may flood the SLSK network with unnecessary files.
=> Add HIDDEN_FOLDER_NAMES class to shares.py for easier management to exclude multiple folders from shares

pynicotine/gtkgui/userbrowse.py
+ Changed: label used in folder popup menus, this frees up the "U" key that could be better used for an "Upload" item.
Same string as used elsewhere.
=> gtkgui/userbrowse.py: "Copy Folder U_RL" menu item label

pynicotine/shares.py
+ Fixed: The numbers were prevented from updating because method only runs after `self.rescanning` is set to `False`
=> shares.py: don't block send_num_shared_folders_files()

pynicotine/gtkgui/downloads.py
+ Changed: dialog button labels, because generic labels may lead to incorrect selection as discussed in #2910
Using existing strings.
=> gtkgui/downloads.py: descriptive button labels in large folder dialog

pynicotine/slskproto.py
+ Changed: to avoid exception 'OSError: [Errno 101] Network is unreachable' # (doesn't need to be reachable)
Edge-case platform-sepcific regression since add35dc0, exception is handled in `_bind_listen_port()` which throws to log:
```
Your branch is up to date with 'origin/master'.
~/git/slook/nicotine-plus $ python3 ./nicotine
[2024-03-04 10:54:53] Loading Python 3.11.8
[2024-03-04 10:54:53] Loading Nicotine+ 3.3.3.dev1
[2024-03-04 10:54:53] Translation files (.mo) are unavailable, using default English strings
[2024-03-04 10:54:53] Loading GTK 4.12.4
[2024-03-04 10:54:54] Loading plugin system
[2024-03-04 10:54:54] Loaded plugin Nicotine+ Commands
[2024-03-04 10:54:54] Reconnecting to server in 12 seconds
[2024-03-04 10:54:54] Cannot listen on port 2234. Ensure no other application uses …
```
=> slskproto.py: broadcast with connect_ex() in local_ip_address()

pynicotine/plugins/core_commands/__init__.py
Otherwise it's nearly impossible to determine our own username when running in headless mode, except for using the /ip command for localhost address 127.0.0.1
Suggestion for different code would be welcomed if there is a neater structure of the if condition block?
=> Core Commands: /away command shows login username on output

pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/search.py, pynicotine/gtkgui/uploads.py
+ Added: Select the selected file when browsing to the folder from a "_Browse Folder" context menu action
The `_basename` data already exist but they were discarded, yet there is no good reason to truncate the `path` because in most cases where this function is called (usually from a file selection) it seems expected to select a file in the shares, if it still exists there.
=> gtkgui: select selected file on_browse_folder()

pynicotine/gtkgui/dialogs/preferences.py
It wouldn't work because of a 403 HTTP status, but this was because
the program showed that you had to put a colon after username;apikey
I removed this from the UI and now it works.
=> Fix last.fm now playing

pynicotine/slskproto.py, pynicotine/tests/unit/protocol/test_slskproto.py
Rationale: https://news.ycombinator.com/item?id=40310896
=> Use TCP_NODELAY on the server socket

pynicotine/gtkgui/ui/mainwindow.ui
* Fixed: Show normal mouse cursor over empty area of status bar, instead of incorrectly showing text selection beam cursor...
_Before:_
_After:_
... It is done by using using a GtkBox as a filler widget for doing the hexpand, for want of a better way?
=> mainwindow.ui: show normal mouse cursor over empty area of status bar

pynicotine/gtkgui/transfers.py
+ Changed: Avoid one `human_size()` call for each Finished transfer, it's also faster to read and more logical to view.
=> gtkgui/transfers.py: don't display current_byte_offset when finished

pynicotine/utils.py
Minor optimization.
+ Changed: Only measure the lengths of `text` and `word` once, instead of doing so for each instance of `word`.
Relevant in the unlikely, but possible, scenario that there are many subword instances of the word in a large text.
=> utils.py: optimize string length measurements in find_whole_word()

pynicotine/utils.py
Minor cleanup.
- Removed: try/except block because there aren't any calls that could lead to a TypeError being encountered anymore (if there ever was, then it doesn't seem to the case now).
=> utils.py: don't catch TypeError in _human_speed_or_size()

pynicotine/gtkgui/popovers/chathistory.py
Minor code cleanup:
+ Changed: Give `load_user()` a decorator to indicate that this function could be placed elsewhere (ideally, within the core)
=> chathistory.py: make load_user() a staticmethod

pynicotine/config.py
- Removed: There is no reference to the "readroomlogs" setting anywhere, it would be redundant anyway because the number of lines can be set to zero for the same intended effect as turning this off.
=> config: remove unused "readroomlogs" setting

pynicotine/core.py, pynicotine/events.py, pynicotine/gtkgui/application.py, pynicotine/gtkgui/downloads.py, pynicotine/gtkgui/mainwindow.py, pynicotine/gtkgui/transfers.py, pynicotine/gtkgui/uploads.py, pynicotine/headless/application.py, pynicotine/slskproto.py, pynicotine/uploads.py
The previous code was bad/sloppy for many reasons:
- Core should not be aware of uploads, only the uploads module should
- No events for starting/stopping a pending shutdown for uploads
- Implemented in the wrong module
- Gave me a headache when reading it
Based on previous feedback from users, also change the behavior to always show a confirmation dialog on quit if uploads are active (unless the window is hidden/running in the background).
=> uploads: refactor code related to pending shutdown

pynicotine/gtkgui/chatrooms.py, pynicotine/gtkgui/privatechat.py, pynicotine/gtkgui/widgets/textview.py
Minor UI change:
+ Changed: Don't timestamp the `--- old messages above ---` separator line, because the complexity required in the code it is not really worthwhile for this purpose, actually it is visually easier to spot it with no timestamp.
Minor code cleanups:
+ Changed: the lowercase `login_username` string is required for each line in lines, so it needs doing only once beforehand
+ Changed: Call the `read_log()` method directly from gui module instead of parsing config values into the widget
+ Removed: no caller gets the value that was returned by append_line()
This structure of methods is part of what will be required for future enhancements that are planned in draft PR #2792 (please try running that branch and let me know what you think of the overall idea), but this PR is ready …
=> ChatView: don't timestamp old messages separator in append_log_lines()

pynicotine/buddies.py, pynicotine/chatrooms.py, pynicotine/downloads.py, pynicotine/gtkgui/popovers/chathistory.py, pynicotine/interests.py, pynicotine/privatechat.py, pynicotine/slskproto.py, pynicotine/transfers.py, pynicotine/uploads.py, pynicotine/userbrowse.py, pynicotine/userinfo.py, pynicotine/users.py
Currently, the list of watched users grows indefinitely until we disconnect/quit. Unwatch users when we no longer need to track them.
=> Unwatch users when updates are no longer needed

pynicotine/config.py
- Changed: increase default `max_displayed_results` to `2000` because the application has become much more performant since this default was last increased two years ago, and there are generally more results readily available on the network as well.
=> config.py: increase default max_displayed_results to 2000

pynicotine/gtkgui/widgets/textentry.py
+ Added: Goto end of chat log by pressing Return key or click send message icon while entry is empty, instead of a noop.
Scrolling to the bottom is probably what is desired when sending a non-empty message as well, but that is not implemented in this PR because `scroll_bottom()` is usually called anyway if there is text present in the entry and the view is already at the bottom.
There doesn't seem to be any possibility that `chat_view` will be `None` because `send_message()` isn't available before the parent is set, but there might be a better method of implementing the desired behaviour without causing duplicated scrolling events?
=> ChatEntry: Scroll to bottom on entering empty message

pynicotine/gtkgui/application.py, pynicotine/gtkgui/mainwindow.py
Per definition, urgency hints should only be used when a timely response is required (typically instant messaging).
Fixes #3123
=> Only set window urgency hint for private chats and mentions

.github/workflows/website.yml
+ Added: Condition to restrict building (and thereby also blocking deploy) only when running on the official repo
The CI always fails on forked repo's because the website can't be deployed anywhere other than in the official repo, it is annoying to have the [failure notifications](https://github.com/slook/nicotine-plus/actions/workflows/website.yml) appear whenever synchronizing latest changes for testing.
=> website.yml: prevent forks from attempting to deploy pages

.github/workflows/website.yml
+ Added: Avoid unnecessarily deploying the site unless .md file(s) are being pushed
If there is a case for deploying pages to the the site other than when a markdown file is altered, then the workflow can be manually dispatched.
=> website.yml: deploy pages only when pushing markdown files

debian/copyright
In previous PR #3131 I failed to notice that the path had also changed.
=> debian/copyright: correct path to data/ip_country_data.csv

.github/workflows/tests.yml
+ Removed: `brew update` from the `macos-12` runner, doesn't need to be patched to do its job
=> tests.yml: don't update legacy macOS platform for tests

data/org.nicotine_plus.Nicotine.appdata.xml.in, debian/changelog, pynicotine/__init__.py
Waiting for the libadwaita 1.6 release to pair with GTK 4.16 before merging this.  Should happen within this week.
=> Bump version to 3.3.5rc2

README.md, doc/DOWNLOADS.md, doc/TESTING.md
All the nightly links to artifacts from old action runs expired long ago and so are now broken, so these deep links need updating to support legacy users who may need to look on GitHub for old versions to install.
+ Fixed: Broken links to old binary packages in the `3.2.x` branch
+ Changed: Instances of phrases like "current version" -> "legacy version" or "old version" to avoid confusion
+ Changed: Synchronize TESTING.md with the `master` branch to replace all the Nightly links which are broken now
+ Changed: "Portable" -> "Standalone" to match the same terminology used in the master branch
Preview it on my fork links:
https://github.com/slook/nicotine-plus/blob/docs-legacy-3.2.9/README.md
https://github.com/slook/nicotine-plus/blob/docs-legacy-3.2.9/doc/DOWNLOADS.md
=> docs: links to old version of Nicotine+ 3.2.9 for legacy users

pynicotine/downloads.py, pynicotine/tests/unit/transfers/test_downloads.py
If the user's incomplete download folder contains other unrelated files, ensure we don't delete them.
Fixes #3152
=> downloads.py: only remove actual stale incomplete downloads

.github/workflows/packaging.yml, .github/workflows/tests.yml, doc/DEPENDENCIES.md, packaging/macos/dependencies.py, packaging/windows/dependencies.py
By default, python3-build builds packages in a virtual environment, which contains dependencies like setuptools and wheel. Add a step that attempts building without the virtual environment.
=> CI: test building without isolation

pynicotine/transfers.py, pynicotine/uploads.py
=> transfers.py: reset last_byte_offset when aborting transfer

pynicotine/core.py, pynicotine/gtkgui/dialogs/preferences.py, pynicotine/gtkgui/ui/settings/chats.ui, pynicotine/gtkgui/ui/settings/network.ui, pynicotine/gtkgui/ui/settings/search.ui, pynicotine/slskmessages.py, pynicotine/slskproto.py, pynicotine/users.py
Closes #2704 
Two translatable strings are modified, but since the only change is removing the `(requires a restart)` part from them, we could modify the translated strings manually and include this PR in Nicotine+ 3.3.7.
=> Reconnect when changing listening port or network interface

pynicotine/gtkgui/mainwindow.py, pynicotine/gtkgui/ui/mainwindow.ui, pynicotine/shares.py
We should give users a sign that the scanner is actually doing something.
The strings are a bit of a mess currently, since we can't add new translatable strings in 3.3.x, but we can improve the situation in 3.4.x.
=> Show folder count while rescanning shares

pynicotine/downloads.py, pynicotine/tests/unit/transfers/test_downloads.py
Fixes #3255
+ Added: Use count argument of replace() to avoid erroneously replacing subsequent parts of the path
+ Changed: Longer test folder paths in the relevant CI test module in order to cover this bug
=> downloads.py: only remove first occurrence of removed_parent_folders

.github/workflows/tests.yml
https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
This job uses development versions of GTK and other libraries, so it could be useful to catch any arm64 regressions.
=> tests.yml: test Fedora Rawhide on arm64

NEWS.md, pynicotine/logfacility.py
Turns out using deque for reading lines from a large file is really slow, even when you only want to show a fraction of the contents in the GUI. Use a more efficient implementation for reading lines instead.
Some profiling results (150 MB log file):
Master:
#2792:
This PR:
@slook This change is relevant for #2792.
=> logfacility.py: Optimize reading of log lines

pynicotine/logfacility.py
+ Changed: Use built-in constant instead of READ_BLOCK_SIZE use [io.DEFAULT_BUFFER_SIZE](https://docs.python.org/3/library/io.html#io.DEFAULT_BUFFER_SIZE):
> _An int containing the default buffer size used by the module’s buffered I/O classes. [open()](https://docs.python.org/3/library/functions.html#open) uses the file’s [blksize](https://docs.python.org/3/library/os.html#os.stat_result.st_blksize) (as obtained by os.stat()) if possible._
On my system this is `8192` instead of `4096`.
Imported the entire `io` module since other functions from it are likely to be required in future.
=> logfacility.py: READ_BLOCK_SIZE -> io.DEFAULT_BUFFER_SIZE

pynicotine/downloads.py, pynicotine/transfers.py, pynicotine/uploads.py
Queue position requests are sent in batches, and calculating the position for each request is slow. Cache the positions until the queue changes.
Fixes #3199
=> uploads.py: temporarily cache queue positions

doc/DEVELOPING.md
- Removed: Inaccurate mention of Python `3.6`
+ Added: Link to [Status of Python versions chart](https://devguide.python.org/versions/#python-release-cycle) on the Python website
+ Added: When incrementing `B` mention the creation of old feature branches to enable critical bug fix maintenance
+ Added: Fourth point to keep in mind about old branch maintenance
=> DEVELOPING.md: don't mention oldest Python version number

doc/DEVELOPING.md
- Removed: Outdated and irrelevant detail about running the test suite locally, since GitHub Actions make this task superfluous.
=> DEVELOPING.md: simplify Continuous Integration Testing section

pynicotine/gtkgui/ui/settings/network.ui
1. Add (For VPN) so VPN users know they should look into this setting.
2. Make tooltip easier to understand and translate
=> Help VPN users

pynicotine/shares.py, pynicotine/transfers.py, pynicotine/uploads.py
Make things a bit easier for our users, so they don't have to deal with private messages from Soulseek NS users about not sharing files.
Fixes #3277
=> Add lowercase file path mapping for Soulseek NS clients

pynicotine/shares.py, pynicotine/transfers.py, pynicotine/uploads.py
=> Substitute non-separator backslashes in file paths

pynicotine/gtkgui/ui/popovers/searchfilterhelp.ui
+ Added: Public Files section in Search Result Filters Help popover
> _Public Files_
>
> Only show files that are shared publicly, and hide privately shared files which cannot be downloaded until the uploader gives explicit permission.
=> searchfilterhelp.ui: Public Files

pynicotine/gtkgui/dialogs/pluginsettings.py, pynicotine/gtkgui/dialogs/preferences.py, pynicotine/gtkgui/ui/settings/plugin.ui, pynicotine/pluginsystem.py
No breaking changes in this PR. It is a minor code cleanup only.
Code cleanups related to logical naming for plugin settings, metasettings and pluginsettings dialog only:
- Renamed: `plugin` -> `plugin_name` where it is a string of the plugin.internal_name and not the plugin object itself
- Renamed: `plugin_id` -> `plugin_name` everywhere
- Renamed: `plugin_name` -> `plugin_human_name` where the string is plugin.human_name and not plugin.internal_name
- Renamed: `name` -> `option_name` where the key is the name of an option and not either of the names of the plugin
- Renamed: `settings` -> `metasettings` where the object is a plugin's metasettings dict() and not a plugin's config settings
- Renamed: `plugin_settings` -> `plugin_settings_dialog` where the widget is a GtkDialog and not …
=> PluginSettings: settings and plugin_name object naming cleanup

pynicotine/gtkgui/application.py, pynicotine/gtkgui/transfers.py
We currently have a R shortcut for resuming/retrying transfers, and T shortcut for pausing/aborting transfers. There are two issues with these shortcuts:
- They are bare keys, which conflict with 'type to search' in the transfer list.
- They are right next to each other, which is good for reachability, but makes it too easy to press the wrong key.
I've replaced the shortcuts with Ctrl+S (S as in start) for resuming/retrying transfers, and Ctrl+T (T as in terminate) for pausing/aborting transfers.
The goal is to use shortcuts that are easy to activate with a single hand, and fairly close to each other, but not close enough to cause confusion. We also want to avoid using shortcuts that are very common and have different meanings in other contexts. While Ctrl+S is commonly used for saving …
=> transfers.py: Replace bare key shortcuts with more sensible ones
